### ISSUE TITLE
Lem-in: can someone re-check this change? (for example02)

### ISSUE THREAD

**Issue by nik-don** [01-edu/public#1006]
The instuctions are:

> Each room can only contain one ant at a time (except at ##**start** and ##**end** which can contain as many ants as necessary).
> 
> To be the first to arrive, ants will need to take the shortest path or paths. They will also need to avoid traffic jams as well as walking all over their fellow ants.
> 
> You will only display the ants that moved at each turn, and you can move each ant only once and through a tunnel (the room at the receiving end must be empty).
> 

For this example (example02.txt)
The paths are:
3 OR 1,2,3
and 3 is the **end** room

As the end room can contain many ants.. All the ants can just move forward to the end room one by one.
Therefore I believe this shouldnt have been changed.

![image](https://user-images.githubusercontent.com/93073558/157689519-38c76db8-06af-470f-a8eb-e3bd45a66561.png)

_Originally posted by @nik-don in https://github.com/01-edu/public/issues/901#issuecomment-1064157910_

**Comment by MSilva95** [comment]
In that example the ants are moving all at the same time which will cause a  traffic jam, and as we say in the subject we need to avoid that.
That example is valid if done this way:
```
L1-3
L2-3
L3-3
L4-3
L5-3
L6-3
L7-3
L8-3
L9-3
L10-3
L11-3
L12-3
L13-3
L14-3
L15-3
L16-3
L17-3
L18-3
L19-3
L20-3
```

**Comment by nik-don** [comment]
@MSilva95 I agree completely. But do we ONLY care about the number of turns. Or should we consider the number of steps as well.
Please see my comment here: https://github.com/01-edu/public/issues/901#issuecomment-1064402728
Thanks

**Comment by MSilva95** [comment]
The purpose is to find the fastest way to get from start to the end.
So it doesn't matter if you take more steps if you reach the end faster ...
In this case instead of having just one ant leaving the start room we can have two ants moving at the same time in different tunnels witch will be faster.
The fewer turns you have the faster it will be.

**Comment by MSilva95** [comment]
And as i said above, the other example was wrong because you can't have more than one ant at the tunnel as it is considered a traffic jam.
