### ISSUE TITLE
[ADMIN OBJECT FORM] - Name of a child changing to its parent name

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#101]
When accessing an object set as a child of an object by clicking the Original object link, it changes the name of the object and replaces it by the name of the parent he's contained in.

1. Go to the children of an object
2. Click on the link after 'Original object'
3. Scroll to the top of the object
4. See the name is now the name of its parent

The name of the object mustn't be altered.

<img width="1552" alt="Screenshot 2019-05-03 at 17 38 14" src="https://user-images.githubusercontent.com/4631239/57152259-d708a480-6dca-11e9-8b70-2a0ec89fa3e0.png">
<img width="1552" alt="Screenshot 2019-05-03 at 17 38 22" src="https://user-images.githubusercontent.com/4631239/57152260-d708a480-6dca-11e9-949d-2786c175751b.png">

**Comment by bde-maze** [comment]
I don't have this bug in a previous version, may be it poped up with the new child integration. I will look into it
