### ISSUE TITLE
issorted subject

### ISSUE THREAD

**Issue by asyamak** [01-edu/public#1010]
issorted
---
_IsSorted(main.isSortedBy10, []int{999898, 980726, 813814, 454688, 152258, 75453, 42450, -904975}) == false instead of true_

Found a mistake in the test case above. The code above should return false, but i think the test case think it should return true.

Here is my code:
```
package piscine

func IsSorted(f func(int, int) int, a []int) bool {
	des := false
	asc := true

	for i := 1; i < len(a); i++ {
		if f(a[i-1], a[i]) > 0 {
			asc = false
		}
	}

	return asc || des
}

func f(a, b int) int {
	if a > b {
		return 1
	} else if a == b {
		return 0
	} else {
		return -1
	}
}
```

**Comment by MSilva95** [comment]
Hello @asyamak! 
Its not the test returning the false value, it is your code the one returning false.
Here is another example that your code fails:
```a3 := []int{8, 7, 2, -1, -4, -5, -10}```
This is sorted and your code returns false.
