### ISSUE TITLE
cl-camp2 subject

### ISSUE THREAD

**Issue by OnRoad6** [01-edu/public#1015]
cl-camp2

Exercice n° 1, question n° 5, dans le sujet, enlevez le $ de la 2ème ligne.
E° 1, Q° 5, in the subject, take the $ off of the 2nd line.
---

**Comment by MSilva95** [comment]
Hello @OnRoad6!
Thank you for the catch i will be removed soon.

Tip: try to structure and specify the issues better, it was a little confusing to understand.

**Comment by MSilva95** [comment]
Sorry after a confirmation i ended up realizing that the $ is supposed to be there in the example because of the flag -e in the cat command.
Thank you for the feedback!
