### ISSUE TITLE
cl-camp3 subject

### ISSUE THREAD

**Issue by OnRoad6** [01-edu/public#1017]
Je suis désolé, mais je trouve cette Question n° 6 difficile et je ne cherche pas à me plaindre, vu que j'ai ai passé 08 h sans y parvenir.
Ce que je déteste dans cette question est l'ordre de tri que vous me demandez, j'ai tout essayé.

I apologize, but I deem this Q° 6 difficult and I don't aim to complain, because I spent 08 h of time without achieving.
What I hate in this Question is the sort order you asked me, I all intended.

**Comment by MSilva95** [comment]
Hello @OnRoad6!
This question is very clear, we do not find it difficult at all.
Are you the only one who got stuck or are there other students in the same situation?
Perhaps the best thing when you are in this situation is to start talking to someone who is in the same situation as you, or someone who has already done the exercise to give you some tips and guide you to a solution.

**Comment by OnRoad6** [comment]
I must check more details about find command.
Normally, that is sufficient, more than my brain, to achieve.
You'll be noticed.

Regards.
________________________________
De : MSilva95 ***@***.***>
Envoyé : mardi 22 mars 2022 11:13
À : 01-edu/public ***@***.***>
Cc : OnRoad6 ***@***.***>; Mention ***@***.***>
Objet : Re: [01-edu/public] cl-camp3 subject (Issue #1017)


Hello @OnRoad6<https://github.com/OnRoad6>!
This question is very clear, we do not find it difficult at all.
Are you the only one who got stuck or are there other students in the same situation?
Perhaps the best thing when you are in this situation is to start talking to someone who is in the same situation as you, or someone who has already done the exercise to give you some tips and guide you to a solution.

**Comment by OnRoad6** [comment]
J'ai trouvé la solution.
Il fallait se rapprocher du manuel ou de Google, pour find.

I found the solution.
It was bound to join the manual or Google, all about find.
________________________________
De : MSilva95 ***@***.***>
Envoyé : mardi 22 mars 2022 12:16
À : 01-edu/public ***@***.***>
Cc : OnRoad6 ***@***.***>; Mention ***@***.***>
Objet : Re: [01-edu/public] cl-camp3 subject (Issue #1017)


Closed #1017<https://github.com/01-edu/public/issues/1017>.
