### ISSUE TITLE
cl-camp6 Unclear instruction

### ISSUE THREAD

**Issue by leviet0115** [01-edu/public#1020]
Hi, 

While testing the content on the dev environment, I found the instruction for exercise cl-camp6 is not clear enough. Below are the details:

**Current instruction:** 

`Create a file countfiles.sh, which will print the number (and only the number) of **regular files and folders contained in the current directory and its sub-folders**`

**Validation and master solution:**
The current directory needs to be included in the count too, which is not mentioned or implied in the instruction.

**Example:**
If the current directory has zero files and subfolders, the current correct answer is 1 instead of 0.

**Suggestion:**
Can we clarify this validation requirement mentioned above to the instruction or reconfigure the validation? So that students won’t be unnecessarily stuck at this exercise.

Link: https://01-dev.gritlab.ax/intra/gritlab/piscine-go/quest-01/cl-camp6

**Comment by MSilva95** [comment]
Hello @leviet0115! 
i will add a small clearance to this exercise. 
thank you for the feedback!
