### ISSUE TITLE
printreversealphabet  Hidden overflow text in File To Submit

### ISSUE THREAD

**Issue by leviet0115** [01-edu/public#1021]
Quest 2 - printreversealphabet

Hi, I found a display error with the long name of the file to submit. Please see below for details:

**Link**: https://01-dev.gritlab.ax/intra/gritlab/piscine-go/quest-02/printreversealphabet

**Issue**: The name of the File To Submit is partially hidden due to overflow. 
Full name: printreversealphabet/main.go. 
Display: printreversealphabet/main.

**Impact**:  Students may not pass validation due to the wrong file name.

![image](https://user-images.githubusercontent.com/64316728/159901908-a55f5fc0-b936-45f0-81d8-7e60ced43cfb.png)

**Comment by OGordoo** [comment]
Thank you for the feedback. We are fixing it now!

**Comment by MSilva95** [comment]
This was fixed here:

https://github.com/01-edu/all/pull/1148
