### ISSUE TITLE
strlen subject

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1022]
strlen
---
Hello this is Riad joined the team lately, I would like to point that it is possible to solve this exercise using the len function and type casting "len([]rune(s))" and my suggestion is to make the len()  function as a forbidden function

**Comment by MSilva95** [comment]
This is a good exercise for the students to learn how to use the len function and if they decide to use it in this exercise they will be forced to create a new one, because later on they will need a strLen function that does not use the len function.
So let's leave it like this.
