### ISSUE TITLE
makerange subject

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1026]
makerange
---
it can be validated using append

![makerange](https://user-images.githubusercontent.com/39562040/159913004-164faa92-fb41-4015-8167-b6f5fbbaa41d.png)

**Comment by MSilva95** [comment]
Hello @freeworldwhoo!
I will talk with Chris to see what does he think about removing the "allowedFunctions": ["--allow-builtin"], because this is what is causing the issue.

**Comment by MSilva95** [comment]
<https://github.com/01-edu/all/pull/1167>
