### ISSUE TITLE
point subject

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1028]
point
---
this solution passes 
![point](https://user-images.githubusercontent.com/39562040/159915879-39dc0adf-136a-4571-8995-12cd9de45c88.png)

**Comment by MSilva95** [comment]
This will soon not pass, it was a problem with a regex it will be merged in this pr:
https://github.com/01-edu/go-tests/pull/18

**Comment by MSilva95** [comment]
For this one i can probably make a restriction in the allowed functions to forbid this kind of cheating
So instead of this:
```{ 'point','{"allowedFunctions":["github.com/01-edu/z01.PrintRune", "--allow-builtin"]}'```

it will become something like this:

 ```'point','{"allowedFunctions":["github.com/01-edu/z01.PrintRune", "--allow-builtin", --no-lit=42.+21"]}'```

**Comment by MSilva95** [comment]
<https://github.com/01-edu/all/pull/1167>
