### ISSUE TITLE
cat subject

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1029]
cat
---
I submitted this files
![files to submit](https://user-images.githubusercontent.com/39562040/159916816-3c49d548-7c0e-4212-9b57-0a4ce0edfefc.png)
but I get this error
![error](https://user-images.githubusercontent.com/39562040/159916865-e2e38f42-92ce-4538-b42f-236b5e346e75.png)
and this in the console
![console log](https://user-images.githubusercontent.com/39562040/159916923-bb44d6ba-50e2-40c5-8274-d19309cffbac.png)

**Comment by MSilva95** [comment]
Are the txt files inside the cat folder?
They must be in the piscine repo not together with the main.go

**Comment by freeworldwhoo** [comment]
you're right my bad 😞 I just did  and it worked 😊
