### ISSUE TITLE
[SYSADMIN] - for every student session, students have to create password for locking session

### ISSUE THREAD

**Issue by sakenism** [01-edu/public#103]
**Describe the bug**
In each student session, we have to create new password.
**To Reproduce**
1. Set password (press lock session button)
2. Reboot

**Expected behavior**
Password for the flash should be saved first time students make a session, and we have to be able to change passwords on flashes if necessary

**Priority**
low

**Subject**
sysadmin

**Comment by xpetit** [comment]
Nice idea, thank you
