### ISSUE TITLE
exercises dots are redirecting to the wrong link 

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1030]
clicking on the dot to access exercise doesn't take you to the right link 
![exercise dots](https://user-images.githubusercontent.com/39562040/159918092-3b3210c6-2dfd-4c5d-8372-9eef08d68fec.png)

This happens only if I was previously in  "/piscine-go"
----

for example in quest09 if I click the second dot it should take me to the map exercise "/piscine-go/quest-09/map" but instead it takes me to "/piscine-go/map"

**Comment by MSilva95** [comment]
@MarieMalarme can you try to find out whats happening?
