### ISSUE TITLE
race.js in piscine-js doesn't produce an output in the console when performing a local test on a correct solution 

### ISSUE THREAD

**Issue by papshmeare** [01-edu/public#1033]
Expected behavior:
`node test.mjs PATH_TO/piscine-js-2 race` > all passed (9 tests)
Whereas right now the output would be nothing at all

**Comment by MSilva95** [comment]
On mine it's working fine, are you sure you gave the right path?

**Comment by papshmeare** [comment]
> 

I am sure the path is correct because if I intentionally break part of the solution it does indeed show where tests fail. Only when solution is correct it doesn't show completion output, are you saying that on your machine it shows `all passed (9 tests)`?

**Comment by MSilva95** [comment]
Yes on my machine it works as expected.

![race](https://user-images.githubusercontent.com/53977751/160129431-d4b54684-f835-4fc2-ba3a-5569dffbf676.png)

**Comment by MSilva95** [comment]
the repo in that pic is just a test repo called piscine go ...

**Comment by MSilva95** [comment]
I will close this issue, if the problem persists  you can reopen it
