### ISSUE TITLE
cat subject

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1035]
cat
---
in cat subject this is the expected output when file doesn't exist
![cat expected output](https://user-images.githubusercontent.com/39562040/160093736-11172cb7-cc30-4515-9bdc-87a6c39f52cd.png)
but it shows in the error a deferent expected output with an exit status of 1
![error output](https://user-images.githubusercontent.com/39562040/160093941-f9e57462-6a71-44d1-b155-35ceeed59259.png)
even if I create the same output and exit with status 1 it gives timeout error

**Comment by MSilva95** [comment]
I will change the readme to update the error message.

**Comment by freeworldwhoo** [comment]
okay sure also in the error it shows "exit status 1" but when I exit with status 1 it gives a timeout error

**Comment by MSilva95** [comment]
I just tested it and it works fine for me, it doesn't give me that error
