### ISSUE TITLE
graphql subject

### ISSUE THREAD

**Issue by SilverLuhtoja** [01-edu/public#1041]
graphql
---
Hello 

I wanted to ask if this exercises endpoint have somekind of limitations for  how much data we can fetch in one go. Example: in 
https://01.kood.tech/graphiql/ I can see over 250+ transactions , but when I fetch with js from address  https://01.kood.tech/api/graphql-engine/v1/graphql  it will only return 50 max.

**Comment by MSilva95** [comment]
Hello @SilverLuhtoja!
For security reasons the the number of transactions is limited to 50.
