### ISSUE TITLE
btreetransplant subject

### ISSUE THREAD

**Issue by hhaakkimm** [01-edu/public#1042]
btreetransplant
---
solution is not correct

**Comment by MSilva95** [comment]
Please provide some more info!
Tell us why do you think this is wrong for example, otherwise we cant find out what do you mean with "is not correct".
Is it Your solution not passing?
Do you think it's a problem with the test?

**Comment by MSilva95** [comment]
As this has no more info it will be closed.
Feel free to reopen it if you add some more info on the issue.
