### ISSUE TITLE
explain subject: limited possible solutions

### ISSUE THREAD

**Issue by sagarishere** [01-edu/public#1045]
explain
---
I coded the solution below and my final 4 suspects were different, but I arrived at the same final answer.

My suspects were selected / filtered on the basis of number of cars found in the wallet, which were 4. I only put in the suspect lists the people who were members of all the 4 clubs.

So, I derive at the same place, following a different set of filter criteria, and this does not match with the hard-coded solution.

A better idea would be to actually divide the problem in small bits, so that the final solution and the process could be checked, by seeing filters at various steps.

[here is the solution](https://gist.github.com/sagarishere/ac0fd2e787e2893893ae4d9f25d954aa)

**Comment by MSilva95** [comment]
I think this exercise is fine as it is.

You got all the info there in your filters just use that.

using the command info on your solution you can identify the main suspect of the last 5 by just looking for who has the blue honda and is a men...

# Mike Bostock 4 # -> has a Honda -> Color: Teal
# Matt Waite 4  ->  has a toyota not a honda
# Brian Boyer 4  ->  has a jag not a honda
# Hellen Maher 4 -> Is a woman
