### ISSUE TITLE
eightqueens subject

### ISSUE THREAD

**Issue by October45** [01-edu/public#1051]
eightqueens
---
Too easy to pass the test, you can do a for range loop on the "instead of" given string and print the runes.

```
package piscine

import "github.com/01-edu/z01"

func EightQueens() {
	var solutions string = "15863724\n16837425\n17468253\n17582463\n...(rest of string)"
	for _, c := range solutions {
		z01.PrintRune(c)
	}
}

```

**Comment by MSilva95** [comment]
Hello @October45!
What school are you from?

**Comment by October45** [comment]
@MSilva95 i'm a participant of the grit:lab piscine on the Åland Islands.

**Comment by MSilva95** [comment]
We will ask the admin to update the exercise in your school as this problem was solved in this pr <https://github.com/01-edu/all/pull/1139>
thank you for the feedback!
