### ISSUE TITLE
ascii-art-web-dockerize subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1060]
ascii-art-web-dockerize
---
Could you please clarify a bit the meaning of these two [audit questions](https://github.com/01-edu/public/blob/master/subjects/ascii-art-web/dockerize/audit.md#basic):

**- Is the file system of the containers well organized?**
What is considered "well organized"? This project usually includes a couple of code files, a html template, a css file and the 3 banner fonts. How should these few files be organised to be "well organised" or "badly organised"?

**- Does the project present no [unused object](https://docs.docker.com/config/pruning/)?**
The link refers to pruning unused Docker objects. Can you give an example of what would considered a prune object in this project? The project presents a simple Dockerfile and compiles a docker image that will be run. How to detect if there are any prune objects in the Docker image? Or should the project include instructions on how to clean up after stopping the container image?

**Comment by LEEDASILVA** [comment]
> - Is the file system of the containers well organized?
What is considered "well organized"? This project usually includes a couple of code files, a html template, a css file and the 3 banner fonts. How should these few files be organised to be "well organised" or "badly organised"?

This question should be removed

> - Does the project present no [unused object](https://docs.docker.com/config/pruning/)?
The link refers to pruning unused Docker objects. Can you give an example of what would considered a prune object in this project? The project presents a simple Dockerfile and compiles a docker image that will be run. How to detect if there are any prune objects in the Docker image? Or should the project include instructions on how to clean up after stopping the container image?

i think that this question should also be removed

@MSilva95 what do you think?

**Comment by MSilva95** [comment]
Will do that!
@jarmo-seljamaa Thanks for the feedback!
