### ISSUE TITLE
listclear subject

### ISSUE THREAD

**Issue by bomanviktor** [01-edu/public#1063]
listclear
---
suggested code to run the program does not work when you submit it:
states:
type List = piscine.List
type Node = piscine.NodeL

wants:
type (
	List = piscine.List
	Node = piscine.NodeL
)

**Comment by MSilva95** [comment]
Hello @bomanviktor !
Its working for me what is the Error that you get?

**Comment by MSilva95** [comment]
You can  reopen the issue if the problem continues in your side. 
At this time i didn't find any problem on my side

**Comment by bomanviktor** [comment]
I am unable to re-submit the code since the piscine is over. It was just a
minor error, but kinda annoying when it was like 22:00 and I wanted to go
home.

Thanks for responding!
