### ISSUE TITLE
Missing allowed packages in social-network

### ISSUE THREAD

**Issue by Olaroll** [01-edu/public#1065]
The social-network task seems to be missing 3 allowed Go packages that were allowed in the forum task. There's still a need for these packages, so I don't see why they were removed.

First of, there's no [driver package](https://github.com/mattn/go-sqlite3) for SQLite. Without this, it's impossible to create or connect to a SQLite database, which is what the task asks of us.

Then there's the [bcrypt](https://pkg.go.dev/golang.org/x/crypto/bcrypt) hashing package. Implementing our own password hashing from scratch seems way out of scope for this task.

And finally the [UUID](https://github.com/google/uuid) package. I'm pretty sure generating a truly random UUID is not a trivial task. We could also use incrementing IDs, but the forum task already taught us that it's better to use UUIDs, so why stop now?

https://github.com/01-edu/public/blob/a9e04d8e88f3ec40dc64b2d3755287514ac842a1/subjects/social-network/README.md?plain=1#L214-L220

**Comment by MSilva95** [comment]
Hello @Olaroll!
Yes it was a mistake on our part, thanks for the feedback i will add those packages.
