### ISSUE TITLE
go-reloaded audit issue

### ISSUE THREAD

**Issue by hhaakkimm** [01-edu/public#1071]
go-reloaded
---
I was assigned to audit my own project, however I didn't get 5 character confirmation code

<img width="1676" alt="Screen Shot 2022-05-04 at 16 18 24" src="https://user-images.githubusercontent.com/20023687/166663533-022d3f18-056f-4925-9366-4c72efacfd7f.png">

**Comment by MSilva95** [comment]
Hello @hhaakkimm!
This is not possible, you cannot audit your own projects, there must be another account with the same name as yours.

**Comment by MSilva95** [comment]
![tt](https://user-images.githubusercontent.com/53977751/166667522-50efad53-16c7-4cbe-9be9-0330610155e9.png)
There it is, you have two accounts with practically the same name

**Comment by hhaakkimm** [comment]
Can I possibly merge these two accounts, I do have the same two accounts one from the sandbox and the second one is imported from our school to the sandbox. I solved the question with my audit by sign-in from the admin panel, but for the future can admins reassign auditors?

**Comment by ZoeVig** [comment]
Hi @hhaakkimm! I will get back to you through Discord as this is not directly linked to the content team's work
