### ISSUE TITLE
cl-camp3 subject

### ISSUE THREAD

**Issue by Cenk313** [01-edu/public#1075]
cl-camp3
---

Instruction below specifically indicates to look for all files, thus solution should expect a `-type f` option to do so (to look for files and exclude directories;
`find . -type f \( -name "a*" -o -name "*z" -o -name "z*a!" \)`
But the solution above that looks for files only is getting denied.

The quest accepts the command below which finds both files and directories as a solution, even though instruction specifically asks for all files in almost every sentence.
`find . \( -name "a*" -o -name "*z" -o -name "z*a!" \)`

> Instructions
> "start looking ..."
> 
> Create a file look, which will look for and show, in the current directory and its sub-folders **all the files** :
> 
> starting with an a or,
> **all the files** ending with a z or,
> **all files** starting with z and ending with a!.

**Comment by MSilva95** [comment]
Hello @Cenk313 Thanks for the catch we will fix the problem.
