### ISSUE TITLE
Bug in go-test for quad

### ISSUE THREAD

**Issue by leviet0115** [01-edu/public#1082]
The audit test suite has a bug. The error messages are flipped. So, if my code returns “A” and the expected answer is “B”, the error message will be “test function prints B instead of A”. Probably the functions are passed in the wrong order to the testing function. 

```
quadA(0, 0) prints:
""
instead of:
"o\n"
exit status 1
```

**Comment by leviet0115** [comment]
Our mentor has improved it.

**Comment by MSilva95** [comment]
Thank you for the catch we will fix it as well!
