### ISSUE TITLE
[subject] Incorrect subject "inter" description

### ISSUE THREAD

**Issue by Dias1c** [01-edu/public#1087]
During the exam, I came across a subject in which the description of the subject does not match the example of the program.
Its about [inter subject](https://github.com/01-edu/public/tree/master/subjects/inter).

Look at the example of the program, and you can understand that the task is not formulated correctly.

Subject Instructions:
```
Write a program that takes two string and displays, without doubles,
the characters that appear in both string, in the order they appear in the first one.
```
But example of program:
```bash
# On example of usage #2:
$ go run . ddf6vewg64f  twthgdwthdwfteewhrtag6h4ffdhsd
df6ewg4
```

**Comment by MSilva95** [comment]
Hello @Dias1c!
I don't see any problem here, was is the confusion?

**Comment by Dias1c** [comment]
Hello @MSilva95! 
I highlighted the erroneous wording in bold text :)
## Task formulation
Write a program that takes two string and displays, without doubles,
the characters that appear in both string, **in the order they appear in the first one.**
