### ISSUE TITLE
boxing_todo subject

### ISSUE THREAD

**Issue by annalazarenkova** [01-edu/public#1108]
boxing_todo
---
In automatic tests "Fail to parse todo" is changes to "Fail to parse**_s_** todo" for some reason

**Comment by MSilva95** [comment]
Hello @annalazarenkova !
You need to explain issues more clearly. Try using print screens next time. 
For what i understand of what you said, a you're having trouble with the main testing function which had a small mistake and was fixed in the pr #1112.
