### ISSUE TITLE
make-your-game-history subject

### ISSUE THREAD

**Issue by rahelaas** [01-edu/public#1111]
make-your-game-history
---
![Screen Shot 2022-06-02 at 11 25 44 AM](https://user-images.githubusercontent.com/92050740/171587983-b83f5c49-0460-48be-8c06-fcde3a4581d8.png)
Hi! I've been trying to submit the make-your-game-history for audit but the submit button doesn't work and I keep getting these errors.

**Comment by MSilva95** [comment]
Hello @rahelaas!
We will take a look at this and we will get back to you.
Thank you for creating the issue
