### ISSUE TITLE
make-your-game-history subject

### ISSUE THREAD

**Issue by rahelaas** [01-edu/public#1114]
make-your-game-history
---
<img width="1336" alt="Screen Shot 2022-06-03 at 12 19 29 PM" src="https://user-images.githubusercontent.com/92050740/171827533-44566599-2fc4-4fc0-9056-865577aafc02.png">

Hi! I wrote yesterday that I had an issue with the submit button that didn't do anything. The issue was fixed but I am still not able to submit the code, now I get this error. If I click on the link "Repo to create for this project" it takes me to the uploaded files, the repo does exist. Not sure if this is something on my end or not. Thanks!

**Comment by MSilva95** [comment]
Hello @rahelaas We are taking a look at it at the moment, a fix will be done soon, thank you for reporting!

**Comment by MSilva95** [comment]
if you want to do the project you can create the repo with the name "history" instead of "make-your-own-game-history" for now this is how its working but soon we will fix this!
