### ISSUE TITLE
DEV-3891-front-back

### ISSUE THREAD

**Issue by Hamzaelkhatri** [01-edu/public#1121]
### instructions

- Write a program that prints the previous and next alphabet of a given alphabet.
    - if the number of arguments is different from `1`, print (`'\n'`).
    - if the length of the argument is different from `1`, print (`'\n'`)
    - if the argument is not a letter, print (`'\n'`)
    - print the previous alphabet and the next alphabet except for the last alphabet of the alphabet.

 ### Usage

```shell
$ go run  . | cat -e
$
$ go run . "a" | cat -e
ab$
$ go run . "B" | cat -e
ABC$
$ go run . "z" | cat -e
yz$
$ go run . B | cat -e
ABC
$ go run . "Hello World!" | cat -e
$
$ go run . "1" | cat -e
$
```

**Comment by davhojt** [comment]
Don't forget
```console
go run .
```

**Comment by davhojt** [comment]
Consider doing at least one of those suggestions without speech marks. For example:
```console 
go run . B | cat -e
```

**Comment by davidrobert99** [comment]
It is missing the PR for the go-tests repo.

**Comment by Hamzaelkhatri** [comment]
@davidrobert99 I add it

**Comment by Hamzaelkhatri** [comment]
https://github.com/01-edu/go-tests/pull/23
