### ISSUE TITLE
Buz-Zinga

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1122]
Write a function named `BuzZinga()` that takes a number as an argument and prints the following:
- if the number is divisible by `3`, print `Buz` followed by a newline.
- if the number is divisible by `5`, print `Zinga` followed by a newline.
- if the number is divisible by `3` and `5`, print `BuzZinga` followed by  a newline.
- if the number is not divisible by `3` nor `5`, print `*` followed by a newline.

```go
func BuzZinga(number int) {

}
```

**Comment by davhojt** [comment]
Ah, this is like one snapshot of fizzbuzz?

**Comment by zainabdnaya** [comment]
corrected
