### ISSUE TITLE
get-area

### ISSUE THREAD

**Issue by Hamzaelkhatri** [01-edu/public#1126]
### instruction 

- Write a program that takes a number and prints the area of the circle.
    - The area of the circle is `π` times the radius squared.
    - if the number is not positive or is not a number, print `Error` followed by (`'\n'`)
    - if the number is positive, print the area of the circle followed by (`'\n'`) 
    - if the number of arguments is not `1` print (`'\n'`)
    - You may assume that the value of pi is 3.14.
 
###  examples

```console
$ go run . | cat -e
$
$ go run . 10 | cat -e
315$
$ go run . 4 | cat -e
50$
$ go run . -10 | cat -e
Error$
$ go run . "Hello World!" | cat -e
Error$
```

**Comment by davhojt** [comment]
Here, we're not testing the student's mathematics ability, we're testing their ability to program. So we'll need to include a fixed value for pi. Something like
> You may assume that the value of pi is 3.14.
