### ISSUE TITLE
Binary- Addition

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1129]
Write a function that takes two integers as arguments:

a: the first integer number
b: the second integer number
and returns the sum of the two integers in Binary.
If the sum is negative return an empty string.

```go
func AddBinary(a int , b int)string {
        ...
    }
```

**Comment by Alcadeus0** [comment]
Hi, id like to work on this issue!

**Comment by davhojt** [comment]
"Binarry" is misspelled in the title.
