### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1137]
Write a function that takes two integers as arguments:
  - a: the first integer number 
   - b: the second integer number

it returns the sum of the two integers as integers.

If the number a or b is negative return 0.

```go
    func addIfPositive(a int, b int) int {
        ...
    }
```

**Comment by davhojt** [comment]
We'll have to check whether that function name is available. Perhaps you could obscure it now, by calling is something like `addIfPositive` or something like that.
