### ISSUE TITLE
swap-name

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1138]
Write a function that takes one argument including a first name + space + last name and returns a string in which the first name is swapped with the last name.
  Only valid strings will be used.

```go
$ go run . "zainab dnaya"
$ dnaya zainab
```

**Comment by davhojt** [comment]
@zainabdnaya  You could propose two versions of this. Easy and not very easy.

Easy version (this one) should say something additional like
> Only valid strings will be used.

Perhaps you could also propose a swap-name-mega or something, which adds error handling. If the sting is not valid, return error or something like that.

**Comment by zainabdnaya** [comment]
I do agree with you  , I will Work on it us soon as possible .
