### ISSUE TITLE
ping-pong

### ISSUE THREAD

**Issue by Hamzaelkhatri** [01-edu/public#1140]
### instructions

- write a program that checks if a number from `0` to `99` is an odd or even number 
   - if the number is `even` then it prints `ping` followed by (`'\n'`)
   - if the number is `odd` then it prints `pong` followed by a new line (`'\n'`)

### Usage

```console
$ go run . | cat -e
0 ping$
1 pong$
2 ping$
3 pong$
4 ping$
5 pong$
6 ping$
7 pong$
8 ping$
9 pong$
.
.
.
99 pong
```

Add a restriction in the refs to limit the number of invocations of `z01.PrintRune`.

**Comment by davhojt** [comment]
This can be hard coded. Let's make this one slightly more interesting.

How about it accepts a positive number between 0 and 99, and prints those lines. Just so there is some logic expressed.

For example
```js
console.log("0 ping\n1 pong\n2 ping\n...");
```

**Comment by Hamzaelkhatri** [comment]
@davhojt I guess if we limit the number of using for example `z01.PrintRune`, it can't be hard coded

**Comment by davhojt** [comment]
Fair point @Hamzaelkhatri.
Don't write tests for that, write it in the description (so that we add it in the configuration for the exercise).
