### ISSUE TITLE
Divisors

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1143]
- Write a function that takes a positive integer and returns the number of its divisors.
    - If the number a is negative return 0
```go
    func Divisors(n int) int {        
        ...
    }
```

```go
    package main
    import (
        "github.com/01-edu/z01"
    )
    func main() {
	    fmt.Println(Divisors(4))
	    fmt.Println(Divisors(5))
    }
```
And its output :
```go
    $ go run .
    3
    2


why?
4 can be divided by 1 and 2 and 4
5 can be divided by 1 and 5
```

**Comment by davhojt** [comment]
Please test to make sure that vey large numbers don't take a very long time.

**Comment by zainabdnaya** [comment]
I test INT_MAX AND it took 18.527430748 seconds
