### ISSUE TITLE
is sume of Even

### ISSUE THREAD

**Issue by mohamedLazyBob** [01-edu/public#1152]
# isSumOfEven 
a function that takes a number and returns `yes` if it's a sum of two even numbers and `no` if it's not
```
isSumOfEven(8) -> `yes` (4&4, 2&6..)
isSumOfEven(7) -> `no` (3&4..)
```

PS: this is just isEven with a tweak!

**Comment by davhojt** [comment]
How does this work?
8 can be 5+3 which are odd. Would 8 still be `yes`?

**Comment by davhojt** [comment]
Unclear exercise.
