### ISSUE TITLE
word Abbreviate

### ISSUE THREAD

**Issue by mohamedLazyBob** [01-edu/public#1153]
# wordAbbreviate 
a function that takes a string, and returns the same string if its length <= 9 
or a new string of length 9, that contains `...` in the middle and padded by the 3 chars of the original string from both sides
```
("hello!") => "hello!"
("hello world!") => "hel...ld!"
```

**Comment by davhojt** [comment]
Very nice 👍🏾

**Comment by eslopfer** [comment]
I am closing this since it was moved to jira.
