### ISSUE TITLE
isTheSquareAChild

### ISSUE THREAD

**Issue by mohamedLazyBob** [01-edu/public#1154]
# isTheSquareAChild 
a function that takes two numbers, the length of the square side.
and checks if one can be created from multiple squares of the other 
```
(4, 8) => true
(9, 3) => true
(2, 5) => false
```

**Comment by davhojt** [comment]
Will this be that **any** one can fit inside the other?
Or that the first one can fit inside the second one (or vice-versa)?

**Comment by mohamedLazyBob** [comment]
the way I thought about it, is to check if any square can be fit into the other, which is the second option you mentioned. but after thinking about it this will increase the difficulty of the exercise, so maybe it should be only if the first argument can fit into the second?
