### ISSUE TITLE
isSmoothDivisor

### ISSUE THREAD

**Issue by mohamedLazyBob** [01-edu/public#1163]
# isSmoothDivisor 
The positive integer m is called a smooth divisor of n if the quotient and remainder of dividing n by m are equal. 
given the positive integers n, and m. Find out if m is a smooth divisor of n.

```go
func isSmoothDivisor (m, n int) bool {

}
```

**Comment by davhojt** [comment]
@mohamedLazyBob Do you mean if you do 35 / 6
Then the answer is 5, with 5 remaining?
