### ISSUE TITLE
Swap-name-mega

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1166]
- Write a function that takes one argument and verifies this specification:
    - The `First name(string)` and `Last name(string) `must be separated by a space.
    - The First name and Last name must be Alphabetical.
    - No number, no special characters are allowed except space between First name and Last name.
    - If any rule is not verified return`wrong format`.
    - The First Character should be UpperCase and the rest in lowercase
- After you verify the format return a string in which the First name is swapped with the Last name separated with space.
    - In whatever case returns include newline `'\n'`

**Comment by davhojt** [comment]
@zainabdnaya What is this for?
> The First name and Last name must be in the same case.
If this is already true:
> The first characters of each First name and Last name must be capitalized.


Perhaps we could make it that
First char is upper, rest of the letters in each part of the name are lower?

**Comment by davhojt** [comment]
Unclear exercise.
