### ISSUE TITLE
Vowls-Index

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1167]
# instruction 

- Write a function that takes one argument of type string and returns an array of integers containing the index of the vowels in the string. [a,i ,e ,u o]

```go 
func VowelIdx(str string) []int {
}

VowellIdx("hello Iyan") // => [1, 4, 6, 8]
```

**Comment by davhojt** [comment]
I removed the console code-block as it's a function.

Please make sure to specify the vowels that will be used. It appears that we consider "y" to be a vowel here.

**Comment by davidrobert99** [comment]
@zainabdnaya The link for the PR on the go-tests is missing, can you please check that?
