### ISSUE TITLE
 red-black-tree validation

### ISSUE THREAD

**Issue by Hamzaelkhatri** [01-edu/public#1169]
### Instruction
- Write a function that checks if the `list` passed in the parameter is a valid red-black-tree or not :
    - If the list is a valid red-black-tree, return `true`
    - If the list is not a valid red-black-tree, return `false`
    - A valid red-black-tree is a binary tree where each node is either red or black
    - The root of the tree is always black.
    - The number of black nodes on the left side of the root is equal to the number of black nodes on the right side of the root

### Expected function
```go
func isValidRedBlackTree(list interface{}) bool {
    // Write your code here
}
```

**Comment by davhojt** [comment]
Too hard for easy exercises.
