### ISSUE TITLE
go-reloaded subject

### ISSUE THREAD

**Issue by Nitroshield** [01-edu/public#1178]
go-reloaded
---
Dans l'audit "go-reloaded" lors de la dernière question demandant de copier le texte : 
`harold wilson (cap, 2) : ‘ I am an optimist, but an optimist who carries a raincoat. ’`

Les apostrophes utilisées sont courbées alors que celles données dans l'énoncé sont neutres/ambigües.
Ces deux apostrophe étant considérées comme deux caractères différents pour l'ordinateur, lorsqu'il cherche l'un, il ne peut trouver l'autre

**Comment by davhojt** [comment]
Hello @Nitroshield. Are you referring to this:
https://github.com/01-edu/public/blob/3726c9a3b00f50b52919904946da7c309dfe8ac0/subjects/go-reloaded/audit/README.md?plain=1#L17

It appears to have the correct single quote. Is it possible that it was copied from somewhere like Microsoft Word or similar which normally change quotes into speech marks?

For now I will close this issue as it seems to be correct. But you are welcome to reopen it or submit a new issue if I am mistaken.
