### ISSUE TITLE
Rust picine Exam: macro_calulator

### ISSUE THREAD

**Issue by Whovillage** [01-edu/public#1188]
The exam task requires the json crate, but it is not possible to use it in the exam environment, so it is impossible to solve the exercise the way it is asked to be solved.

**Comment by davhojt** [comment]
That is a very good point.

I will ensure that it is not part of any subsequent exams.

Thank you for your feedback.

**Comment by davhojt** [comment]
Removed from exams. Thank you @Whovillage.
