### ISSUE TITLE
lunch_queue subject

### ISSUE THREAD

**Issue by mihkelgering** [01-edu/public#1192]
lunch_queue
---
Expected structure is causing confusion:

```
pub struct Person {
    pub id: i32,
    pub name: String,
}

```

Tests and even example below are pointing to Person which has name and discount.

Please change expected structure to correct one:
```
pub struct Person {
    pub discount: i32,
    pub name: String,
}
```

**Comment by davhojt** [comment]
Thank you @mihkelgering. We have made the fix that you identified.

Very grateful 🙂.
