### ISSUE TITLE
[DESIGN] Add a security on Nuclear button

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#121]
Add a security if a user double clicks on the button by mistake (could be a setTimeout).

**Comment by bde-maze** [comment]
What is the nuclear button 🤔

**Comment by MarieMalarme** [comment]
A new fresh feature ! You can check it in the admin now, just has been merged on master (delete an object or an attribute or a children)

<img width="1552" alt="Screenshot 2019-05-14 at 12 20 54" src="https://user-images.githubusercontent.com/4631239/57694198-00cf9000-7643-11e9-9336-36bba52b69ab.png">
<img width="1552" alt="Screenshot 2019-05-14 at 12 21 12" src="https://user-images.githubusercontent.com/4631239/57694204-04631700-7643-11e9-8a75-32cf4f626584.png">
<img width="1552" alt="Screenshot 2019-05-14 at 12 21 02" src="https://user-images.githubusercontent.com/4631239/57694212-075e0780-7643-11e9-8414-a4e21241999a.png">
