### ISSUE TITLE
[DATEFORMAT] Change dateformat to dd/mm/yyyy

### ISSUE THREAD

**Issue by atlekbai** [01-edu/public#123]
**Is your feature request related to a problem? Please describe.**
People confuse when filling date input of type mm/dd/yyyy.

**Describe the solution you'd like**
To change to type: dd/mm/yyyy

**Priority**
normal

**Subject**
onboarding

**Comment by sakenism** [comment]
People in KZ are more used to dd/mm/yyyy

**Comment by lfoussat** [comment]
hey! I've looked MDN documentation and it seems that the format of the date displayed in the input type date depends on the langage used by your browser. I don't think I can force anything about that but I'll keep looking

**Comment by sakenism** [comment]
Oh, right... We had English system, so that was confusing. Thanks a lot
