### ISSUE TITLE
printcomb2 subject

### ISSUE THREAD

**Issue by chickazama** [01-edu/public#1233]
printcomb2
---

Hi, I feel like the format checks on the Go programs are a bit overzealous...most of the tasks I understand the logic and solve the programs, but then spend ages combing through the source code because my 'Go files are not formatted correctly'. This is even after having run 'gofmt -w <file>', and the programs run just fine on my local machine. Often, the 'format error' is actually that I've given myself a bit of space within a code block.

**Comment by davhojt** [comment]
@chickazama I will close this issue for now. Please feel welcome to reply or open a new issue if necessary.

**Comment by chickazama** [comment]
Thanks! No other issues, sorry for only responding to this now - it took me a while to get to grips with the extreme level of formatting enforced (i.e. no empty lines which I was adding for readability), thanks for your help!
