### ISSUE TITLE
oddlength

### ISSUE THREAD

**Issue by eslopfer** [01-edu/public#1274]
Write a function that receives a slice of strings and returns a new slice with the strings in which the length is odd.

```go
["Hi", "Hola", "Ola", "Ciao", "Salut", "Hallo"] => ["Ola", "Salut", "Hallo"]
```

**Comment by davhojt** [comment]
@eslopfer Please also propose an even length version of this function.

**Comment by eslopfer** [comment]
Thank you. Done.
