### ISSUE TITLE
printstr subject

### ISSUE THREAD

**Issue by CIRCADES** [01-edu/public#1304]
printstr
---

The hint suggests output:

$ go run . | cat -e
Hello World!%
$

The "%" is probably a mistake. Also, the Test Panel expects no new line.

**Comment by davhojt** [comment]
Hello @CIRCADES.

The `%` is normally used to represent that there is no new line at the end. This is however not consistent across different shells.

Some shells place the prompt directly after the output. But as `cat -e` used `$` to represent the end of the line, and the prompt is also represented by a `$`, it gets a bit confusing to use it.

https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol

ohmyzsh:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/22807573/176935398-876813e6-8070-4011-83fe-7a7ee08cce2c.png">

bash:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/22807573/176935700-9480e03d-769c-4168-8d6c-39efc4592140.png">

csh:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/22807573/176935994-5c6e712a-03ad-4cd9-b088-3a461649d9f5.png">
