### ISSUE TITLE
social-network subject

### ISSUE THREAD

**Issue by KRakenoZavr** [01-edu/public#1306]
Can we make the backend also on js?

There are not much difference in backend in subjects
1. forum - we've learned a lot about backend and working with db
2. real-time-forum - the only new thing is websocket
3. social-network - only migration

so maybe we will learn some fully new backend technology(nodejs) in js branch and not only front work

**Comment by MSilva95** [comment]
You must respect the allowed packages for that project, the rest is up to you to decide.
Make sure that you respect every question on the audit and it should be fine. But the purpose is to explore the Go language
