### ISSUE TITLE
findnextprime subject

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1309]
findnextprime
---
hum considering this :
- "findnextprime.go"
and
- "Write a function that returns the first prime number that is _equal or superior_ to the int passed as parameter"

we really to be clear on what next "means" or we acknowledge that functions name can simply be wrong (real life case ?).
because saying that next prime number after 2 is 2 ... 
don't let any math teacher hear that or they will attack you.

**Comment by MSilva95** [comment]
Yes @fulverin you are right the name of the function is not the best, but I think it will not be a problem, we explained the exercise and I don't think it will create confusion because of the name of the function.
Thanks for the feedback anyway!
