### ISSUE TITLE
nrune subject

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1310]
nrune
---
hi,
feel like lest part of instruction is unfortunate copy paste from previous exercise : 

"
Instructions

Write a function that returns the nth rune of a string. _**If not possible, it returns 0.**_
"

then example and test suggest it should be null or nothing (not sure) instead : 
output from test
NRune("Not", 6) == '0' instead of '\x00'
exit status 1

and below the expected detailed output :
func main() {
	z01.PrintRune(piscine.NRune("Hello!", 3))
	z01.PrintRune(piscine.NRune("Salut!", 2))
	z01.PrintRune(piscine.NRune("Bye!", -1))
	z01.PrintRune(piscine.NRune("Bye!", 5))
	z01.PrintRune(piscine.NRune("Ola!", 4))
	z01.PrintRune('\n')
}

And its output :

$ go run .
la!
$
"

**Comment by MSilva95** [comment]
Your program should not (PRINT 0), it should (RETURN 0) it is different, at the moment your program prints "la00!" for the example given!
