### ISSUE TITLE
map subject

### ISSUE THREAD

**Issue by hannaevg** [01-edu/public#1322]
map
---
The possible program to test the function "map.go" referes to an optional task in quest 4, which I didn't do. Because it was an optional task. So now I have big problems with solving a required task. This is very unfair and unpleasant.

**Comment by davhojt** [comment]
It is not explicitly necessary to use `piscine.IsPrime`. `Map` expects a function with the signature `func(int) bool`.

**Comment by hannaevg** [comment]
I know it but this doesn't make the task simpler for beginners.
