### ISSUE TITLE
listlast subject

### ISSUE THREAD

**Issue by G-ameline** [01-edu/public#1324]
listlast
---
Hi, may be I am wrong , but unless there is a convention when it comes to list of nodes that define "element" by what we called data in the exercise (and what I would call content of the node)
the instruction say we should return the last element of the list (what I understand as the node itself) and the example suggest we are should return the data of that last element.
thanks

**Comment by eslopfer** [comment]
Hi @fulverin  Thank you for your feedback.
You may see the updated document here which will be implemented shortly: https://github.com/01-edu/public/pull/1327/files
