### ISSUE TITLE
listat subject

### ISSUE THREAD

**Issue by G-ameline** [01-edu/public#1325]
listat
---
instruction say "l" as *list type input (make sense) whereas the expected structure say "l" is a *NodL type (weird)

instruction :
"Write a function ListAt that takes a pointer to the list l"

expected function :
func ListAt(l *NodeL, pos int) *NodeL{
}

edit :
how and yes the test actually ask for a node and input a list_of_nodes.Head as an input so I guess the instruction is faulty, should be something head_of _ist *NodeL imho. 
Unless, indeed,  there is a strong convention that state that we can reduce the list to its head [ we are newbes here so please share some hint )

**Comment by eslopfer** [comment]
Hi @fulverin  Thank you for your feedback.
You may see the updated document here which will be implemented shortly: https://github.com/01-edu/public/pull/1328/files
