### ISSUE TITLE
sortlistinsert subject

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1331]
sortlistinsert
---
hi, same here, big  ambiguities on the what the function do and what/how we call list, node, data.
I don't know where to start

instruction :
Write a function SortListInsert that inserts data_ref in the linked list l
_want(list,data) return (nothing)_

expected function
func SortListInsert(l *NodeI, data_ref int) *NodeI{
_want (node,data) return (node)_

suggested test :
link = piscine.SortListInsert(link, -2)
link = piscine.SortListInsert(link, 2)
_want(list,data) return(list)_

this time I cannot guess what is the right one.

so if  am picky and get the node list thing right we do not insert data in list , we write data in a node that we insert in a list of nodes accessed/referenced by a list. 

well is sounds also we jumped from a struct called NodeL ("L") to NodeI ("i")  midway in the quest.

Regards

Guillaume

**Comment by davhojt** [comment]
Hey @fulverin. Thank you for your feedback.

A linked list is some reference to a struct, which has pointer(s) to other structs which make up the list. So there isn't a fundamental difference with the first parameter in each of your pseudo-code examples. Same goes for the return type on the last two pseudo-code examples.

It is valid that the instruction does not say to return something, but the function signature is unambiguous that a pointer to some `NodeI` should be returned. The specific node which is pointed to by the return address can be determined from the usage. We may make the instructions clearer following your feedback.

`NodeL` and `NodeI` are not the same struct, so the change of name is necessary.
