### ISSUE TITLE
ascii-art-justify subject

### ISSUE THREAD

**Issue by yernur16** [01-edu/public#1333]
ascii-art-justify
---
Hello
Should the code be failed or passed, if the length of text goes out of range and not start from new line. Or is it okay to handle it like this "too long text"? Because I(as an auditor) can rearrange the terminal size and make it small, so text from audit will not show up, as an output.

![Screenshot from 2022-07-18 12-23-47](https://user-images.githubusercontent.com/46591418/179460637-e9b48d08-5c8d-4995-bda2-ef61d7700c13.png)

**Comment by davhojt** [comment]
Thanks for your question @yernur16.

The following line was added: https://github.com/01-edu/public/blob/c2ba93a8b48df5eca96ce136405dcecae4ce07d1/subjects/ascii-art/justify/README.md?plain=1#L21
