### ISSUE TITLE
to-git-or-not-to-git tests

### ISSUE THREAD

**Issue by rcatini** [01-edu/public#1335]
to-git-or-not-to-git
---

In the test script (to-git-or-not-to-git_test.sh) the variables are not defined.
As a consequence the test appears to succeed with any script that can be run (even with an obviously wrong output).

The commit that deleted the variable definitions: e221c91bd37a3499466a4aa55d9904c37bf02c08

This is the error message that is produced on succeeding:
```
to-git-or-not-to-git_test.sh: line 11: submitted: unbound variable
to-git-or-not-to-git_test.sh: line 11: expected: unbound variable
```

**Comment by davhojt** [comment]
Thank you @rcatini. We'll get that looked at shortly and provide you a response.
