### ISSUE TITLE
teacher subject

### ISSUE THREAD

**Issue by rcatini** [01-edu/public#1336]
teacher
---
Le sujet teacher spécifie : `(those folders will not be called mystery, they will have different names but they will all be at the same level)`
Mais le code que doit etre rendu sera exécuté directement dans les dossiers, et n'a pas besoin de savoir les noms des dossiers mystery, ni leur niveau (ce qui etait le cas avant la simplification du test opérée par 97dcdafc99a7902ecc4fb4bf1e5977e3aef6e025)
Le résultat est que cette information sur les noms des dossiers devient inutile, voire trompeuse.
Une solution sera simplement d'éliminer cette information dans le parenthèses.

**Comment by davhojt** [comment]
Thank you @rcatini. We'll provide you a response shortly 👍🏾.
