### ISSUE TITLE
go-reloaded - uncertainty in the task constraints

### ISSUE THREAD

**Issue by Dias1c** [01-edu/public#1339]
Students (auditors) encounter contradictions in these constraints. 
- Group 1 believes that only functions implemented from the old repository can be used ([Link](https://github.com/01-edu/public/blob/61e9bcda0fc1bdbba7d1308efc00f1c43c5294bc/subjects/go-reloaded/README.md?plain=1#L7)).
```md
In this project you will use some of your old functions made in your old repository. You will use them with the objective of making a simple text completion/editing/auto-correction tool.
```

- Group 2 believes that they can only pass the project using standard packages ([Link](https://github.com/01-edu/public/blob/61e9bcda0fc1bdbba7d1308efc00f1c43c5294bc/subjects/go-reloaded/README.md?plain=1#L37)).
```md
- Only the [standard Go](https://golang.org/pkg/) packages are allowed
```

Is it possible to remove the ambiguities and describe the project in more detail.

**Comment by MSilva95** [comment]
Thanks for the feedback!
The thing is that you can use both, the standard go packs and the functions you created before, but just to make things a bit clear i will remove the "only" from the second sentence.
