### ISSUE TITLE
contradiction in the instruction

### ISSUE THREAD

**Issue by ive663** [01-edu/public#1341]
it says that
"You **must** follow the same [instructions](../README.md) as in the first subject..."
also in the last statement it says
"The usage **must** respect this format `go run . [STRING] [BANNER]`, any other formats must return the following..."
so the question is if i enter 'go run . "some text" | cat -e' what should i get in return....? 
should it work as base ascii-art program or should it return error?

https://github.com/01-edu/public/blob/61e9bcda0fc1bdbba7d1308efc00f1c43c5294bc/subjects/ascii-art/fs/README.md?plain=1#L5-L13

**Comment by MSilva95** [comment]
Hello @ive663!
I can not see contradictions here, but i understand what is your confusion.
The usage is just `go run . [STRING] [BANNER]` after that, the piping is an extension of the usage, using the flag cat -e will not affect the program output in any way.
With that being said, you program should print the output just like in the audits.
Thanks for the feedback!

**Comment by ive663** [comment]
hello @MSilva95 
I was pointing to " go run . [string]"  without [banner] .... 
if no banner used how should it work?

**Comment by MSilva95** [comment]
It should work like the base program, it will return the Art string in the standard banner

**Comment by ive663** [comment]
thanks...

**Comment by arturzhamaliyev** [comment]
> It should work like the base program, it will return the Art string in the standard banner

hi, there. may you update audit tests pls: first test asks if you pass one argument `go run . "banana"`, does it print usage message, not art. thx in advance.
![Screenshot from 2022-07-26 07-12-44](https://user-images.githubusercontent.com/105099285/180901263-4e5dabe9-1749-4037-9206-df83c5eea082.png)
