### ISSUE TITLE
cl-camp1 subject (sort by creation time)

### ISSUE THREAD

**Issue by rcatini** [01-edu/public#1345]
cl-camp1
---

The subject asks to sort the files by the **file creation** time. On GNU coreutils 8.32 (the only one I've tested), the two equivalent options `--time=creation` and `--time=birth` are supported.

When submitting the exercise with the above option (at kood/johvi, july 2022), this is the result of the test (that is running on GNU coreutils 8.30 on the tmpfs filesystem):

```
ls: invalid argument 'creation' for '--time'
Valid arguments are:
  - 'atime', 'access', 'use'
  - 'ctime', 'status'
Try 'ls --help' for more information.
```

The option does not seem supported by the testing system, even if the point of the exercise is reading the manual of `ls` (and the `--time=creation` is the only reasonable solution, according to the manual of the latest GNU coreutils).

At 42 Paris on macOS and HFS+, a trick that would have worked would have been to use option `-U` (directory order). Unfortunately this old trick does not work on file systems where the directory order is not chronological (ex: on binary tree file systems).

The test https://github.com/01-edu/public/blob/61e9bcda0fc1bdbba7d1308efc00f1c43c5294bc/sh/tests/solutions/mastertheLS#L3 uses the default behavior of `ls` (`ctime`) which is the time of the latest change, and not the creation time.

All in all, the easiest solution would be to change the request of the subject to `atime` (since `atime` seems to be a universally supported attribute). A switch to `ctime` might be possible too, but it would reduce the level of complexity of the exercise (since it's the default option for sorting).

**Comment by davhojt** [comment]
Cheers @rcatini. We'll get this looked into.
