### ISSUE TITLE
Netfix Deprecated Features

### ISSUE THREAD

**Issue by nater6** [01-edu/public#1346]
netfix
---
When using the netfix files provided there are deprecated features when used with Django 4.0. For example "from django.conf.urls import" which is causing a problem when trying to run the migrations with python manage.py migrate.

**Comment by davhojt** [comment]
Thanks @nater6. We'll get that looked at.

**Comment by MSilva95** [comment]
Hello @nater6!
This project works only up to the version `Django v3.1.14` so we will add a note on the readme that you need that version in order to complete the project.
Thank you for your feedback!
