### ISSUE TITLE
introduction subject

### ISSUE THREAD

**Issue by Cleveraccountant96** [01-edu/public#1382]
introduction
---
tudent@ubuntu:~/piscine-go$ git add hello.sh
student@ubuntu:~/piscine-go$ git commit -m "My very first commit"
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
student@ubuntu:~/piscine-go$ git push
To https://learn.01founders.co/git/mshoaib/piscine-go.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://learn.01founders.co/git/mshoaib/piscine-go.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
student@ubuntu:~/piscine-go$ git clone https://learn.01founders.co/git/musab/piscine-go.git
Cloning into 'piscine-go'...
fatal: repository 'https://learn.01founders.co/git/musab/piscine-go.git/' not found
student@ubuntu:~/piscine-go$ git clone https://learn.01founders.co/git/mshoaib/piscine-go.git
Cloning into 'piscine-go'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
student@ubuntu:~/piscine-go$ $ bash hello.sh
Hello Musab!
$
$: command not found
Command 'Hello' not found, did you mean:
  command 'hello' from deb hello (2.10-2ubuntu2)
  command 'hello' from deb hello-traditional (2.10-5)
Try: sudo apt install <deb name>
$: command not found
student@ubuntu:~/piscine-go$ git add hello.sh
student@ubuntu:~/piscine-go$ git commit -m "My very first commit"
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        piscine-go/

nothing added to commit but untracked files present (use "git add" to track)
student@ubuntu:~/piscine-go$ git push
To https://learn.01founders.co/git/mshoaib/piscine-go.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://learn.01founders.co/git/mshoaib/piscine-go.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
student@ubuntu:~/piscine-go$ hello.sh
hello.sh: command not found
student@ubuntu:~/piscine-go$

**Comment by davhojt** [comment]
Hello @Cleveraccountant96.
Could you provide a brief summary of the problem you encountered?

**Comment by Cleveraccountant96** [comment]
I am trying to submit my "test introduction" task, so just asking if there
are any limits to the attempts I make submitting my tasks.

Thank you
Regards

SH Musab

**Comment by davhojt** [comment]
There isn't a limit to the number of submissions. There is a time scope for submission. Outside of the time-scope, you will potentially not earn XP for submission.
Don't forget to ask your fellow students for help.
Good luck @Cleveraccountant96

**Comment by Cleveraccountant96** [comment]
Thank you for the clarification.
SH Musab

**Comment by Cleveraccountant96** [comment]
Thanks a lot.
That Great.

SH Musab
