### ISSUE TITLE
bomberman-dom subject

### ISSUE THREAD

**Issue by mihkelgering** [01-edu/public#1391]
Main task description requires for 3 different types of powerups. 
![image](https://user-images.githubusercontent.com/33875822/184540514-a2c61297-af2c-4aef-800b-6da44ce5e4d8.png)

Audit is checking for 4 different types of powerups.
```
Try to destroy every block on the map.
Did the power ups appeared in the places of the blocks?
Can you confirm that there is 4 different types of power ups?
```
This point is missleading from the main task description, because adding more extra powerups is a bonus part.

**Proposal:**

Change this
```
Can you confirm that there is 4 different types of power ups?
```
To this:
```
Can you confirm that there is 3 different types of power ups?
```

**Comment by davhojt** [comment]
Thank you for your feedback @mihkelgering. It was resolved by a proposed PR by @AaEnnDeeErrEeEss.
