### ISSUE TITLE
printnbrbase subject

### ISSUE THREAD

**Issue by Markovk1n** [01-edu/public#1394]
printnbrbase
---

Hello, I have a problem with the "run print base test" button.

1) I started searching for a match
2) found a match and chose a bet
3) I chose that the code will not work and the opponent too
4) my code did not work and after that the button became gray

button does not respond to pressing
![my_fov](https://user-images.githubusercontent.com/110080304/184878896-4f51189f-99ef-46b8-bbeb-cf46e72d8779.png)
2 screen from opponent
![2 person](https://user-images.githubusercontent.com/110080304/184878890-b37f3e87-21fe-4fe1-bc31-ad842677acfc.png)

**Comment by ZoeVig** [comment]
Hi @Markovk1n, thank you for reporting this, much appreciated.
I'll register it as a bug so that it is looked into by the dev team @kigiri .
I'll close this ticket as this information will be moved elsewhere.
Cheers,
Zoe
