### ISSUE TITLE
looping subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1398]
looping
---
The example does not reflect the expected output (Example: "Number of trials", Expected output: "It took you N trials to get the right answer").
![image](https://user-images.githubusercontent.com/80747520/185904783-d3a377af-2539-49f2-99d2-5a5f21b78849.png)

**Comment by davhojt** [comment]
Thank you for your report @jarmo-seljamaa.

We have fixed an error which caused student's code to be tested against outdated versions of tests.
