### ISSUE TITLE
sortedlistmerge subject

### ISSUE THREAD

**Issue by Adil-9** [01-edu/public#1399]
wrong testcase input
data set:[[3 5 7] [1 -2 4 6]]
student list:0-> 3-> 5-> 7-> <nil>
list:-2-> 0-> 0-> 1-> 3-> 4-> 5-> 6-> 7-> <nil>

SortListInsert() == 0 instead of -2

exit status 1
second data set not sorted

**Comment by eslopfer** [comment]
Thanks for your feedback @Adil-9 this issue was resolved in the pull request to the right of this message.
