### ISSUE TITLE
shopping_mall subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1413]
shopping_mall
---
The task instruction asks for `highest_paid_employees`, `fire_old_guards` and `check_for_guards` functions:
![image](https://user-images.githubusercontent.com/80747520/188077561-46b2364c-3400-48d3-99be-e62ece7c33f2.png)

However, the tests require `highest_paid_employee`, `fire_old_securities` and `check_for_securities` functions instead.

**Comment by davhojt** [comment]
Thanks @jarmo-seljamaa. We'll get that fixed.

**Comment by mikysett** [comment]
Thanks a lot for the feedback, we fixed the issue
