### ISSUE TITLE
go-reloaded - Wrong single quotation mark in audit questions

### ISSUE THREAD

**Issue by gritlab** [01-edu/public#1414]
- In the project description, students are asked to use this `'`quotation mark. 
<img width="753" alt="Screen Shot 2022-09-02 at 15 21 30" src="https://user-images.githubusercontent.com/109672158/188141721-59ef3299-06d4-474f-a4cc-c8a09442925e.png">

- But in the audit, the auditor is asked to test the code with this `‘` quotation mark.  
![image](https://user-images.githubusercontent.com/109672158/188141805-001c461f-0786-4394-afb8-5d9003b208fb.png)

- This inconsistency made many students fail the audit as the auditors are instructed to use syntax from the questions. 

- I have checked the source file of the audit questions. It's the `'` mark in the source, but the display is incorrect on the UI. I believe the root cause is the font.

**Comment by davhojt** [comment]
Thanks @gritlab.
We'll look into that fro you.

**Comment by davhojt** [comment]
@gritlab Thanks for reporting the issue.
We need to make some improvements with how some of the markdown renders. In the meantime, we've moved the content around to mitigate for that.

**Comment by davhojt** [comment]
Resolved by #1423
