### ISSUE TITLE
box_it subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1415]
box_it
---
The instructions are a bit confusing in regards of there reference to `kilograms`.

Instead of 

> `transform_and_save_on_heap`: which accepts a string of **numbers** separated by spaces. Each number may or may not have a 'k' as a suffix which represents **kilograms**.

it should say either

`transform_and_save_on_heap`: which accepts a string of **gram values** separated by spaces. Each number may or may not have a 'k' as a suffix which represents kilograms.

or remove reference to kilograms altogether

`transform_and_save_on_heap`: which accepts a string of numbers separated by spaces. Each number may or may not have a 'k' as a suffix which represents **multiplication by one thousand**.

**Comment by mikysett** [comment]
Thanks for the feedback, the meaning of the `k` is now more clear and already in production
