### ISSUE TITLE
go-reloaded subject

### ISSUE THREAD

**Issue by sagarishere** [01-edu/public#1418]
go-reloaded
---
$ cat sample.txt
Punctuation tests are ... kinda boring ,don't you think !?

$ go run . sample.txt result.txt

$cat result.txt
Punctuation tests are... kinda boring, don't you think!?
ISSUE 1: => In this last test case, the new line magically disappears whereas in the other cases it does not. No such rule is whereas defined. 

This should be addressed.

Plus, it is clearly mentioned that <Best Practices> "must" be followed but no tests are written to check for the best practices, then it is renegaded to "should" rather than "must", as there are no tests included for it, nor is any audit question about it.

**Comment by MSilva95** [comment]
Hello @sagarishere!
You're talking about the usage part right?

**Comment by sagarishere** [comment]
Hi, let me try to explain it in a different way.

The description of tasks is not clear. At some places the cat command should generate multiple lines, at some point not, which means at random the new line should be introduced in the result.txt files, regardless of whether the new line was present in sample.txt or not.

Here's another one: The description clearly says that the code **must** follow best practices.
However, there is no test run to check for best practices. 

I suggest that task descriptions be clear, and concise. And also that standard tests to check the 'best practices' like https://github.com/go-critic/go-critic be used in the server side before submitting for audit.

**Comment by davhojt** [comment]
"MUST" and "SHOULD" often follow the [RFC 2119 convention](https://www.ietf.org/rfc/rfc2119.txt) for documentation:
- MUST: mandatory
- SHOULD: recommended

Our subjects describe a technical task, but are not intended to take the form of technical documentation. That being said, there are very obvious opportunities to better distinct mandatory requirements from recommendations and optional items.
