### ISSUE TITLE
alphamirror - inconsistent newline requirement between example and test

### ISSUE THREAD

**Issue by gritlab** [01-edu/public#1429]
- **Case**: If there is no argument

- **Example**: Then print a new line
<img width="1116" alt="Screen Shot 2022-09-08 at 16 49 00" src="https://user-images.githubusercontent.com/109672158/189139519-c1775494-9d4d-4dfc-b217-aad328aad252.png">

- **Test**: Then print 2 new lines
![IMG_1304](https://user-images.githubusercontent.com/109672158/189140802-b9d6226f-115b-408e-b0dd-fcecbd9fdf18.JPG)

**Comment by eslopfer** [comment]
Hi @gritlab this issue was addressed in the attached pull request.
Thanks for your feedback!
