### ISSUE TITLE
union - inconsistent newline requirement between example and test 

### ISSUE THREAD

**Issue by gritlab** [01-edu/public#1433]
See screenshot for details 

**Case**: $ go run . zpadinton paqefwtdjetyiytjneytjoeyjnejeyj | cat -e
**Example**: zpadintoqefwjy$
**Test**: 
zpadintoqefwjy
$
![IMG_1306](https://user-images.githubusercontent.com/109672158/189599443-5b7bb23e-75e2-4585-9d16-95ae98262820.JPG)

**Comment by eslopfer** [comment]
Hi @gritlab this issue was addressed in the attached pull request.
Thanks for your feedback!
