### ISSUE TITLE
commits_stats subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1434]
commits_stats
---
Instructions:

> In this exercise, you will be provided with a json file `commits.json` with data corresponding to git commits in GitHub (extracted using the GitHub rest API). 

In reality we are not **provided** with the json file, but have to Google for the exact specs ourselves. With time being tight in the Piscine quests it would be fair to provide at least a link to to the spec (https://docs.github.com/en/rest/commits/commits), so we wouldn't have worry if we found the right specs until we push the first version of our code to server for testing. 

Thank you!

**Comment by mikysett** [comment]
I added a link to the file in the subject, thanks for pointing out it was missing.
