### ISSUE TITLE
[ascii-art-color] Empty question and malfunction bonus question

### ISSUE THREAD

**Issue by gritlab** [01-edu/public#1441]
During the audit, we found that: 

- The last question is empty.
- The last question belongs to the bonus section but failing that questions make the students fail the project.

**Comment by gritlab** [comment]
Hi @davhojt, we still encountered the malfunction issue in the audit of this project. Students still fail if they fail the last question, which is a bonus one. Could your team have a look at it again? Thanks.

**Comment by davhojt** [comment]
Hey @gritlab. Don't hesitate to reopen an issue if necessary.
Could you confirm that it looks good at your end now?

**Comment by davhojt** [comment]
Resolved here: https://github.com/01-edu/public/pull/1475
