### ISSUE TITLE
printstr subject

### ISSUE THREAD

**Issue by T4NKER** [01-edu/public#1452]
The output that's required presumes that coder adds z01.PrintRune(\n) after the for loop, but the code goes through only when it is ommited.
---

**Comment by davhojt** [comment]
Hi @T4NKER.

We have a known issue at the moment where both of the following are represented by `$`:
- The prompt
- The position of the new-line character when piped through `cat -e`.

So it it sometimes confusing to view code examples which include `cat -e`. We're working on a solution for this to make those console code-blocks more readable.

See: #1304
