### ISSUE TITLE
[roman numbers] Hard coding issues

### ISSUE THREAD

**Issue by gritlab** [01-edu/public#1453]
roman numbers
---
-During checkpoints and exams, we found that students can hardcode this task in 30 mins. 
-We suggest the test validating hardcoding in the submitted work.
-If hardcoding can't be prevented, we suggest replacing this exercise with another task in checkpoints/exams.

**Comment by eslopfer** [comment]
Hi @gritlab, thanks for your feedback.

The tests for this exercise are random, so it would be a situation of either wining the lottery or writing at least a couple thousands of different if statements to be able to hard-code the solutions to match the test cases if that is what you mean. 

Can you be a bit more specific about what do you mean by hard-coding it, so I can understand the problem better?

**Comment by gritlab** [comment]
Hi @eslopfer, our student hardcoded by writing all if-cases for numbers from 1 - 399 in 30 minutes.

**Comment by gritlab** [comment]
Hi @eslopfer, we will have another checkpoint in two days. Is there any update on this issue? 😃

**Comment by davhojt** [comment]
Hey @gritlab.

May I ask for an example of what the hard-coding looked like?

**Comment by gritlab** [comment]
Hi, it's something like: 

If (input = "123") 
    print C+X+X+I+I+I
    print CXXIII

And students managed to do this for all numbers from 1 - 399.

**Comment by davhojt** [comment]
Hey @gritlab.

It appears that our test cases range from 0-4000 (not to 399). It would seem like a reasonably big ask to hard-code 4000 cases under exam conditions.

We'll test what happens when hard-coding from 1-399, but in theory that should not pass our tests.

**Comment by davhojt** [comment]
Hey @gritlab.

We've reviewed the tests to make sure that we test cases between 0-4000, and consider it to be unlikely that students can hard-code that under exam conditions.
