### ISSUE TITLE
isprintable subject

### ISSUE THREAD

**Issue by olivierpolynice** [01-edu/public#1465]
isprintable
---
package piscine

func IsPrintable(s string) bool {
	for _, i := range s {
		if (rune(i) < 65 || rune(i) > 90) && (rune(i) < 97 || rune(i) > 122) && (rune(i) < 48 || rune(i) > 57) {
			return false
		}
	}
	return true
}

**Comment by davhojt** [comment]
Hi @olivierpolynice.
Could you describe the issue you have?

**Comment by davhojt** [comment]
@olivierpolynice Please reopen the issue if you have some feedback for us 👍🏾.
