### ISSUE TITLE
filler subject

### ISSUE THREAD

**Issue by Whovillage** [01-edu/public#1478]
filler
---
The game does not run on an M1 Mac with given instructions. 

`--platform=linux/amd64` has to be added to the docker build command to make it work.

**Comment by davhojt** [comment]
Thanks @Whovillage.
I'll get the maintainers to take a look at that for you.

**Comment by mikysett** [comment]
Hello Whovillage, thanks a lot for reporting the issue and also for the proposed solution, which works as a breeze.
We've updated the `README.md` in the `filler.zip`.
