### ISSUE TITLE
filler

### ISSUE THREAD

**Issue by pr11t** [01-edu/public#1482]
The task description mentions that creating a bot that can beat the terminator is a [bonus task](https://github.com/01-edu/public/blob/master/subjects/filler/README.md#bonus).

But the [audit](https://github.com/01-edu/public/tree/master/subjects/filler/audit#general) seems to imply that terminator must be beat 4 out of 5 times to pass.
```
General

Try to run ./game_engine -f maps/<map of your choice> -p1 <path to student player> -p2 robots/terminator five times changing the position of the players each time so that the student player can be the p1 and the p2.

+Can you confirm that the student player won at least 4 out of 5 times?
```

I think it should be clarified whether beating terminator is required to pass the audit or not.

**Comment by mihkelgering** [comment]
Same thing with visualization part. Task description says creating visualization is a bonus, but in the audit we can see that this one is under General part.

**Comment by MSilva95** [comment]
![image](https://user-images.githubusercontent.com/53977751/194878053-a06e1cba-272c-4452-88b9-a013dc919710.png)
Hello @pr11t! Does it not appear as a bonus in the audit like in the image?

**Comment by MSilva95** [comment]
i will move it to a #### bonus instead.
you can see the fix here <https://github.com/01-edu/public/pull/1495>
