### ISSUE TITLE
arrays subject problem with lib

### ISSUE THREAD

**Issue by tonycava** [01-edu/public#1483]
Problem in RUST CHALLENGE
---
When i submit the arrays problem on the quest 3 i have this problem (image below) and also the same problem for the card_deck problem (alredy done before but now crash) but the other work fine can someone please help me !

![problem](https://user-images.githubusercontent.com/91544506/194037474-ac404a5f-f8d9-48f6-920b-61da8c83b949.png)

**Comment by mikysett** [comment]
Hello tonycava, thanks a lot for your feedback. Normally the issue has been solved and pushed into production.
I'll close the issue but if by any means you experience it again in any exercise please do not hesitate to answer back and I will reopen it.
