### ISSUE TITLE
Unconsistent date format

### ISSUE THREAD

**Issue by bde-maze** [01-edu/public#15]
The date format is not the same between the two games and 'mn' should get changed to 'mins' (avoid any confusion with months)

![Screenshot 2019-04-12 at 11 06 17](https://user-images.githubusercontent.com/15313830/56029979-9f4e9580-5d13-11e9-9d89-c18892e86a4b.png)

 - Laptop
 - OSX
 - Chrome

**Comment by lfoussat** [comment]
The display is like this on purpose. I display only the necessary. I don't display hours if there are only minutes. 
I've changed mn -> min
