### ISSUE TITLE
index subject

### ISSUE THREAD

**Issue by GlazeMoyu** [01-edu/public#1523]
index
---
func main() {
	fmt.Println(piscine.Index("Bonjour", "our"))

Prints -1 instead of 4  (4 is printed using fmt.Println(strings.Index("Bonjour", "our")) function)

**Comment by eslopfer** [comment]
Hi @GlazeMoyu, thanks for your feedback. 

From what I can deduce with the information you shared, it means that your implementation of Index, is not correct, as it should behave in a similar way as `strings.Index`. I would advise to look at your implementation.

Feel free to communicate with us again if that's not accurate, I'll close the issue for now.
