### ISSUE TITLE
to-git-or-not-to-git subject

### ISSUE THREAD

**Issue by ChristopheBoli** [01-edu/public#1534]
to-git-or-not-to-git
---
Bonjour, aidez moi svp !!
curl -s https://zone01normandie.org/api/graphql-engine/v1/graphql --data '{"query":"{user(where:{login:{_eq:\"choumi\"}}){id}}"}'

je dois isoler l'id, je sais pas comment faire!!

**Comment by davhojt** [comment]
Work with your fellow peers to try to figure it out. Keep trying.

**Comment by ChristopheBoli** [comment]
je sais que je dois travailler avec mes collègues, mais qui sont mes
collègues en fait et comment travailler avec eux, comment les contacter?
j'en ai aucune idée, j'ai cherché mais rien, je sais pas comment les
contacter.

**Comment by ChristopheBoli** [comment]
comment faire pour travailler avec mes collègues ? j'en ai aucune idée !!
