### ISSUE TITLE
printalphabet subject

### ISSUE THREAD

**Issue by RoyS122** [01-edu/public#1536]
printalphabet
---
![Capture d'écran_20221026_103146](https://user-images.githubusercontent.com/115789442/197983077-e3a6dd07-4ddc-4463-b142-53f89be62288.png)
![Capture d’écran 2022-10-26 110006](https://user-images.githubusercontent.com/115789442/197983377-db0814a1-8b1d-477b-810a-255b72b55ed1.png)

Message d'erreur quand je soumet au test, je n'avais jamais vu un message d'erreur comme celui ci et aucun moyen de le corriger

**Comment by davhojt** [comment]
Keep trying, and try to work it out with your fellow peers.
