### ISSUE TITLE
ascii-art subject

### ISSUE THREAD

**Issue by AidanaNBK** [01-edu/public#1563]
ascii-art
---
I've faced with an issue in the tests for the code with the given examples:
1. "hello There 1 to 2\!"
![image](https://user-images.githubusercontent.com/72804373/201620185-cd517b20-9408-459a-8ccc-e7b51b2f887c.png)
2. "\\!\" #$%&'()*+,-./"
![image](https://user-images.githubusercontent.com/72804373/201620061-bb60d1ff-b4bb-44a5-8a5c-3599c5ce56bf.png)

In the case 1, result should be following (according to given examples): hello There 1 to 2!
![image](https://user-images.githubusercontent.com/72804373/201620613-5086a96e-ad81-4a91-beaa-f68bbf1ffa43.png)

While in case 2: \!" #$%&'()*+,-./
![image](https://user-images.githubusercontent.com/72804373/201620533-e65fdcd5-3bf9-4184-8556-1dd56335206b.png)

Here I should point that in case if I try to read the given input by bytes, I've notices that "\\" and "\" (except the case when I just enter \, then it will be working as one of the bash command and will wait for me to continue my input) will be entered as the same thing. It means that the \ will be automatically shielded by second \, and it just a part of the bash command. 
Thus, when I code that \! should be read as !. then \\! will also be considered by my code as \!, and will be resulted as !. 
 
Finally it means that tests 1 and 2 conflicts with each other. Can you please justify it for me or fix this issue

**Comment by nprimo** [comment]
Hi Adriana, thank you for informing us about your doubt! 

I would suggest you experiment with passing arguments in the command line (for example, the snippet below) and see what are the different behaviours :) 

```console
echo hello world!
echo hello "world!"
echo hello "world\!"
````

**Comment by AidanaNBK** [comment]
Yes, I've checked it earlier. But I'm saying exactly regarding 2 case:
1. echo hello "world\\!"
2. echo hello "world\\!"
And that's why I've attached 2 cases from audits (where they are presented)

**Comment by nprimo** [comment]
Thank you for the follow-up and for pointing this out!
These differences in the behaviour of the shell are due to the different shells used: `bash` vs `zsh` for example.

We are going to make this audit clearer in the next few days
