### ISSUE TITLE
zappy subject

### ISSUE THREAD

**Issue by sagarishere** [01-edu/public#1587]
zappy
---
I am unable to understand if the world needs to be in what technology. Will three.js do or you want babylon or any technology is fine as far as it works?

Also, about AI, does it essentially need to be a neural network or a simple regression model with randomisation and self-correction towards a goal will also be categorised as AI, as it is characterised at many companies. 

Kindly be clear about the technologies we can use.

Also, do we need to host it or will running it at localhost suffice?

**Comment by MSilva95** [comment]
Hello @sagarishere!
You can see in the readme that we say the "Client" and "GUI" can be done in a language of your choice. Only the server has limitations for languages and you can't use "exec" funcs. Regarding the technologies, for now you are not able to use any kind of game engine, and that is the only restriction.
Localhost will do it.

I will add a small sentence to clarify this aspect. Thank you for the feedback!
