### ISSUE TITLE
Quest 01 introduction

### ISSUE THREAD

**Issue by GreyCoderK** [01-edu/public#160]
I have done all instruction but when i run the test it fail. But i think that my code is correct. It is the reason why i made several push to find the correct answer but it still failed.

```bash
./introduction_test.sh: line 3: ./student/hello.sh: Permission denied
1c1
< 
---
```

**Comment by xpetit** [comment]
Your code may be correct but sometimes, unfortunately, code isn't enough ;)
I would start searching Google for this “Permission denied” error
