### ISSUE TITLE
ascii-art subject

### ISSUE THREAD

**Issue by Toompere** [01-edu/public#1604]
ascii-art
---
Same code on mac and pc(windows/linux) gives different output for
"hello There 1 to 2\!" 

On mac it prints out ascii art without backslash, on pc it also prints out the backslash. All other audit questions are printed out correctly.

**Comment by nprimo** [comment]
Hi! Thank you for reporting this :) 

We're working to make `ascii-art` audits more consistent between different auditors' machines. One of the possible causes of the different behaviour between OS, might be the default shell used: running the tests with the same shell (for example `bash`) should give you the same results.
