### ISSUE TITLE
go-reloaded subject . vowel

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1608]
go-reloaded
---
Hi.
"Every instance of a should be turned into an if the next word begins with a vowel or a h. (Ex: "There it was. A amazing rock!" -> "There it was. An amazing rock!")."
Can we add something like EVEN 'y' and 'u' ? because that is not straightforward in English, what is a vowel.

**Comment by davhojt** [comment]
Thanks for your feedback @fulverin 👍🏾.
