### ISSUE TITLE
ascii-art subject examples: wrong spacing

### ISSUE THREAD

**Issue by robcat** [01-edu/public#1632]
Hello, in the provided examples at https://github.com/01-edu/public/blame/master/subjects/ascii-art/README.md#L116 (starting at the "Hello There" example), the spacing is off by one space.
In particular it can be noticed that the horizontal spacing between two lowercase `L`s is doubled, and not consistent with the previous examples.

**Comment by nprimo** [comment]
Thank you for reporting this issue!
