### ISSUE TITLE
math-skills subject

### ISSUE THREAD

**Issue by Yirmiyah** [01-edu/public#1653]
math-skills
---
My screen turn black when I click to the project "guess-it-1" I have some audits to pass to validate the project but I can't see nothing on the screen and it's the same thing for others projects on the branch algorithm.

**Comment by freeworldwhoo** [comment]
hello @Yirmiyah we will be looking to this we will get back to you as soon as possible

**Comment by freeworldwhoo** [comment]
hello @Yirmiyah can you confirm if the issue was solved if not can you provide us with your campus
