### ISSUE TITLE
cat subject

### ISSUE THREAD

**Issue by blvckpvblo** [01-edu/public#1664]
cat
---

Here's the error message that I'm seeing when testing my code.

```
Your program does not fail when it should (with a non-zero exit status) :

$ go run . "asd"
ERROR: open asd: no such file or directory
exit status 1$

Expected :

$ go run . "asd"
ERROR: open asd: no such file or directory
exit status 1$
```

My program is outputting exactly what's expected but the test keeps failing.

**Comment by eslopfer** [comment]
Hi @blvckpvblo keep trying. If you find yourself stuck, look to collaborate with your peers.
