### ISSUE TITLE
groupie-tracker-search-bar subject

### ISSUE THREAD

**Issue by jackedsparrow** [01-edu/public#1692]
groupie-tracker-search-bar
---
Current audit question:
Try to search for the location "london-uk".
Does it present as result "Pink Floyd", "Led Zeppelin", "Aerosmith", "Alec Benjamin", "Nickelback", "Eagles", "Linkin Park" and "Coldplay"?

There are two more bands that have london-uk as a location in the API currently missing from the audit question results - "Travis Scott" & "Fall Out Boy"

**Comment by eslopfer** [comment]
Hi @jackedsparrow , thanks for your feedback, that's right, the fix will be implemented shortly in the attached pull request. :slightly_smiling_face:
