### ISSUE TITLE
[ZZLE] - Hide/Show game control when tapping

### ISSUE THREAD

**Issue by bde-maze** [01-edu/public#17]
Annoying behavior of the game control, it keeps show and hide when tapping on the screen
![Screenshot 2019-04-12 at 11 39 42](https://user-images.githubusercontent.com/15313830/56031537-b7281880-5d17-11e9-9dcf-7eca52bbbff5.png)
![Screenshot 2019-04-12 at 11 39 46](https://user-images.githubusercontent.com/15313830/56031538-b7281880-5d17-11e9-82bd-0484735f32c0.png)

- Mobile OnePlus 5T
- Chrome

**Comment by RonaldoOsiro** [comment]
How do you play this game?

**Comment by swaepapi** [comment]
how is this game played? please someone help

**Comment by Stevovenom** [comment]
> how is this game played? please someone help

You need to arrange the arrows so as to traverse each and every box in the right way so as to reach the end which is claiming the star at each end.

**Comment by johnpriestpo-droid** [comment]
How do you pass level 3 pls
