### ISSUE TITLE
collections subject

### ISSUE THREAD

**Issue by healingdrawing** [01-edu/public#1708]
collections
---
error:
```
Error: Already failed code at commit d3c5016

Previous output:
test #15 failed:
({ eq }) => eq(superTypeOf(''), 'String')

AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ 'string'
- 'String'
    at eq (file:///app/test.mjs:45:3)
    at file://collections.js:124:15
    at runTests (file:///app/test.mjs:179:9)
```
Description where string is not capitalized
```
arrToSet: from Array to Set.
arrToStr: from Array to string.
setToArr: from Set to Array.
setToStr: from Set to string.
strToArr: from string to Array.
strToSet: from string to Set.
mapToObj: from Map to Object.
objToArr: from Object to Array.
objToMap: from Object to Map.
arrToObj: from Array to Object.
strToObj: from string to Object.
```

**Comment by davhojt** [comment]
Hey @healingdrawing.

There are two parts to the subject.
1. Convert from one data format to another to another. Here `String` != `string`. They have different meanings.
2. `superTypeOf` returns some string to indicate that you were able to identify some advanced types (which are not ordinarily detectable with `typeof`).

So, the subject is _okay_. That being said, I'm open to making it more clear and easy to understand. Do you feel it would be clearer if `superTypeOf` returned all lower case?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#description

**Comment by healingdrawing** [comment]
@davhojt hard to be sure. I only expect it will follow standards . So , requirements for all values from `typeof` should be similar as in `typeof`. But if other types outside of `typeof` have the different form(capitalized), perhaps they should be capitalized in requirements too.
Javascript is not to clear/strict language at the moment, to just say... "it must be like this!!!"
