### ISSUE TITLE
index-of subject

### ISSUE THREAD

**Issue by healingdrawing** [01-edu/public#1709]
index-of
---
```
test #10 failed:
() => lastIndexOf([t, 0, 0, t], t, 2) === 0

Error: Test failed
    at runTests (file:///app/test.mjs:185:15)
```
less drugs please, when you make tasks. The correct answer is 3, but not a zero. Or fix the task description.

task description part
```

lastIndexOf: which works just like your indexOf function, but returns the index of the last occurrence.
```
0 is first occurence inside array

**Comment by davhojt** [comment]
Correct answer is not 3.

`0` is correct. As `lastIndexOf` is the reverse of `indexOf`. Optional index starts from the end, and search is carried out in reverse.

```
[
 t, <- First match, is array 0.
 0, <- Optional index (search starts here in reverse)
 0,
 t,
]
