### ISSUE TITLE
elementary subject

### ISSUE THREAD

**Issue by 62oz** [01-edu/public#1711]
elementary
---

the expected result for modulo with negative b is wrong

**Comment by mikysett** [comment]
Hello @62oz 

Thanks for your report.

I've double-checked our tests for `modulo` function with all combinations of negative and positive `a` and `b`.
Actually the tests seems to work properly.

You can run the following code to check how modulo operator behave in JavaScript:
```js
console.log("123 % -22: " + 123 % -22)
console.log("-123 % 22: " + -123 % 22)
console.log("-123 % -22: " + -123 % -22)
```

the results should be:
```console
123 % -22: 13
-123 % 22: -13
-123 % -22: -13
```

I guess your implementation of `modulo` returns something different on the first or the third case, in which case you should fix the issue in your proposed solution and resubmit.

In case you still have some doubts about the correctness of the tests please feel free to write back with more info about the specific discrepancies you identified and I'll reopen the issue and investigate more into it.
