### ISSUE TITLE
[BUG] NaN is shown as XP amount on project list page

### ISSUE THREAD

**Issue by uristdwarf** [01-edu/public#1715]
**Describe the bug**
NaN is shown as xp amount on some projects.

**Users**
Pretty much everyone I know at the kood/Jõhvi school

**Severity**
❗️minor

**Type**
🖌️ ui

**To Reproduce**

1. Go to profile page
2. Click on Go To Div 0
3. See XP amounts

**Workarounds**
You can see XP amounts of projects you've unlocked by clicking on them.

**Expected behavior**
See the normal XP amounts

**Attachments**
![image](https://user-images.githubusercontent.com/7394119/212273451-cfea20fe-feb7-44c0-bd95-e62bacf1aadd.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 108.0.2

**Additional context**

**Comment by freeworldwhoo** [comment]
Hello @uristdwarf we are looking into this we will get back to you as soon as possible

**Comment by uristdwarf** [comment]
@freeworldwhoo seems to be fixed

**Comment by freeworldwhoo** [comment]
thank you @uristdwarf  for your return I will close this as it is solved now
