### ISSUE TITLE
[BUG] AI piscine - Numpy "Football tournament" answer

### ISSUE THREAD

**Issue by Whovillage** [01-edu/public#1725]
**Describe the bug**
In the AI piscine - numpy audit the provided answer for the last task "Football tournament" seems to be wrong

❗️minor

🗂️ documentation

The provided answer is  
`[[0 3 1 2 4][7 6 8 9 5]]`

However we all got 
`[[2, 9, 6, 0, 8], [1, 3, 5, 7, 4]]`

and manual checking of the data seems to confirm our answer. 

Please check if the answer provided is correct.

**Comment by eslopfer** [comment]
Hi @Whovillage you are right. Thanks for the feedback. It's going to be changed on the attached pull request and should be available shortly.
