### ISSUE TITLE
long-words subject

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#1727]
long-words
---
<img width="1509" alt="Screen Shot 2023-01-18 at 11 02 56" src="https://user-images.githubusercontent.com/18734845/213132757-eb1721a7-065a-49aa-8213-85a3a7c38eaf.png">

The task does not specify that you have to use 
Array.prototype.every
Array.prototype.some

You can solve this using only Array.prototype.filter

**Comment by eslopfer** [comment]
Hi @sailordi you have something to fix in your code. Collaborate with your peers, keep trying, and good luck :slightly_smiling_face: .

**Comment by sailordi** [comment]
I ran all the test locally and got the right answer with filter the only thing i changed to pass was switch to using every and some
<img width="2240" alt="Screen Shot 2023-01-19 at 13 07 43" src="https://user-images.githubusercontent.com/18734845/213427452-4ceaf125-e9f9-42e8-ae4c-d3b3ae5d5f04.png">
