### ISSUE TITLE
[BUG] AI piscine day 3 (visualizations) - Ex 1 audit questions

### ISSUE THREAD

**Issue by Whovillage** [01-edu/public#1728]
**Describe the bug**
AI piscine Visualizations (day 3) audit question for exercise 1 contains wrong information.

❗️minor

🗂️ documentation

First exercise audit questions do not match with the exercise. The old archived repo's audit questions are correct, but in the new repo and in the intra they are wrong.

To fix, copy the questions from the old repo.

**Comment by eslopfer** [comment]
Hi @Whovillage . Thank you very much for your feedback. The changes will be implemented on the attached pull request.
