### ISSUE TITLE
piscine-js/race Does the tests work with a valid exercise example?

### ISSUE THREAD

**Issue by October45** [01-edu/public#1737]
We're currently doing the exercise race in the JS Piscine.
We think the test might be broken as you are in the race_test.js file making ```Promise.race = undefined```, which you are using in your ```runTests()``` function in test.mjs.
When I go back to commit ```2a5383c3c358c41d164087fe16898c6ff2b236e4``` the one before ```d8ec885b25f69137f165552114f440f6733e4fa5``` where you add ```Promise.race``` to test.mjs the tests seem to work.

We've tried commenting the ```Promise.race = undefined``` in todays version of race_test.js and that gives me the same result as the old commit does.

**Comment by eslopfer** [comment]
Hi @October45 good catch! That's indeed a bug. The fix will be implemented soon in the attached pull request.

**Comment by ololax123** [comment]
Still seem to get this error: 
<img width="1006" alt="Screenshot 2023-01-25 at 9 35 00" src="https://user-images.githubusercontent.com/35573940/214505586-7cc70e24-cd8a-4015-9cae-6b7d6eedbf90.png">

**Comment by davhojt** [comment]
Hey @ololax123.

To unblock you quickly, I've created a fast fix. This issue will remain open until we make a more permanent fix. Could you confirm that you're able to continue now?
