### ISSUE TITLE
[BUG] AI piscine - data-wrangling - Exercise 5: inconvenient data

### ISSUE THREAD

**Issue by Whovillage** [01-edu/public#1738]
**Describe the bug**
In AI piscine day 4 (data-wrangling) Exercise 5 the input data for the exercise is provided as a table

**Type**
🗂️ documentation)

**Expected behavior**
It would be better if the input data was  provided as code (Pandas dataFrame) like in other exercises so that the students could copy instead of creating the data structure manually.

**Comment by eslopfer** [comment]
Hi @Whovillage. Thanks for your feedback. I'll close this issue because we are talking about 7 rows and 2 columns here. total amount of 14 values, with some of them repeated.

Please don't feel discouraged to open new issues with your feedback :slightly_smiling_face:
