### ISSUE TITLE
where-do-we-go subject

### ISSUE THREAD

**Issue by healingdrawing** [01-edu/public#1740]
where-do-we-go
---
what is that?
where are the limits described?
<img width="564" alt="Screen Shot 2023-01-20 at 02 31 42" src="https://user-images.githubusercontent.com/39751647/213592418-51e356bf-bf76-4e92-85e8-db9c482b04c2.png">

**Comment by ololax123** [comment]
Delete the folder with the images for the excersie and you will be fine (Y)

**Comment by eslopfer** [comment]
I'll close this since it appears to be solved. Feel free to open a new issue if it's not.
