### ISSUE TITLE
invert subject

### ISSUE THREAD

**Issue by healingdrawing** [01-edu/public#1743]
invert
---
the task
```
Create a function named invert which takes an object and returns **it** with its keys and values inverted.
```
but , this code not works, with some muddy error from test side , about prototype ignoring required
```javascript
const invert = (obj) => {
  const keyvals = Object.entries(obj).filter(([key]) => obj.hasOwnProperty(key));
  keyvals.forEach(([key, val]) => {
    obj[val] = key;
    delete obj[val];
  });
  return obj;
};
```
and this code works (pass the tests) ,
```javascript
const invert = (obj) => {
  const newObj = {};
  const keyvals = Object.entries(obj).filter(([key]) => obj.hasOwnProperty(key));
  keyvals.forEach(([key, val]) => {
    newObj[val] = key;
  });
  return newObj;
};
```

 but  ``` it ``` means incoming object but not a new one. And where is the requirements about ignoring prototype in task description?

**Comment by eslopfer** [comment]
Hi @healingdrawing, you are right, the phrasing is not 100% accurate. The changes will be implemented shortly in the pull request attached to this issue.

Thanks for your feedback.
