### ISSUE TITLE
wget subject

### ISSUE THREAD

**Issue by nater6** [01-edu/public#1770]
wget
---
The ThinkDownload website states " NOTE: We provide these download files primarily for UK broadband users; although we do not prohibit their use by others, we do not allow scripted/automated download of these files. Our systems routinely block repetitive attempts which we believe are automated or abusive. If you get an 'unauthorised' error message, you can contact us (please include [your IP address](https://www.thinkbroadband.com/tools/what-is-my-ip) when contacting us)."

This results in a forbidden error when attempting to download the following files:
http://ipv4.download.thinkbroadband.com/100MB.zip
http://ipv4.download.thinkbroadband.com/20MB.zip
http://ipv4.download.thinkbroadband.com/10MB.zip

 I imagine this is because we are running a scripted/automated download.

https://www.thinkbroadband.com/download#:~:text=Click%20the%20file%20you%20want,to%20force%20it%20as%20required.

**Comment by davhojt** [comment]
Hey @nater6.

Was this issue resolved? We're planning to take a look at it this week.
