### ISSUE TITLE
push-swap subject

### ISSUE THREAD

**Issue by sagarishere** [01-edu/public#1785]
push-swap
---
this does not tally up with any of your instruction:
$ go run ./checker "3 2 1 0"
sa
rra
pb
KO

**Comment by sagarishere** [comment]
stdin has nothing in this case. However, in output we have a list of steps followed by KO.
KO means not OK. What are the steps about.

**Comment by davhojt** [comment]
The example may not be super clear. But some of those lines are `stdin`, and some are `stdout`
```console
$ go run ./checker "3 2 1 0"
sa <- stdin
rra <- stdin
pb <- stdin (something happens here to end stdin)
KO <- stdout/stderr
```

**Comment by sagarishere** [comment]
Could you make it clear like this:

$ echo -e "sa\nrra\npb\n" | go run ./checker "3 2 1 0"
sa
rra
pb
KO

**Comment by davhojt** [comment]
The `checker` program doesn't print the input though, so that would actually look like this:
```console
$ echo -e "sa\nrra\npb\n" | go run ./checker "3 2 1 0"
KO
```

**Comment by sagarishere** [comment]
I got the impression that in case of KO, the checker has to print the steps and in case of OK it does not. 

Thank you for this clarification.

Your proposal below satisfies the explanations in the question perfectly:
```
$ echo -e "sa\nrra\npb\n" | go run ./checker "3 2 1 0"
KO
```
this will be perfect and clarify things.

If I may request to edit this example as per your suggestion.

Old version:
```
$ go run ./checker "3 2 1 0"
sa
rra
pb
KO
```

New version:
```
$ echo -e "sa\nrra\npb\n" | go run ./checker "3 2 1 0"
KO
```

**Comment by sagarishere** [comment]
ohhh.. okay. I got it now. You want the user to put input into standard in, in case the length of args[1:] is not zeros, as well as the size of stdin is 0 bytes. 
however, this has not been mentioned in the instructions. 
So either this should be clearly mentioned or this becomes very confusing. I am being very honest here. This was confusing. I discussed it with other students also and nobody I discussed with could understand it.
Students just ignored it as it is only mentioned in examples here but such a case is not covered in the audits.

**Comment by davhojt** [comment]
I agree to make it more clear. It's important to do it in a way that leaves something to be discovered by the learner. In the same way that you discovered yourself about ctrl+d to end the input to `stdin`.

I consider that if a learner understands `stdin`, then they will know that this input can be provided via a pipe, or via keyboard entry from the user. I think the missing clarity, is that the following makes it look like `sa`, `rra` and `pb` are output by `checker`. It doesn't look obvious that those are `stdin`.

```console
$ go run ./checker "3 2 1 0"
sa - this
rra - this
pb - this
KO
```

About your comment on the audits. There are actually some cases which are not tested here, which would be better tested with keyboard input from the user. Particularly to make sure that ALL of the valid instructions are considered before `OK` or `KO` is printed.

**Comment by sagarishere** [comment]
Ohh.. I love the easter egg thingy. Now I understand :)

**Comment by davhojt** [comment]
@sagarishere 

> Ohh.. I love the easter egg thingy. Now I understand :)

Discovering those often results in a nice dopamine boost 😊.

The purpose of the curriculum in general, is to enable learners to become skilled in solving problems for themselves. So that when you arrive at the workplace, you have no fear to learn new things on your own, and are skilled in finding solutions to problems. To achieve this, the subjects are often intentionally vague, so that you need to collaborate with others or research your way to a solution.

I'm saying that to ensure that you don't lose motivation to provide feedback, even if we sometimes decide to keep the subjects slightly vague. There is some method to the madness 😅.

**Comment by sagarishere** [comment]
In the task description: checker is a folder here: 
```
$ go run ./checker "3 2 1 0"
sa
rra
pb
KO
$ echo -e "rra\npb\nsa\n" | go run ./checker "3 2 one 0"
Error
$ echo -e "rra\npb\nsa\nrra\npa"
rra
pb
sa
rra
pa
$ echo -e "rra\npb\nsa\nrra\npa" | go run ./checker "3 2 1 0"
OK
$ go run ./checker
$
```

Whereas in the audit question, checker is an executable here:
`./checker "0 one 2 3"`

`echo -e "sa\npb\nrrr\n" | ./checker "0 9 1 8 2 7 3 6 4 5"`

Shall we only provide the executables in the repo to the auditor or we have to provide the code also. Because if checker is name of child folder, a file with the same name cannot be created at same directory level.

Maybe something on this could be clarified either in the task description or in the audits.

**Comment by davhojt** [comment]
@sagarishere You're right.

We'll modify it to ensure that it is audited in the context of built binaries. So that `checker` and `push_swap` are next to each other.

Thank you for noticing 👍🏾
