### ISSUE TITLE
listsort subject

### ISSUE THREAD

**Issue by qazmaster** [01-edu/public#1787]
listsort
---
func listPushBack(l *piscine.NodeI, data int)  {
	n := &piscine.NodeI{Data: data}

	if l == nil {
		return n
	}
	iterator := l
	for iterator.Next != nil {
		iterator = iterator.Next
	}
	iterator.Next = n
	
}

func main() {
	var link *piscine.NodeI

	listPushBack(link, 5)
	 listPushBack(link, 4)
	 listPushBack(link, 3)
	 listPushBack(link, 2)
	listPushBack(link, 1)

	PrintList(piscine.ListSort(link))
}

looks better without inquired extra elements in the code

**Comment by MSilva95** [comment]
Hello @qazmaster! 
This code is not running correctly. But what is the problem of the current usage program? Isn't it working for you?

**Comment by MSilva95** [comment]
Closed for lack of reply!
Feel free to reopen the issue if necessary!
