### ISSUE TITLE
make-your-game subject

### ISSUE THREAD

**Issue by danglam88** [01-edu/public#1788]
make-your-game
---
Hello and good day,

We are currently doing the project make-your-game. There is one question from the audits that is quite unclear to me (and many others) as follows:

Use the Dev Tool/Performance to record and try pausing the game while it is running.
Try moving the player/element using the proper commands and keys to do so.
Does the player obey the commands?

Does it mean that even if the game is paused, we must still be able to move the player using the keyboard? If so, it seems to be very illogical to me (and other people) since when a game is paused, none of its contents should be able to move at all regardless of using the keyboard or not. Maybe something is missing from the question?

I hope to be hearing an answer from you soon. Thanks very much for your consideration!

Best regards
Dang Lam

**Comment by eslopfer** [comment]
Hi @danglam88, you are right, the audit needs some clarification. It'll be addressed shortly in a PR attached to this issue. Thanks for your feedback.

**Comment by danglam88** [comment]
Thanks for your fixes!
