### ISSUE TITLE
[BUG] Missing image in Deep-In-System README.md

### ISSUE THREAD

**Issue by lotoussa** [01-edu/public#1797]
missing image at the beginning of the subject
https://atos.demos.01-edu.org/git/root/public/media/branch/master/subjects/devops/deep-in-system/pictures/sysadmin.jpeg
![image](https://user-images.githubusercontent.com/66522867/218263144-9e11a54a-5261-446d-851d-5c983c446246.png)
google chrome

**Comment by davhojt** [comment]
It's present.
@lotoussa Open a new SUP issue if you find it to be missing.
<img width="849" alt="image" src="https://user-images.githubusercontent.com/22807573/227868436-53a208d3-682c-4a12-918f-c0c559d30b96.png">

**Comment by lotoussa** [comment]
yes sorry was a false alarm, just need to refresh caching
