### ISSUE TITLE
[BUG] Infinite loading

### ISSUE THREAD

**Issue by maximihajlov** [01-edu/public#1810]
**Describe the bug**
One of the chunks gets an unexpected 404 which causes infinite loading

**Users**
Several students from grit:lab ([01.gritlab.ax](https://01.gritlab.ax))

**Severity**
⚠️ critical

**Type**
⚙️ functionality, 🖌️ ui

**To Reproduce**

1. Hard refresh / Open a new window in Chrome or Safari
2. Login
3. See infinite loading and 404 for one of the chunks

![image](https://user-images.githubusercontent.com/43277901/219953524-01b698f5-84ee-4f09-b4ce-69222f13beb4.png)

**Workarounds**
1. Open the chunk directly and see an unexpected 404

![image](https://user-images.githubusercontent.com/43277901/219953604-66e0dd74-411e-4a68-959a-4284b101a732.png)

3. Hard refresh (`Ctrl+F5`) and see a valid chunk

![image](https://user-images.githubusercontent.com/43277901/219953637-84327c99-855b-4f59-bb43-51cf4bd2afa5.png)

4. Move back to the main page and refresh using cached chunk (**NOT HARD**)

![image](https://user-images.githubusercontent.com/43277901/219954902-2e81f2d9-14aa-4972-9de0-df6c13365025.png)

or use **Desktop Firefox**

---

**Reproduced on desktops**

- OS: MacOS, Windows, Linux
- Browser: Chrome and Safari, but **not Firefox**
Latest versions

**and smartphones**

- OS: Android and iOS
- Browser: Chrome, Safari, Firefox
Latest versions

on Android Firefox it's even worse, no `Loading...`, just nothing happens.

**Comment by freeworldwhoo** [comment]
hello @maximihajlov do you still have the same issue?

**Comment by maximihajlov** [comment]
No, it looks fixed to me. I haven't encountered that bug for over a week now.
