### ISSUE TITLE
nbrconvertalpha subject

### ISSUE THREAD

**Issue by Vonewman** [01-edu/public#1820]
nbrconvertalpha
---
I solved the problem but I have this output:

$ go run . "12" "5" "7" "5" "14" "56" "4" "1" "18" "25" "32" "86" "h"
legen dary    
$

Expected :

$ go run . "12" "5" "7" "5" "14" "56" "4" "1" "18" "25" "32" "86" "h"
legen dary   
$

**Comment by nprimo** [comment]
Hi,

You should read again the subject and have a second look at the examples provided :)

Good luck :muscle:
