### ISSUE TITLE
real-time-forum subject

### ISSUE THREAD

**Issue by danglam88** [01-edu/public#1841]
real-time-forum
---
Hello,

The first audit question asks "Do you need to register/login in the forum to use it?". Does it mean unregistered user cannot use the forum at all (cannot even read any posts or comments)? If so, will an unregistered user coming to the forum only see a blank page (except for the Register link and the Login form)?

Thanks for your concern!

Best regards
Dang Lam

**Comment by MSilva95** [comment]
I will add a bit more info on the readme, Thank you for the feedback.
