### ISSUE TITLE
nbrconvertalpha subject

### ISSUE THREAD

**Issue by Pinkish-Warrior** [01-edu/public#1842]
nbrconvertalpha
---
package main

import (
	"os"

	"github.com/01-edu/z01"
)

func main() {
	args := os.Args[1:]

	var nums []int
	for _, arg := range args {
		if arg == "--upper" {
			continue
		}
		var num int
		for _, r := range arg {
			if r < '0' || r > '9' {
				num = -1
				break
			}
			num = num*10 + int(r-'0')
		}
		if num != -1 {
			nums = append(nums, num)
		}
	}

	if len(nums) == 0 {
		return
	}

	var result string
	if args[0] == "--upper" {
		for _, num := range nums {
			if num < 1 || num > 26 {
				result += " "
				continue
			}
			result += string(rune(num + 'A' - 1))
		}
	} else {
		for _, num := range nums {
			if num < 1 || num > 26 {
				result += " "
				continue
			}
			result += string(rune(num + 'a' - 1))
		}
	}
	for _, r := range result {
		z01.PrintRune(r)
	}
	z01.PrintRune('\n')
}

**Comment by Pinkish-Warrior** [comment]
`Your program output is not correct :

$ go run . "12" "5" "7" "5" "14" "56" "4" "1" "18" "25" "32" "86" "h"
legen dary  
$

Expected :

$ go run . "12" "5" "7" "5" "14" "56" "4" "1" "18" "25" "32" "86" "h"
legen dary   
$`

**Comment by davhojt** [comment]
You'll need to fine tune your solution. Collaborate with your fellow learners to try to find a solution.
