### ISSUE TITLE
[BUG] Mobile Development Piscine - movie_list

### ISSUE THREAD

**Issue by JesusKris** [01-edu/public#1843]
**Describe the bug**
Mobile Development piscine task **movie_list**  includes a data list of movies in JSON format. Each movie also contains "Poster" field with http image link.  Our task is to fetch the image and then display it.

When tried fetching the image, I receive the following message:

**HTTP request failed, statusCode: 403**

403 - indicates that the server understands the request but refuses to authorize it.

Could it be on my end or servers end?

**Users**
Student: nimi25820

**Severity**
❗️minor - Unable to complete the task to its full extent.

**Type**
🖌️ ui,
⚙️ functionality,

**To Reproduce**
1. Open a new Flutter application
2. Paste the following in **lib/main.dart**
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 50,
            height: 50,
            child: Image.network("Poster URL"),
          ),
        ),
      ),
    );
  }
}
```
3. Replace the URL to a valid one.
4. Emulate the Flutter application on your machine or a smartphone using flutters Hot Reloaded dev enviorment.
5. Check your IDE debugger for the error.

**Expected behavior**
Get 202 status code and fetch the image.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: -
- Version:  22.04.2 LTS

**Additional context**
IDE: VSCode

Flutter version: 3.7.6

Flutter application emulated on **Linux (linux-x64)**

**Comment by sakenism** [comment]
@JesusKris thanks for the report, it seems that old url is deprecated
@davhojt please have a look at pr: https://github.com/01-edu/public/pull/1768

**Comment by davhojt** [comment]
Hey @JesusKris.

The maintainer has added new links. It transpired that the links that were there didn't work inside the EU from some moment in time.

Thank you for your report.

Note, I've merged the links as quickly as possible, and every link will be validated shortly.

**Comment by davhojt** [comment]
Confirmed all links: https://raw.githubusercontent.com/01-edu/public/e3be2d4be2ef30c855beb2feaf4569de0c6494ed/subjects/mobile-dev/movie-list/movies.json
