### ISSUE TITLE
bloody-sunday subject

### ISSUE THREAD

**Issue by Peafield** [01-edu/public#1844]
bloody-sunday
---

The text for the explanation appears as: error reading the markdown: This subject is under maintenance or is not ready yet, come back later USAGE: https://learn.01founders.co/markdown/USER/REPO/FILE_PATH.md Working example: https://learn.01founders.co/markdown/root/public/subjects/printalphabet/README.md error reading the markdown: This subject is under maintenance or is not ready yet, come back later

USAGE: https://learn.01founders.co/markdown/USER/REPO/FILE_PATH.md
Working example: https://learn.01founders.co/markdown/root/public/subjects/printalphabet/README.md

**Comment by davhojt** [comment]
Closing as it duplicates #1845
