### ISSUE TITLE
[FEATURE] a less random auditor selection

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1847]
**Is your feature request related to a problem? Please describe.**
This is a suggestion

**Type**
⚙️ functionality

**Expected benefit**
A way better auditors involvement

**Target audience**
Students

**Describe the solution you'd like**
What about we (you actually) make the selection of the auditor less random : 
giving more chance to people doing a task, to also be auditor for that task or one in the neighboring.
Thus auditors will have better interest into : audit spec, how the thing work, why such design choice, etc.
And if auditor just finished the task then he will be more "involved/aware" about spec details he struggled to reach and check alternatives they missed.
I doubt people could really deep into someone else forum audit details when they are stuck at ascii art, they may just "store" it as an example. (and the other way around)

Plus as a bonus, people will then get more contact with people of similar progress. Imagine you just finish a task and looking for teammates, in the meantime you audit someone for the task just before and have great technical exchange. You just find your next best coding buddy for your task.

**Comment by davhojt** [comment]
Hey @fulverin.

May I ask you for your Discord handle? Or you may add me at one of the following and let me know that it's you "fulverin":
- Discord: davhojt#3605
- https://www.linkedin.com/in/davhojt/

**Comment by davhojt** [comment]
Thank you for your input @fulverin, it was super useful to get your input towards shaping how that feature develops.
