### ISSUE TITLE
printprogramname subject

### ISSUE THREAD

**Issue by MSK17A** [01-edu/public#1848]
printprogramname
---
Failed to print the program name : ./choumi

exit status 1

Tried to print program name, it runs on my system, but it is not working in the website.

**Comment by davhojt** [comment]
Please share your solution.

**Comment by davhojt** [comment]
@MSK17A Please collaborate with your fellow peers to solve the problem, and let us know if you believe there is a problem with the automatic tests by opening a new issue.
