### ISSUE TITLE
fifty-shades-of-cold subject

### ISSUE THREAD

**Issue by bomanviktor** [01-edu/public#1849]
fifty-shades-of-cold
---
Bugged quest as of Tue 7 Mar 2023:

import {colors} from "./fifty-shades-of-cold.data.js";

let styles = [];
export function generateClasses(){
    var style = document.createElement("style");
    style.textContent = '';
    for(let i = 0; i < colors.length; i++){
        let color = `.${colors[i]} {\n\tbackground: ${colors[i]};\n}\n\n`;
        style.textContent += color;
    }
    document.getElementsByTagName('head')[0].appendChild(style);
}

export function generateColdShades(){
    for(let i = 0; i < colors.length; i++){
        if(colors[i].match(/blue/g)      ||
           colors[i].match(/aqua/g)      ||
           colors[i].match(/turquoise/g) ||
           colors[i].match(/green/g)     ||
           colors[i].match(/cyan/g)      ||
           colors[i].match(/navy/g)      ||
           colors[i].match(/purple/g))
        {
            let div = document.createElement("div");
            div.setAttribute("class",colors[i]);
            // div.className = `${colors[i]}`;
            div.textContent = colors[i];
            styles.push(colors[i]);
            document.body.append(div);
        }

    }
}

export function choseShade(d) {
    let divs = document.querySelectorAll('div');
    for(let i = 0; i < styles.length; i++){
        if (!divs[i].classList.contains(d)) {
            divs[i].classList.replace(divs[i].className, d);
        }
    }
}

**Comment by davhojt** [comment]
@bomanviktor Could you describe the problem you have?

**Comment by davhojt** [comment]
@bomanviktor Please open a new issue with a description of your feedback if you have something to tell us.

**Comment by bomanviktor** [comment]
It failed test #0.

Everyone who passed the quest on the piscine who re-submitted
fifty-shade-of-cold got "failed" while every other assignment in the quest
passed.
