### ISSUE TITLE
go-reloaded subject

### ISSUE THREAD

**Issue by SSMM0498** [01-edu/public#1852]
go-reloaded
---
In the subject we have this kind of marks '. However in the audit process we have this one ‘

**Comment by davhojt** [comment]
@SSMM0498 Which we browser do you use?

**Comment by ololax123** [comment]
Seems to be dupe of problem https://github.com/01-edu/public/issues/1515

**Comment by davhojt** [comment]
@freeworldwhoo This has been reported before.
Quote character is converted to a speech mark.

**Comment by SSMM0498** [comment]
> @SSMM0498 Which we browser do you use?

Edge

**Comment by SSMM0498** [comment]
> Seems to be dupe of problem #1515

Yeah it is

**Comment by freeworldwhoo** [comment]
Hello @SSMM0498 we are looking into this we will get  back to you as soon as possible
