### ISSUE TITLE
guess-it-1 subject / Confusing naming

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1870]
guess-it-1
---
### Issue
The task project is called `guess-it-1`, the provided zip file is called `guess-the-number.zip` and the `README.md` inside that zip file refers to the project as `guess-the-name`.

> This file should be an executable shell script that runs the student program if you are in the root folder `guess-the-name/`. The filesystem should look somethings like this:
> 
> ```console
> ─ guess-the-name/
> ├── ai/
> │   ├── big-range
> │   └── ...
> ├── index.html
> ├── index.js
> └── ...
> └── student/
>     ├── ...
>     └── script.sh
> 
> ```

### Suggestion
Use `guess-it` throughout the project consistently, by renaming the zip file to `guess-it.zip` and correcting the references in `README.md`.

**Comment by mikysett** [comment]
thanks a lot for the contribution!
A PR is on its way to improve consistency ;)
