### ISSUE TITLE
passive subject / no xp awarded on completion

### ISSUE THREAD

**Issue by specest** [01-edu/public#1871]
passive
---
No xp awarded after completing the audits.

**Comment by freeworldwhoo** [comment]
Hello @specest can specify what do you mean by no xp awarded is it you finished a project and validated but you didn't get any project XP or it is something else ?

**Comment by specest** [comment]
> Hello @specest can specify what do you mean by no xp awarded is it you finished a project and validated but you didn't get any project XP or it is something else ?

Yes, that's exactly what I mean.

**Comment by freeworldwhoo** [comment]
okay thank you @specest we will get back to you as soon as possible

**Comment by freeworldwhoo** [comment]
Hello @specest the issue is solved now, thank you.
