### ISSUE TITLE
personal-shopper subject

### ISSUE THREAD

**Issue by Peafield** [01-edu/public#1896]
personal-shopper
---
In all the examples given the key of the json object in the json file is written with quotation marks, however in test #3, it is without quotation marks. This is very misleading

**Comment by MSilva95** [comment]
Can you send the example on a print please?
If you are talking about this example:
- `node personal-shopper.mjs shopping-list.json ls` would print the list in your
  console like this:
```
- tzatziki pot (1)
```
Remember this is an output on the console so it wont have the quotes like the others. If it is not this one please let me know.

**Comment by MSilva95** [comment]
Will be closed for lack of info. please reopen if still needed!
