### ISSUE TITLE
guess-it-2 subject "error in the number of the test data"

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1905]
guess-it-2
---
at the really end it says:

"If you fail one of these steps, the test will not work. So we advise you to run the test by downloading [this zip file](https://assets.01-edu.org/guess-it/guess-it.zip) containing the tester. You should place the student/ folder in the root directory of the items provided and read its instructions. The data sets used to test this exercise will be **Data 5 and Data 6.**"

Pretty sure it is 4 and 5 instead since there is no 6 and guess-it-1 made us test 1, 2 and 3

**Comment by mikysett** [comment]
thanks a lot for the catch! I've updated the subject
