### ISSUE TITLE
guess-it-1 subject [bug number format JS server]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1912]
guess-it-1
---
Hi,
something strange , when I test my guesser against the ai one some results are displayed with aukward numbers
if I take my results :

168 <> 185
Result= 618
Value #132: 166

150 <> 162
Result= 967
Value #137: 168

**_2528 <> 2647
Result= 4 314
Value #2537: 2644_**

170 <> 187
Result= 618
Value #133: 135

157 <> 170
Result= 1 024
Value #138: 164

**_2509 <> 2626
Result= 4 314
Value #2538: 2674_**

or ai results (nic)

180 <> 180
Result= 800
Value #132: 166

138 <> 138
Result= 800
Value #137: 168

_**2715 <> 2715
Result= 21 600
Value #2537: 2644**_

166 <> 166
Result= 800
Value #133: 135

168 <> 168
Result= 800
Value #138: 164

_**2644 <> 2644
Result= 21 600
Value #2538: 2674**_

some are above 2600 and still can still score (and I am pretty sure that at least my guesser cannot anticipate such jump)
so I assume is number format/display that is involved.
that is the best I can do until I do the JS piscine.

edit : ho and I am using firedragon (firefox) arch

**Comment by fulverin** [comment]
Hi @nprimo. .. um this is way too much long time ago and the output format is way too cryptic .
And my code probably changed 20 times since then.
btw just changing result by score would make everyone happy I think.

if you look at the way the score is written it seems that there was a shift about the new range provided by the guesser and the new value to add to the pool... 

I think that bug happened to me only one time and did not really prevented me from progressing.
sorry that is as much as I can do.

**Comment by nprimo** [comment]
Thank you so much for the feedback! Since there is not much I can do now, I will close this ticket. Feel free to open a new one if you have more information about the code causing the behaviour you described.

Have a lovely week!
