### ISSUE TITLE
[Status of exercise] - wrong status

### ISSUE THREAD

**Issue by sakenism** [01-edu/public#192]
Status of exercise after successful submission is wrong

**To Reproduce**
1. Complete exercise #1
2. No matter fail/success go to next exercise
3. Look at the status, it is the same as in previous

**Type** minor

**Priority** normal

![Screenshot from 2019-06-19 18-56-18](https://user-images.githubusercontent.com/35443199/59768397-1bda9300-92c6-11e9-9102-0922037c5cdf.png)

**Comment by lfoussat** [comment]
are yoiu talking about the status in the test panel? the success mention is related to the last test run, you can see it on the left (introduction). We have noticed that it can be confusing, we'll try to make it more clear with UX
