### ISSUE TITLE
graphql subject

### ISSUE THREAD

**Issue by MalinOsc** [01-edu/public#1921]
IMPORTANT!!! graphql
---
Hello!
Issue from GritLab:
currently we all are blocked of using graphql API from external programs. it only works from the graphiql client as it already has the access token in use. and we dont have that if we for example just run a curl command it wont work.

**Comment by davhojt** [comment]
Hey @MalinOsc 

We'll merge the updated project soon, which will describes a new requirement to add a login page - allowing you to obtain a token.

You can see it here ahead of time however: https://github.com/01-edu/public/blob/db453991451a3e7ed8f8062f86174adc6e0321d6/subjects/graphql/README.md

**Comment by mathisen99** [comment]
hi still problems with CORS policy. do we realy need to make headers to go around this. sounds like bad solusion for students.
[https://imgur.com/a/OFin2EW](url)

**Comment by davhojt** [comment]
Hey @mathisen99. Normally I don't like to give too many clues 😅. But for this, I'd like to make sure things are working as expected.

<img width="359" alt="Screenshot 2023-03-31 at 16 54 12" src="https://user-images.githubusercontent.com/22807573/229139649-a7eaa64b-dc99-4460-bf35-582228d22ed2.png">

Your URL has a double forward-slash. May I ask if that is a typo by you, or did you copy that explicitly from the subject?

**Comment by davhojt** [comment]
I'm just asking because we have a `((DOMAIN))` variable, which is replaced with your schools domain. But I cannot see how it renders in your context.

**Comment by mathisen99** [comment]
sorry for typo but it is same with corr
<img width="1394" alt="Screenshot 2023-03-31 at 16 58 23" src="https://user-images.githubusercontent.com/5032480/229141403-09aeac06-cee5-4f31-9255-0b52bfeaa425.png">
ect url.

**Comment by danglam88** [comment]
@davhojt mathisen99 has already updated a new picture with a correct URL in his last comment.

**Comment by healingdrawing** [comment]
@davhojt It sounds like personally you are ready to compensate for every person of loosing data in case of credentials will be insecurely used.

You new epic ... changes ... require the login/logout using student credentials in not safe place, with not trusted site. Because the **students work can not be the trusted site**.
It smells like brown substance.

**I want to do not use my credentials,  just for demonstrate really not interested for anyone and not needed group of symbols, using not safe source.**

You forcing the students use the credentials and compromise the security of students' personal data and access to the platform you claim you are trying to keep private. 

How many personalities do you have inside your head?

Remove the login/logout requirement if possible(and i know it is possible), because noone wants to use important credentials(with personal data includes potential relatives contacts) with no named site, which was created by the student.

And I hope you will not participate in the improvements of the cybersecurity section. This potential case just scaring me.

**Comment by davhojt** [comment]
@mathisen99 May I ask if you have a `Access-Control-Allow-Origin` header in the response? And if so, what its value is?

**Comment by danglam88** [comment]
@davhojt  Yes, I'm currently inside the campus.

**Comment by davhojt** [comment]
If you make a request to `https://content.01-edu.org/api/auth/signin` instead of `https://01.gritlab.ax/api/auth/signin`, do you still get a CORS error?

I'm just trying to establish where the issue lies.

**Comment by lvisgrit** [comment]
Hi @davhojt, has this issue been fixed? We hope we can start the project today.

**Comment by davhojt** [comment]
@lvisgrit @danglam88 @mathisen99 
We're looking into that now. It is likely the preflight `OPTIONS` call by the browser that causes the issue. I.e. the `POST` request is not sent by the browser. We're working hard on a solution, and will contact you back shortly.

**Comment by mathisen99** [comment]
@davhojt  yes, it works fine with golang to get the token like this.

```go
package main

import (
    "bytes"
    "encoding/base64"
    "errors"
    "fmt"
    "io/ioutil"
    "net/http"
)

type LoginCredentials struct {
    Username string `json:"username"`
    Password string `json:"password"`
}

func encodeCredentials(credentials LoginCredentials) string {
    credStr := fmt.Sprintf("%s:%s", credentials.Username, credentials.Password)
    return base64.StdEncoding.EncodeToString([]byte(credStr))
}

func signin(credentials LoginCredentials) (string, error) {
    client := &http.Client{}

    data := bytes.NewBuffer([]byte{})
    req, err := http.NewRequest("POST", "https://01.gritlab.ax/api/auth/signin", data)
    if err != nil {
        return "", err
    }

    encodedCredentials := encodeCredentials(credentials)
    req.Header.Set("Authorization", "Basic "+encodedCredentials)

    resp, err := client.Do(req)
    if err != nil {
        return "", err
    }
    defer resp.Body.Close()

    if resp.StatusCode != http.StatusOK {
        body, _ := ioutil.ReadAll(resp.Body)
        return "", errors.New(string(body))
    }

    token, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        return "", err
    }

    fmt.Println("Token:", string(token))
    return string(token), nil
}

func main() {
    // Replace with your credentials
    credentials := LoginCredentials{
        Username: "YOUR_USERNAME",
        Password: "YOUR_PASSWORD",
    }

    jwt, err := signin(credentials)
    if err != nil {
        fmt.Println("Error logging in:", err)
        return
    }
    fmt.Println("JWT obtained:", jwt)
}
`````

**Comment by danglam88** [comment]
@davhojt  We’ve managed to make our codes working with the current setup. Hence, please don’t fix anything more from now on. We don’t want to start our projects from scratch again after your fixes. You can leave everything as it is right now, please! Thanks very much for your time and effort on this. We really appreciate it!

**Comment by MalekLahbib** [comment]
> 

hello, how did you do to make your code working? is it using javascript? can you share the solution please?

**Comment by danglam88** [comment]
@MalekLahbib  Yes, my code is still mostly in JavaScript, except for the token part which has been done in Go exactly as in the comment of mathisen99 above. After having the token, I set the browser cookie value to the token value and continue with the graphql queries normally using JavaScript. Note that you must set the following header whenever you make a fetch to the graphql API endpoint: **"Authorization": `Bearer ${token}`** with ${token} as the token value.

**Comment by MalekLahbib** [comment]
@davhojt is the site https://zone01normandie.org/ for example using the same api for authentication and JWToken as  us?

**Comment by davhojt** [comment]
Browsers make a "preflight" request with an `OPTIONS` HTTP method, before the actual desired call (`POST`, `GET`...) is made. Reason: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS.

The headers which relate to CORS were handled in the desired call, but not in the `OPTIONS` call. We've fixed that, and are testing it now ahead of releasing the fix.

**Comment by davhojt** [comment]
The CORS error related to `OPTIONS` HTTP requests has been resolved.
