### ISSUE TITLE
graphql subject

### ISSUE THREAD

**Issue by danglam88** [01-edu/public#1922]
graphql
---
The GraphQL API endpoint https://01.gritlab.ax/api/graphql-engine/v1/graphql cannot be accessed anymore even within the school internal network. Do you have any ideas what went wrong and how long does it take to fix this? I'm in the middle of doing the GraphQL project and this totally screwed up my plan to finish it...

**Comment by davhojt** [comment]
Hey @danglam88.
I've written a description here: https://github.com/01-edu/public/issues/1921#issuecomment-1491639917.
