### ISSUE TITLE
wget subject [language choice]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1939]
wget
---
Hi, is our interface (kood johvi)
the language icon say "open"
but then it is written :
"This project objective consists on recreating some functionalities of [wget](https://www.gnu.org/software/wget/manual/wget.html) using Go."

**Comment by mikysett** [comment]
Thanks a lot for spotting this inconsistency.
The project is meant to be done in any compiled project, I've made a PR to make it clear in the subject.
