### ISSUE TITLE
stock-exchange-sim subject [language choice]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1940]
stock-exchange-sim
---
upfront icon indicate it can be done in any language "open"
but I have seen it being contradict in the instructions of some others exercises.  (wget)
if this one we do  actually have choice , could it be formulated explicitly  ?
(go commands are mentioned as example so ...)

**Comment by mikysett** [comment]
Thanks for this feedback too, I've added more clarity to it in a PR ;)
