### ISSUE TITLE
get subject

### ISSUE THREAD

**Issue by timootsing** [01-edu/public#1959]
get
---
Having trouble making sense of this.

https://github.com/01-edu/public/blob/master/js/tests/get_test.js
line 17 aka test #7. Are there missing parenthesis on the 't.toString' part?

**Comment by nprimo** [comment]
Hi @timootsing, thank you for your feedback.

Besides the tests, is there anything that we could improve in the subject to make it clearer what is required from this exercise? :)
The subject should be exhaustive enough for you to be able to submit a solution that can pass the tests without seeing the tests directly.
