### ISSUE TITLE
using-map subject [weird result fahrenheit]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1964]
using-map : fahrenheitToCelsius()
---
using straightforward formula provide different results than the one expected by the tester (looks like rounding issue).
between internet and the tester I would be tempted to think that the tester do something off.
can the formula be explicit in the instructions ?
![image](https://user-images.githubusercontent.com/43323333/232762998-145d0ae2-a1b8-4590-b3fc-1436a5f0c5de.png)

**Comment by fulverin** [comment]
Sounds like floor is used for the temperature instead of round, this is quite unconventional imho.
I would suggest to change it to specify it.

**Comment by nprimo** [comment]
Hi @fulverin! Thank you for your feedback.

In the [subject](https://github.com/01-edu/public/tree/master/subjects/using-map#fahrenheit-to-celsius), it is specified to "round down the result".

Is there anything else you think might improve the clarity of the subject?

**Comment by fulverin** [comment]
my very bad, I completely overlooked that.
