### ISSUE TITLE
using-filter subject [instructions wording]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1965]
using-filter
---
is :
filter1DistinctVowel: accepts an array of strings, and returns only those which contain distinct vowels (a,e,i,o,u). For example, "Alabama" contains only 1 distinct vowel "a".
should be : 
filter1DistinctVowel: accepts an array of strings, and returns only those which contain **ONLY 1** distinct **vowel(s)** (a,e,i,o,u). For example, "Alabama" _is valid because it_ contains only 1 distinct vowel "a".

**Comment by mikysett** [comment]
Hello @fulverin and thanks a lot for your feedback!

We've added clarity to that part of the subject to avoid confusion ;)
