### ISSUE TITLE
sweet-curry subject (more precise instructions)

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1975]
sweet-curry
---

is : 
    mult2: that multiplies two numbers.
    add3: that adds three numbers.
    sub4: that subtracts four numbers.

could be : 
    mult2: that multiplies two numbers **_successively_**.
    add3: that adds three numbers **_successively_**.
    sub4: that subtracts four numbers **_successively_**.

that would give a chance to understand the expected behavior before first "fail commit feedback".

**Comment by nprimo** [comment]
Hi @fulverin, thank you for your feedback! I have added more information on the `sub4` functions (since for add and mult the order does not impact the result). Now, taking into consideration the provided link about `currying`, the subject should be clear enough :)
