### ISSUE TITLE
mobs subject

### ISSUE THREAD

**Issue by pbgo2** [01-edu/public#1976]
mobs
---trhis structure required in quest:
mobs/src/lib.rs, mobs/src/mobs.rs, mobs/src/mobs/ 

it produce issue modules conflict because you request mobs.rs and alss subfolder with same name. In such situation if i will drop both files into src/mobs subfolder (boss,rs and member,rs) together mod,rs what is required by rust module tree it will produce conflict widt src/mobs,rs Sort this because it confusing people and make quest no sortable consuming students valuable time to figtth with such nonsense

**Comment by nprimo** [comment]
Hi @pbgo2! Thank you for your feedback - I will add a `Notion` ([this one](https://doc.rust-lang.org/book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html)) to the subject to try to clarify how to achieve the expected result.

I hope this will help other people getting unstack :)
