### ISSUE TITLE
sortable subject {wording}

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1980]
sortable
---
alignement alignment
lost 45 minutes of my life on this
![image](https://user-images.githubusercontent.com/43323333/233805455-3d966e75-969f-4dd6-adbb-61a065e80e63.png)
![image](https://user-images.githubusercontent.com/43323333/233805465-98b7906b-28e3-497f-a15f-6cf9f3e4f47c.png)
could we get rid of the 'e' everywhere or keep it everywhere ? please

**Comment by davhojt** [comment]
That's fair enough @fulverin, cheers. My VSCode didn't like it either.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/22807573/235089737-5cb07277-b88a-4f9f-a58d-c3684599a0a2.png">
