### ISSUE TITLE
mouse-trap subject (precision)

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1981]
mouse-trap
---
would appreciate if you specify what you call "inside"
is only overlapping count ? 
I would suggest "entirely inside the box"
only way to check is to watch linked video in slow motion

**Comment by zanninso** [comment]
You are absolutely right that the video is not helpful enough, and I appreciate your suggestion to change the wording to 'entirely inside the box'. I have already opened a pull request to make this fix.
