### ISSUE TITLE
manipulate-entries subject

### ISSUE THREAD

**Issue by SgtGanjus** [01-edu/public#1982]
manipulate-entries
---
This function name shown below in the example is different to the one  task description.
"cartTotal: that will give you the right amount of calories, proteins... and all the other items in your grocery cart."
const groceriesCart = { orange: 500, oil: 20, sugar: 480 }

console.log('Total calories:')
console.log(totalCalories(groceriesCart))
console.log('Items with low carbs:')
console.log(lowCarbs(groceriesCart))
console.log('Total cart nutional facts:')
console.log(totalCart(groceriesCart))

**Comment by davhojt** [comment]
Thanks @SgtGanjus
