### ISSUE TITLE
manipulate-entries subject [error name last function    cartTotal !==totalCart ]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1984]
manipulate-entries
---
non consistent function name between instruction and suggested script to test:
instru:
_cartTotal: that will give you the right amount of calories, proteins... and all the other items in your grocery cart_

then :
_Here is a possible script to test your functions:_
...
```
console.log('Total cart nutional facts:')
console.log(totalCart(groceriesCart))
```

**Comment by mikysett** [comment]
Thanks a lot for your feedback.
This has been fixed two days ago already so I'll close the issue.

Have a nice one and good luck for the javascript piscine ;)
