### ISSUE TITLE
manipulate-entries subject [additional information needed]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1986]
manipulate-entries
---
that would be great to specify the type of the function to pass in functor

_Create 3 functions which work like the .filter, .map and .reduce array methods, but for the entries in the grocery cart.
    filterEntries: filters using both key and value.
    mapEntries: changes the key, the value or both.
    reduceEntries: reduces the entries._

nothing indicate that the first class functions have the type : 
`f([k,v])=>something`

`f(k,v)=>something`   // is as intuitive if not more imho

**Comment by fulverin** [comment]
> I think this little struggle it's part of the learning curve and helps to understand some nuances and certain aspects of a language.

well , no offense but you could also just do not write anything and justify it the same way.
I would expect at least the minimum details from something named "instructions".
when it comes to technical things from language, right you may just let student guess ;  
but this, sounds like arbitrary decision from tester coder. I do not see any learning into figuring out what arbitrary choice the coder made, especially learning it the hard way.

**Comment by mikysett** [comment]
No offense taken, quite the opposite, feedback is very useful to us and helps improve the experience of learners, which is the ultimate goal here :)

I've dropped a few more details for the prototypes specifications, now they looks like this:
```
- `filterEntries`: filters using both key and value, passed as an array (`[k, v]`).
- `mapEntries`: changes the key, the value or both, passed as an array (`[k, v]`).
- `reduceEntries`: reduces the entries passing keys and values as an array (`[k, v]`).
```
I hope this will help to focus on the interesting part of the exercise.

Feel free to leave me a comment if you feel there is still room for improvement.

In the meanwhile thanks again and have a nice one ;)

**Comment by fulverin** [comment]
thanks, I am sure next ones will appreciate
