### ISSUE TITLE
manipulate-entries subject description

### ISSUE THREAD

**Issue by kretesaak** [01-edu/public#1990]
manipulate-entries
---

The lowCarbs function description needs some clarification. I suggest using something like: "lowCarbs: that leaves only those items which have the total amount of carbs lower than 50".

Also, the cartTotal function could be clarified. I suggest using something like: "cartTotal: that will give you the total amount of calories, proteins and other nutritional values for each item in your grocery cart."

And maybe the expected precision of the numbers (how many places after comma) could also be specified.

**Comment by mikysett** [comment]
Thanks a lot for taking the time to suggest those improvement.

A pull request is on its way to apply your suggestions. The only one I don't feel necessary is the last one about the precision, this info is already given away in the `Usage` part and can be easily inferred.
