### ISSUE TITLE
interpolation subject

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1992]
interpolation
---
Hi,
instead of all that weird writing , could it be written 2 or 3 examples like :
when 
interpolation(step, start, end, callback,duration)
for ex
interpolation(2, [0,1], [2,3], ([x,y])=>([y,x+2]),3000) // assuming that s the expected form
it gives
[0,1]...
instead of vague things like points and then distance, point, t, x, y ...
it doesn't sound intuitive or mathematical.

_please let's just say what go in and what should go out. (and when indeed)_

**Comment by zanninso** [comment]
Hello 

The goal from this exercise is to know when and how to use setTimeout & setInterval, and the weird writing showed you when you have to done the calls to the callback and with which coordinate.
we can translate the graph in the subject to something  like that:
at time 2 perform  callback([0, 0.2])
at time 4 perform  callback([0.2, 0.4])
at time 6 perform  callback([0.4, 0.6])
at time 8 perform  callback([0.6, 0.8])
at time 10 perform  callback([0.8, 10])

I hope this clarify to you what should be done and if still there something not clear in that please let me know

**Comment by fulverin** [comment]
> at time 2 perform callback([0, 0.2])
> at time 4 perform callback([0.2, 0.4])
> at time 6 perform callback([0.4, 0.6])
> at time 8 perform callback([0.6, 0.8])
> at time 10 perform callback([0.8, 10])

thanks this is more informative than all the text and graph altogether
I can only talk for myself but I wish it would be that way for all tasks

**Comment by zanninso** [comment]
Sounds great, we are here for that.
while you got it so i will close this issue
