### ISSUE TITLE
JS-piscine - suggestion - introduce JS REPL at the beginning instead

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1999]
Hi , no big deal here but I wanted to share a feedback.
short : node's REPL is useful tool , if you introduce it to students , it could be at the very beginning of the piscine ? it helped me way before we reach node (our last quest)

long :
Well so far I just assumed that,  documenting ourselves about JS tools like REPL / CLI interactive  (`$ node` in terminal ) , 
was our business/responsibility.
so I looked into it at the very beginning of the piscine, and it helped me a lot for all quests.

but I see it is introduced in the node quest.
I know that each school may modify piscine's quest order, but if the standard way is having node at the end I think it would make sense to introduce the REPL tool as soon as possible.

the node REPL introduction I am talking about :
https://youtu.be/s-Wdiv95x5c?list=PLHyAJ_GrRtf8xk2lYyryPRvl4yE5AxZn6

---

**Comment by fulverin** [comment]
Hi @nprimo , well it is a good question. I probably missed that part when I was at that stage.
Anyway, I would simply include the video in that page (how-2-js).
https://youtu.be/s-Wdiv95x5c?list=PLHyAJ_GrRtf8xk2lYyryPRvl4yE5AxZn6
Deno definitely worth mentioning but I hardly see a student going exhaustively into all `deno `features,
identifying the `repl `feature as a useful one among all the others ones that are just noise at that stage imho 
(I tried to use typescript for the piscine, really bad idea).
Including the video mentioned just do the job I think.

The underlying question it brings me is ... is the piscine designed so we can start it as a pure noob or is it something we are expected to prepare ? 
I know that student have the last word about how to approach any task. but if that design decision exist,
making it clear would help us sharing better feedback _and making better study too_.

**Comment by nprimo** [comment]
Hi @fulverin, I will close this issue for the moment, but we will consider and see the best way to deploy this suggested improvement.
