### ISSUE TITLE
pick-and-click subject [precision]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2001]
pick-and-click
---
the axes,
it is unclear if it exists and we need to select it
or if we need to create it.

> Two SVG lines with ids axisX and axisY will need to follow the cursor, like really long cross hairs.
> 
>     the axisX attributes x1 and x2 need to be set to the X position of the cursor.
>     the axisY attributes y1 and y2 need to be set to the Y position of the cursor.

**Comment by fulverin** [comment]
same for all others

**Comment by nprimo** [comment]
Hi @fulverin, thank you for your feedback! 
The subject does not state directly if the SVG axes already exist or need to be created, but since the `pick-and-click.html` file is provided it is possible to find out that information quite easily :)
