### ISSUE TITLE
cl-camp4 subject

### ISSUE THREAD

**Issue by moomle0000** [01-edu/public#2017]
cl-camp4
---

"someone familiar"

Create a file myfamily.sh, which will show a subject's family (key: relatives).

The quotes have to be removed.

The subject will be decided depending on his ID which will be contained in the environment variable HERO_ID.

Where to look : https://learn.reboot01.com/assets/superhero/all.json

What to use : curl, jq and others...

Usage
$ export HERO_ID=1
$ ./myfamily.sh
Marlo Chandler-Jones (wife); Polly (aunt); Mrs. Chandler (mother-in-law); Keith Chandler, Ray Chandler, three unidentified others (brothers-in-law); unidentified father (deceased); Jackie Shorr (alleged mother; unconfirmed)
$

curl -s https://learn.reboot01.com/assets/superhero/all.json | jq '.[] | select(.id == '$HERO_ID') | .connections.relatives' -r

I think it's true
I don't know what's wrong ؟؟؟

**Comment by nprimo** [comment]
Hi @moomle0000, could you please confirm if the following is the solution you're testing?

```sh
curl -s https://learn.reboot01.com/assets/superhero/all.json | jq '.[] | select(.id == '$HERO_ID') | .connections.relatives' -r
```

You haven't shared with us the error you're receiving from trying to submit this solution, but I can see you might have to review [how quotes work in bash](https://www.gnu.org/software/bash/manual/bash.html#Quoting) (if the solution is the one I shared above)

**Comment by davhojt** [comment]
I'm guessing that @moomle0000 has moved past the issue they had.

@moomle0000 open a new issue if you need to.
