### ISSUE TITLE
kahoot (mobile-dev) audit questions wrong

### ISSUE THREAD

**Issue by leonard-ladva** [01-edu/public#2032]
**[Kahoot's](https://github.com/01-edu/public/tree/master/subjects/mobile-dev/kahoot)** audit questions seem fine until question number 3: 
`Try loggin in. Can you authenticate via gmail?`
but after that, questions seem to be for the [chess](https://github.com/01-edu/public/tree/master/subjects/mobile-dev/chess) task. 

For example:
`Try doing illegal moves, i.e. moving pawn 3 squares up, castling after moving the king, moving rook diagonally, etc. Does the app prevent such illegal moves?`

**Comment by MSilva95** [comment]
Hello @leonard-ladva thanks for the info! 
You can take a look at the new fixes for the project on the pr linked here.
It will soon be merged!
