### ISSUE TITLE
graphql subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2034]
graphql
---

What exactly is expected by this audit question?
> [Did the student generated their own GraphiQL?](https://github.com/01-edu/public/tree/master/subjects/graphql/audit#did-the-student-generated-their-own-graphiql)

The task description already contains a link to a perfectly working GraphiQL implementation. Why would a student "generate their own GraphiQL"?
> If you're logged in to the platform, you may access [GraphiQL](https://((domain))/graphiql/) to more easily explore the schema.

**Comment by MSilva95** [comment]
Hello @jarmo-seljamaa!
As you can see in the audit that is a BONUS question.
So it is up to the student to decide if he wants or not to generate his own GraphiQL. 
Feel free to reopen this issue is you find any problem, thank you for the feedback!
