### ISSUE TITLE
basicatoi subject

### ISSUE THREAD

**Issue by IngmarMotsmees** [01-edu/public#2038]
basicatoi
---
as per the exercise instructions : "Atoi returns 0 if the string is not considered as a valid number. For this exercise only valid string will be tested. **They will only contain one or several digits as characters."**

the tester runs piscine.BasicAtoi("") which goes against what the instructions say; i am disappointed

**Comment by mikysett** [comment]
Hello Ingmar!

Thanks a lot for reporting this issue, I've fixed it by removing this edge case in the tests.

Have a nice one and good luck with the piscine :)
