### ISSUE TITLE
reversemenuindex subject

### ISSUE THREAD

**Issue by el7ommed** [01-edu/public#2047]
reversemenuindex
---

func ReverseMenuIndex(menu []string) []string {
	var reversed []string = menu
	for i, j := 0, len(reversed)-1; i < j; i, j = i+1, j-1 {
		reversed[i], reversed[j] = reversed[j], reversed[i]
	}
	return reversed
}

---

My code works just fine locally and it actually reverses the order of the array, but it doesn't work on the tester

---

Error: Already failed code at commit 1d9ff18

Previous output:
ReverseMenuIndex([]string{"starters", "drinks", "mains", "desserts"}) == []string{"starters", "drinks", "mains", "desserts"} instead of []string{"desserts", "mains", "drinks", "starters"}
exit status 1

**Comment by mikysett** [comment]
Hello @el7ommed 

Thanks a lot for reaching us and sharing your code.

Actually your solution have a quite common but hard to catch bug. Many modern programming languages and frameworks do advertise a lot just about not making those bugs possible.

Here is a tip to try and understand what's happening:
In your tests try to put the string array into a variable, then call your function on this same array twice or more during the same execution cycle. Why the results are different each time? What is happening?

I hope you'll stop reading here and try to find the cause of the issue.

Now let's go straight to the point:
What you are doing is called a shallow copy, which means you are only passing a reference to the argument and you are changing the argument in-place.
What you would like to do instead is a deep copy, so you will operate on a completely new array (which has its own space in memory) and leave the arguments unchanged.

PS: Those questions are complicated for new starters but very interesting. Every language try to solve those problems in their own way. Immutability principle and pure functional programming languages are a nice place to look into.

**Comment by el7ommed** [comment]
Oh, so that's why make() was allowed in this exercise, I thought it was a bug with the tester

Thanks a lot
