### ISSUE TITLE
bloody-sunday subject

### ISSUE THREAD

**Issue by nadiatiteuf** [01-edu/public#2052]
bloody-sunday
---
![Capture d’écran du 2023-06-13 16-22-26](https://github.com/01-edu/public/assets/56796592/ec4b4834-9f7b-4c1f-9695-3c769f6ed3bf)
our exercise title is not displayed. we get an error message as in the screenshot.

**Comment by davhojt** [comment]
@freeworldwhoo The name of this exercise was changed to `sunny-sunday`.

**Comment by freeworldwhoo** [comment]
hello @nadiatiteuf the issue now is solved
