### ISSUE TITLE
ascii-art-web subject

### ISSUE THREAD

**Issue by SSMM0498** [01-edu/public#2059]
ascii-art-web
---
Hi, I haven't understood those questions:

- Is the communication between [server and client](https://www.geeksforgeeks.org/client-server-model/) well established?
- Does the project run using an API?

**Comment by mathisen99** [comment]
"Is the communication between server and client well established?" can be defined as:
"Can the computer that is trying to get information (the 'client') and the computer that has the information (the 'server') talk to each other without any problems?" do you get error codes for example like 400/500 codes in the inspector console or server prints.
------------------------------------------------------------------------------------------------
"Does the project run using an API?" could be simplified as:
"Does this project utilize a set of predefined operations or functions (an 'API') that allow it to interact with another software program or service, without needing to know all the details of how that software or service works?"

**Comment by SSMM0498** [comment]
I get you right for the first answer but the second one is still confused for me.
