### ISSUE TITLE
my-ls-1 subject

### ISSUE THREAD

**Issue by Yackzi** [01-edu/public#2090]
my-ls-1
---
are we allowed to use os/exec for the project, as several of us find the project too simple with os/exec?

**Comment by mathisen99** [comment]
you just fooling yourself if you make it run the real ls command with exec. 
the hole point of the exercise is to learn about file manipulation/reading/filesystem and so on. 

that said there is multiple ways to "go around the rules" for this one but if you sit down and think on it you will realize you missing out on information you wanted later on.

have great day!

**Comment by davhojt** [comment]
Hey @Yackzi.

Thank you for your question.

No, `os/exec` must not be used. The purpose like @mathisen99 said is to learn about the file system. Using `os/exec` drastically shortcuts that learning outcome. We'll take a look at the subject to make it more clear.
