### ISSUE TITLE
Add confirmation before deletion or remove delete option

### ISSUE THREAD

**Issue by bde-maze** [01-edu/public#21]
In TOAD Admin, add confirmation or remove delete option.
![delete-user](https://user-images.githubusercontent.com/15313830/56032633-944b3380-5d1a-11e9-8926-76f79749f1ce.gif)

**Comment by lfoussat** [comment]
we'll remove this feature, it's just for tests. so I change prio to low

**Comment by MarieMalarme** [comment]
We need this feature on the whole Admin (for deleting objects / object attributes / object child / users / roles / permissions)
