### ISSUE TITLE
my-ls-1 subject

### ISSUE THREAD

**Issue by SSMM0498** [01-edu/public#2101]
my-ls-1
---
Hi, on our implementation we use the package unsafe that are not allowed to calculate the terminal size.
I think it's not possible to calculate the terminal size to align correctly the columns:
Here is our function:
```golang
func GetTerminalWidth() int {
	winsize := struct {
		Row    uint16
		Col    uint16
		Xpixel uint16
		Ypixel uint16
	}{}
	_, _, _ = syscall.Syscall(
		syscall.SYS_IOCTL,
		uintptr(syscall.Stdout),
		uintptr(syscall.TIOCGWINSZ),
		uintptr(unsafe.Pointer(&winsize)),
	)

	return int(winsize.Col)
}
```

**Comment by nprimo** [comment]
Hi @SSMM0498, the package `fmt` should be enough to achieve what it is required in the subject and tested in the audit :)
