### ISSUE TITLE
passive subject // impossible audit question

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2106]
Last question in `cybersecurity` module task `passive`:
> [If the result.txt file already exists, does the program overwrite the result file, or is a new file created?](https://github.com/01-edu/public/tree/master/subjects/cybersecurity/passive/audit#if-the-resulttxt-file-already-exists-does-the-program-overwrite-the-result-file-or-is-a-new-file-created)

The audit provides only Yes/No answers, so the question cannot include 'this or that' as both cannot be true.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa thank you for reporting this! :)
