### ISSUE TITLE
Broken links in mobile developmets chess and kaquiz subjects

### ISSUE THREAD

**Issue by Laura-Eliise** [01-edu/public#2108]
chess
---
The chess repository does not have a description. Propose a change button also redirect to a 404 page.
![Screenshot from 2023-07-31 16-23-59](https://github.com/01-edu/public/assets/92638573/e7e2eb60-fb6f-4437-84b9-9be0d283c458)
![Screenshot from 2023-07-31 16-25-43](https://github.com/01-edu/public/assets/92638573/6844f818-6d12-4718-9849-a2aafc5a0629)

**Comment by Laura-Eliise** [comment]
The same issue is in Kaquiz. Is Kahoot the project that should be linking to this description?

![Screenshot from 2023-07-31 16-27-17](https://github.com/01-edu/public/assets/92638573/f6b7b35e-2cc2-42a1-9742-ffe7222ff531)
![Screenshot from 2023-07-31 16-27-51](https://github.com/01-edu/public/assets/92638573/775d51c8-bb15-41da-a678-4cbe4cdbd7a5)

**Comment by Laura-Eliise** [comment]
Sorry accidentally closed the issue!

**Comment by Laura-Eliise** [comment]
Sorry accidentally closed the issue!

**Comment by nprimo** [comment]
Hi @Laura-Eliise, thank you for reporting this issue :) It seems to be a wrong configuration. We'll try to fix this as soon as possible

**Comment by nprimo** [comment]
Hi @Laura-Eliise, your school's administrators should have already fixed the issue or are working on this.
