### ISSUE TITLE
[FEATURE] Add React Native to Mobile Development branch

### ISSUE THREAD

**Issue by Laura-Eliise** [01-edu/public#2109]
**Description**
Flutter is a language that is not yet suitable for beginners. AI tools give outdated information and the documentation is not reader friendly. This creates a steep learning curve. On top of that, Flutter is not widely used in the job market and finding a junior position for this language is impossible. React native on the other hand has a robust community, great resources and is more widely used in the job market.

**Type**
⚙️ functionality

**Expected benefit**
More students would choose and complete the mobile development branch if React Native was an option. 

**Target audience**
Students would benefit from this feature.

**Describe the solution you'd like**
The 2 days of the mobile development sprint would have the students learn the basics of dart and React Native. All of the tasks in the sprint and branch would have the options of either Flutter or React Native.

**Comment by Laura-Eliise** [comment]
The idea for this feature change came from the fact that multiple students were put off from choosing Mobile development after seeing what Flutter development looked like. Those that are forced to choose mobile development as their specialization are also not happy with Flutter being their only choice.

**Comment by mikysett** [comment]
Hello @Laura-Eliise 

This suggestion is very on point :)
Actually we are already evaluating the possibility to make the last projects of this branch open, so learners can choose the framework/language they prefer.

This may take a while, so I've kept track of your feedback internally and I'll close this issue for now.

Thanks again for sharing, this really helps us improving the projects to better match your expectations and needs.

Have a nice one,
Michele
