### ISSUE TITLE
[BUG] Can't subimt Kaquiz/Kahoot audit

### ISSUE THREAD

**Issue by Laura-Eliise** [01-edu/public#2116]
Kaquiz audit questions link to the wrong file. We are unable to submit an audit because of this issue.
![Screenshot from 2023-08-07 13-33-52](https://github.com/01-edu/public/assets/92638573/a7da79a8-9d3f-4525-b598-2113c349b353)

**Comment by mikysett** [comment]
Thank you @Laura-Eliise for reporting this issue.

Since you already mentioned it [here](https://github.com/01-edu/public/issues/2108) I'll close this one.
