### ISSUE TITLE
[BUG] stock-market audit broken

### ISSUE THREAD

**Issue by leonard-ladva** [01-edu/public#2125]
**Describe the bug**
Stock market audit shows only "repo cloning" question correcly, the rest of the questions are in a long paragraph with no radio buttons. Submitting with only "repo cloning" question answered doesn't seem to change anything, audits still show as undone. 

**Severity**
⚠️ critical

**Type**
🖌️ ui

**Attachments**
![issue](https://github.com/01-edu/public/assets/65786723/27aab2b3-99ff-4bad-a4a9-214ff13ba263)

**Comment by nprimo** [comment]
Hi @leonard-ladva, please talk with your school administrators. It looks like it was a misconfiguration in the settings. It should be fixed now :)

**Comment by leonard-ladva** [comment]
Hi, thanks for reply. Everything is working as intended now.
