### ISSUE TITLE
firstrune subject

### ISSUE THREAD

**Issue by Mokiri** [01-edu/public#2133]
package piscine

func FirstRune(s string) rune {
	if len(s) > 0 {
		return []rune(s)[0]
	}
	return 0
}
Is the correct answer but it won't let me through

**Comment by nprimo** [comment]
HI @Mokiri, could you please share the error you're getting from the platform?

**Comment by nprimo** [comment]
Please, if you are still stacked, open a new ticket with the error you're getting from the platform :)

**Comment by nprimo** [comment]
Please, if you are still stacked, open a new ticket with the error you're getting from the platform :)
