### ISSUE TITLE
social-network subject [is the app database  server structure mandatory ?]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2135]
social-network
---
Hi ,
back end part says:
> This is typically divided into three major parts:
> - Server ...
> - App ...
> - Database ...

and App part says :

> The backend will consist, like said above, of an app containing all the backend logic. This logic will therefore have several middleware, for example: ...

One sentence suggest we could organize the project certain way the other one that we have to.

**Comment by fulverin** [comment]
and not to mention the migration part that says: 
student$ tree .

> backend
> ├── pkg
> │   ├── db
> │   │   ├── migrations
> │   │   │   └── sqlite
> │   │   │       ├── 000001_create_users_table.down.sql
> │   │   │       ├── 000001_create_users_table.up.sql
> │   │   │       ├── 000002_create_posts_table.down.sql
> │   │   │       └── 000002_create_posts_table.up.sql
> │   │   └── sqlite
> │   |       └── sqlite.go
> |     |
> |   └── ...other_pkgs.go
> |
> ── server.go

in the above example the db thing is under pkg and not on same level as server(.go)
Is the above supposed to be a go packages used by the server ? I believe that a"database util function pacakges" should be under App as I associate it with middlewares. but I would put migration scripts into database folder.

**Comment by fulverin** [comment]
Hi @nprimo in that case, if it is the way that makes sense for us, then I suggest changing the working
"The backend  **_will_** consist ..."
with 
"The backend **_may_** consist ... "

**Comment by nprimo** [comment]
@fulverin I don't see how this would improve the subject clarity :) To fulfil the project, you will need to program an app that, quoting the subject, that `...is the application running on the server that listens for requests, retrieves information from the database and sends responses. The server runs an app that contains all the logic about how to respond to various requests based on the HTTP or other types of protocols. Some of these handlers functions will be middleware. Middleware is any code that executes between the server receiving a request and sending a response.`

Something that might be confusing, and I might not have commented on before, is that the `server` is the physical machine where the code will run (in this case your PC), while the `web server` is the software, running on the machine, dealing with HTTP requests. 

Similarly, you will have to set up a `Database`, but your `backend` application (or in general your project) will need to be able to specify which structure/schema you're database will have: that's the reason of the suggested structure 

```console
backend
├── pkg
│   ├── db
│   │   ├── migrations
│   │   │   └── sqlite
│   │   │       ├── 000001_create_users_table.down.sql
│   │   │       ├── 000001_create_users_table.up.sql
│   │   │       ├── 000002_create_posts_table.down.sql
│   │   │       └── 000002_create_posts_table.up.sql
│   │   └── sqlite
│   |       └── sqlite.go
|    |
|   └── ...other_pkgs.go
```

Is this additional information helpful? If this is the case, which key information do you reckon is missing in the subject?

Thank you so much for your feedback in any case :)
