### ISSUE TITLE
CatInFile subject

### ISSUE THREAD

**Issue by BeornG** [01-edu/public#2139]
CatInFile
---

when running javac *.java -d build for the exerciserunner  i get these errors:

ExerciseRunner.java:9: error: cannot find symbol
        String fileContent = new String(Files.readAllBytes(Paths.get("output")));
                                        ^
  symbol:   variable Files
  location: class ExerciseRunner
ExerciseRunner.java:9: error: cannot find symbol
        String fileContent = new String(Files.readAllBytes(Paths.get("output")));
                                                           ^
  symbol:   variable Paths
  location: class ExerciseRunner
2 errors

Solution:
import java.nio.file.*; as well

**Comment by BeornG** [comment]
It would be a nice if there was some way to do all the test as well as its hard to know where the error is when you dont know the input.

**Comment by zanninso** [comment]
> ## CatInFile
> when running javac *.java -d build for the exerciserunner i get these errors:
> 
> ExerciseRunner.java:9: error: cannot find symbol String fileContent = new String(Files.readAllBytes(Paths.get("output"))); ^ symbol: variable Files location: class ExerciseRunner ExerciseRunner.java:9: error: cannot find symbol String fileContent = new String(Files.readAllBytes(Paths.get("output"))); ^ symbol: variable Paths location: class ExerciseRunner 2 errors
> 
> Solution: import java.nio.file.*; as well

Thank you for your help!! we will fix it asap

**Comment by zanninso** [comment]
> It would be a nice if there was some way to do all the test as well as its hard to know where the error is when you dont know the input.

I didn't really get what you mean can you explain more ?

**Comment by akhossanX** [comment]
> It would be a nice if there was some way to do all the test as well as its hard to know where the error is when you dont know the input.

The fact that we don't include all possible test cases in the exercise runner is done on purpose
To figure out all potential test inputs is left to you as an exercise, that is one of the pedagogical goals of the exercises
being able to thoroughly stress test your code against all possible scenarios.
