### ISSUE TITLE
expected_variable subject

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2155]
expected_variable
---
When runing the test on my code i get 

error: failed to get `edit_distance` as a dependency of package `expected_variable_test v0.1.0 (/jail/tests/expected_variable_test)`

Caused by:
  failed to load source for dependency `edit_distance`

Caused by:
  Unable to update /jail/solutions/edit_distance

Caused by:
  failed to read `/jail/solutions/edit_distance/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
  
  The code i have has pased for others

**Comment by nprimo** [comment]
Hi @sailordi! Have you already done the exercise `edit_distance`? If so, is the solution still present in your piscine repo in your Gitea?

**Comment by sailordi** [comment]
Yes i did edit_distance i had it in a diffrent folder than the main git folder. It worked after moving the project back to the main folder

**Comment by nprimo** [comment]
Happy you manged to solve the issue :)
