### ISSUE TITLE
expected_variable subject

### ISSUE THREAD

**Issue by ItsYaBoiJay** [01-edu/public#2156]
expected_variable
---
When runing the test on my code i get 

error: failed to get edit_distance as a dependency of package expected_variable_test v0.1.0 (/jail/tests/expected_variable_test)

Caused by:
  failed to load source for dependency edit_distance

Caused by:
  Unable to update /jail/solutions/edit_distance

Caused by:
  failed to read /jail/solutions/edit_distance/Cargo.toml

Caused by:
  No such file or directory (os error 2)

  The code i have has pased for others and their code does not pass for me either. And it's not the test of 01-edu that fails as it never even gets to that point.

I'd gladly and higly appreciate this to be addressed and fixed as soon as possible, as we are on on a quite short time frame, for each quest.

**Comment by nprimo** [comment]
@ItsYaBoiJay please check https://github.com/01-edu/public/issues/2155
