### ISSUE TITLE
pig_latin subject

### ISSUE THREAD

**Issue by Wegenfelt** [01-edu/public#2165]
pig_latin
---
Hello, the instructions are very unclear on the word "queen". according to the instructions, a few of us interpreted that you have to move "qu" to the end, but in the test and example only the "q" is moved  to the end.

**Comment by MSilva95** [comment]
Hello @Wegenfelt!
Thanks for the feedback, you are right there is a mistake in the examples given.
In the test we ask for the correct result as you can see here :
```
        assert_eq!(pig_latin(&String::from("queen")), "eenquay");
```
