### ISSUE TITLE
lem-in subject

### ISSUE THREAD

**Issue by goobric** [01-edu/public#2173]
lem-in
---
bullet 5
"A room can be linked to an infinite number of rooms and by as many tunnels as deemed necessary."

is very mis-leading and should be removed from the instructions.
The sentence can be interpreted as follows:
if there are 4 rooms(A,B,C, D), with room A as ##start, and room D as ##end, with L6 (6 ants); I can therefore create 6 tunnels between rooms A-D, and release all 6 ants at the same time, (no collision, as each ant travels through its own tunnel) and all 6 ants arrive at room D (##end) at the same time. This would then be the most efficient solution.

This method could be applied to any 'lem-in' example file.
![230907_lemin_instruction_error](https://github.com/01-edu/public/assets/23141638/c362d9e4-132b-4f0a-b691-d93d406ad707)

**Comment by fulverin** [comment]
there is ambiguity all over about :
- what are the rules of the tunnels-rooms definition (for input validation)
- what are the rule for finding the best paths (solving)

**Comment by mikysett** [comment]
@goobric and @fulverin thanks a lot for your feedbacks,

I've improved the definition of tunnels and rooms to avoid misinterpretation as suggested by @goobric 

For the two points of @fulverin:
You are right and those two aspects are not defined in an extensive and unambiguous way, those are though aspects the learners should figure out on their own (or together, having discussions and identifying the best approach).

Being too specific on those points will reduce greatly the challenge and take away the chance to improve fundamental skills for software engineers.

**Comment by goobric** [comment]
hi @mikysett merci beaucoup :-)
