### ISSUE TITLE
atm-management-system subject

### ISSUE THREAD

**Issue by dgthegeek** [01-edu/public#2175]
atm-management-system
---
For storing the data, according to the project instructions, we can use either text files or sqlite3 (bonus). But in the audit there a question to let you know if the student used text files or not, otherwise you can fail the the project. And i don't understand the point of using both sqlite3 and text files at the same time to store the same data.
Is it an error maybe ?

**Comment by MSilva95** [comment]
Hello @dgthegeek!
I will take a look at the question and get back to you!
Thank you for the feedback!
