### ISSUE TITLE
[BUG] Java Letsplay - EnableGlobalMethodSecurity deprecated

### ISSUE THREAD

**Issue by tvntvn13** [01-edu/public#2178]
## java-letsplay

The 'EnableGlobalMethodSecurity' annotation is [deprecated](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/method/configuration/EnableGlobalMethodSecurity.html) That one could be removed from the audit questions.

**Comment by danglam88** [comment]
@davhojt @zanninso Could you comment on this and do the necessary fixes in the audit questions as soon as you can? Thanks!
