### ISSUE TITLE
corewar subject

### ISSUE THREAD

**Issue by vechivar** [01-edu/public#2192]
There's a problem with the vm_ref program provided with the subject. I tried playing ameba vs ameba and noticed the CyclesToDie values doesn't evolve correctly. At first it decreases of 50 every step (as expected), but then it suddenly goes from 337 cycles to die to 3157 cycles to die. After that it decreases of 550 every step.

-> How to reproduce :
./asm_ref ameba.s (compile the ameba program)
./vm_ref ameba.cor ameba.cor | grep "Cycles to die" (see all the Cycles to die lines of the ouput)

-> Result :
In the attached file you can see that the cycles values don't match the indicated decreased values. I also included the filtered values with the differences.
[cyclesToDie.txt](https://github.com/01-edu/public/files/12598167/cyclesToDie.txt)

Edit : my bad, everything is working properly, issue can be deleted

**Comment by mikysett** [comment]
Hello @vechivar 

Thanks for taking the time to create an issue and thank you even more to take the time to update it since you found everything was ok.

Have a nice one :smile:
