### ISSUE TITLE
btreesearchitem subject

### ISSUE THREAD

**Issue by AESELVI** [01-edu/public#2194]
btreesearchitem
---  checked my code but this error continue

Expected parent value &{0xc0000cc210 0xc0000cc270 <nil> 04} instead of <nil>
exit status 1

**Comment by MSilva95** [comment]
Hello @AESELVI if you could provide the code it would be good. This can be your code that is not correct.

**Comment by montiee4l** [comment]
package piscine

func BTreeSearchItem(root *TreeNode, elem string) *TreeNode {
	if root == nil {
		return root
	}
	if elem < root.Data {
		return BTreeSearchItem(root.Left, elem)
	} else if elem > root.Data {
		return BTreeSearchItem(root.Right, elem)
	} else {
		return root
	}
}

**Comment by montiee4l** [comment]
i also have the same issue
