### ISSUE TITLE
cat subject

### ISSUE THREAD

**Issue by yuliannagarcia** [01-edu/public#2198]
cat
---
I get 

<img width="543" alt="image" src="https://github.com/01-edu/public/assets/129753422/e075c8b5-45ce-49a3-858d-a228008207a7">

<img width="543" alt="image" src="https://github.com/01-edu/public/assets/129753422/e075c8b5-45ce-49a3-858d-a228008207a7">

<img width="726" alt="image" src="https://github.com/01-edu/public/assets/129753422/3b8237b3-7c29-4b5b-8719-92e2eacf50b5">

<img width="503" alt="image" src="https://github.com/01-edu/public/assets/129753422/7e726b2e-f970-4eff-9bb8-52268ea7f7f1">

I asked others to help but the say everything is fine, it seems like an error with the 01 founders platform

my code 

package main

import (
	"io/ioutil"
	"os"

	"github.com/01-edu/z01"
)

func main() {
	if len(os.Args) >= 2 {
		for _, v := range os.Args[1:] {
			data, err := os.ReadFile(v)
			if err != nil {
				printStr("ERROR: " + err.Error() + "\n")
				os.Exit(1)
			}
			printStr(string(data))
		}
	} else if len(os.Args) == 1 {
		input, err := ioutil.ReadAll(os.Stdin)
		printStr(string(input))
		if err != nil {
			printStr("ERROR: " + err.Error() + "\n")
			os.Exit(1)
		}
	}
}

func printStr(s string) {
	for _, v := range s {
		z01.PrintRune(v)
	}
}

**Comment by mikysett** [comment]
Hello @yuliannagarcia 

Thanks a lot for your feedback.

I've tested your solution locally and indeed it seems to work properly.
As you pointed out in the screenshots it seems to be related to your git repo.

Can you double-check those possible issues on your Gitea repo:
- The path to the file is correct
- The name of the file is correct (no trailing spaces, uppercase characters, wrong extension)
- The file has the right permissions (try `ls -a` and check if it way more restrictive of other/working solutions, if yes modify it with `chmod` and push it again)

I hope we are in one of those scenarios, if not please provide more context (are other learners affected? Did you had the same issue elsewhere?)

In the meanwhile have a very nice day

**Comment by yuliannagarcia** [comment]
Thank you for getting back to me we’ve tried it all other people are trying
to help me with this error but they don’t know the problem we checked all
you said and it’s not it, still getting the same error code.

No one else is getting the error message

Even deleted it and re did it and it still happening

**Comment by mikysett** [comment]
I've seen also `quest8.txt` and `quest8T.txt` are in the expected files list for cat in the go piscine.
Can you confirm you pushed those files to your gitea repo?

**Comment by yuliannagarcia** [comment]
Hi yea Quest8.txt and Quest8T.txt are files there and they are pushed in my repo. Everything else is working I moved onto quest 9 today completed everything it’s not affected by this. Cat and it’s files do appear in my gitea repo that why whe are confused as to why it says it’s not found especially as I’ve ensured they are written as the question asks Sent from my iPhoneOn 19 Sep 2023, at 15:01, Michele ***@***.***> wrote:﻿
I've seen also quest8.txt and quest8T.txt are in the expected files list for cat in the go piscine.
Can you confirm you pushed those files to your gitea repo?

**Comment by yuliannagarcia** [comment]
I’ve been told to just leave it and move in as it’s an optional but I I wanted the points for it I guess but I mean if nothing can be done it’s fine just wanted to see what the issue wasSent from my iPhoneOn 19 Sep 2023, at 15:01, Michele ***@***.***> wrote:﻿
I've seen also quest8.txt and quest8T.txt are in the expected files list for cat in the go piscine.
Can you confirm you pushed those files to your gitea repo?

**Comment by mikysett** [comment]
I understand your feeling, also you were right to move to next quest since we didn't manage to fix that one in a short period of time.

In the meanwhile I was able to reproduce the error and I understand now better what's happening.
It seems to be related to some bad configuration in the requested files paths.

I'm working on a PR which will hopefully solve it.

Have a nice one and thanks again for your great help!
