### ISSUE TITLE
cat subject

### ISSUE THREAD

**Issue by 3li7alaki** [01-edu/public#2203]
cat
---
	stat : no such file or directory
Not using stat or anything close, the code works and have tried many codes that work but the test is bugged. Everyone in the selection pool is facing the same exact issue

**Comment by 3li7alaki** [comment]
20 hours till scope ends, hope this is resolved asap

**Comment by mikysett** [comment]
Hello @3li7alaki 

Thanks for the feedback.
Can I ask you to send me your solution so it will be easier to check.

**Comment by 3li7alaki** [comment]
package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	args := os.Args[1:]
	if 0 == len(args) {
		fmt.Print()
	} else {
		for _, s := range os.Args[1:] {
			file, err := os.Open(s)
			if err != nil {
				fmt.Println(err.Error())
				break
			} else {
				data, err := ioutil.ReadAll(file)
				if err != nil {
					fmt.Println(err.Error())
					break
				} else {
					fmt.Printf("%s", data)
				}
			}
		}
	}
}


Txt files are in place 
Everything is in place too

**Comment by 3li7alaki** [comment]
this was the last one I tried but my mentor told me to try many more and still same result

**Comment by mikysett** [comment]
I've finally was able to reproduce the issue and it seems related to some wrong paths for the expected files internally.

I'm working on a PR which should hopefully fix it, thanks once again for the precious help
