### ISSUE TITLE
guess-it-1 subject

### ISSUE THREAD

**Issue by akhaled01** [01-edu/public#2208]
guess-it-1
---
hey there, I have a newer version of node (20.2.0) and the server for testing is refusing to run, i checked my script multiple times but there is nothing wrong from my side.

**Comment by nprimo** [comment]
Hi @akhaled01! Could you please share more information about the error you're getting? Additionally, what do you mean by "the server for testing is refusing to run"? Do you mean you cannot run the test on the platform?

**Comment by nprimo** [comment]
HI @akhaled01, if you are facing the same issue, please open a new ticket :)
