### ISSUE TITLE
index-of subject

### ISSUE THREAD

**Issue by mohaskii** [01-edu/public#2209]
index-of
---
how you can explain this :
() => lastIndexOf([t, 0, 0, t], t, 2) === 0

**Comment by mikysett** [comment]
hello @mohaskii 

Thanks a lot for opening an issue.

Before I take a look into it may I ask you to give more context like:
- In which part of the curriculum does this exercise live
- Why you think the result is not the one it should be
- Which result you think should be the good one

Have a nice afternoon in the meanwhile ;)

**Comment by mikysett** [comment]
I'll close the issue since there is not enough info to take action.

Feel free to write back here and I'll be glad to reopen it :)
