### ISSUE TITLE
bloody-sunday subject

### ISSUE THREAD

**Issue by Pba23** [01-edu/public#2219]
bloody-sunday
---
error reading the markdown: This subject is under maintenance or is not ready yet, come back later

USAGE: https://learn.zone01dakar.sn/markdown/USER/REPO/FILE_PATH.md
Working example: https://learn.zone01dakar.sn/markdown/root/public/subjects/printalphabet/README.md

**Comment by MSilva95** [comment]
Hello @Pba23!
Is this still an issue or was it solved already?
This is due to the fact that the school has not updated the reference of this object, please contact your school's maintenance team to resolve this issue if it still persists.
