### ISSUE TITLE
buy-01 subject

### ISSUE THREAD

**Issue by danglam88** [01-edu/public#2229]
buy-01
---

The "Enhanced Database Design" section is broken, we cannot see any database design there. Could you please fix that?

Moreover, we think the logic for database design could be improved as follows:

1. There's an avatar field with type string in the User table. Does it mean avatarPath instead? Because avatar is an image and of course it cannot be of type string. Hence, you should either change it to "Binary avatar" or "String avatarPath" instead. We'd prefer it to be "Binary avatar" more.

2. If you decide to change to "Binary avatar", then you should also change "String imagePath" to "Binary image" in the Media table as well.

3. We think that the database design could be even further improved by removing the avatar field from the User table, then providing a 1->0..1 relationship (since a user might or might not have an avatar) between the User table and the Media table. This way we could use the Media table for the user avatar as well, and that means "String productId" in the Media table should be changed to "String productId/userId" instead.

We hope you'll make such fixes and improvements as soon as you can because now everything is very unclear for us about the database design and this blocks us from proceeding with the project.

Thanks for your consideration!

**Comment by danglam88** [comment]
@zanninso Could you please check this issue as soon as you can? Thanks!

**Comment by zanninso** [comment]
fixed
