### ISSUE TITLE
Filler BIG issue!

### ISSUE THREAD

**Issue by mathisen99** [01-edu/public#2231]
Hello we are doing filler at gritlab @ Paf / Åland and the docker image is not built for macs!! it made for x86_64 architect!!
so it is imposible for us to complete it on the school machines. 

if i create VM on a X86 machine it works fine please fix this issue.

thanks!!

**Comment by lvisgrit** [comment]
Hi @zamazzal, many students are getting blocked at grit:lab. Please help us check on this issue.

**Comment by zamazzal** [comment]
Hello @mathisen99,

Please provide us with more information so we can identify the source of the problem.

Kind regards,

**Comment by mathisen99** [comment]
ok. lets do this step by step.
first if we follow the instructions and build and run the image it will result in a broken pipe 

```
root@14792452975b:/filler# ./game_engine -f maps/map01 -p1 robots/bender -p2 robots/terminator
$$$ exec p1 : [robots/bender]
$$$ exec p2 : [robots/terminator]
Error sending data: write |1: broken pipe
Anfield 40 30:
    0123456789012345678901234567890123456789
000 ........................................
001 ........................................
002 ........................................
003 ....@...................................
004 ........................................
005 ........................................
006 ........................................
007 ........................................
008 ........................................
009 ........................................
010 ........................................
011 ........................................
012 ........................................
013 ........................................
014 ........................................
015 ........................................
016 ........................................
017 ........................................
018 ........................................
019 ........................................
020 ........................................
021 ........................................
022 ........................................
023 ........................................
024 ........................................
025 ........................................
026 ................................$.......
027 ........................................
028 ........................................
029 ........................................
Piece 4 4:
.OO.
OOOO
OOO.
OOO.
-> Answer (@): 
```

and then if we do a quick test and just run 
./robots/bender  
we will get this error 
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
and that error displays that it is using qemu with x86 architect.  
and YES! we have tried to build and run the image using —platform tag  to change to ARM but that wont work.
same if we turn on rosseta in docker we will get this error
```
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 Trace/breakpoint trap
 ```
 
 and if i do the same steps in a normal VM with x86 architect it has no issues at all.

**Comment by mathisen99** [comment]
Yes it working nicely! 
Thanks! this can now be closed. issue solved.
