### ISSUE TITLE
async-ex-11 subject

### ISSUE THREAD

**Issue by Bakarseck** [01-edu/public#2238]
async-ex-11
---error reading the markdown: This subject is under maintenance or is not ready yet, come back later

USAGE: https://learn.zone01dakar.sn/markdown/USER/REPO/FILE_PATH.md
Working example: https://learn.zone01dakar.sn/markdown/root/public/subjects/printalphabet/README.md 

The statement is missing

**Comment by MSilva95** [comment]
Hello @Bakarseck!
You should report this to an admin in your organization/school, as this exercise in specific is not our content.
