### ISSUE TITLE
[FEATURE]  Gitea

### ISSUE THREAD

**Issue by mathisen99** [01-edu/public#2239]
the 1mb size limit that we currently have when using gitea is just a non needed restriction. 
1mb is nothing in todays messures. and for example we want to turn in Filler now but the robots YOU provide is 3.9 mb in size. 
sure i can make a script that downloads them from a 3.rd party source but this feels so not needed and to compair to a " normal " dev enviroment this is bad really bad! i mean we have github with gitgub actions to compair aginst just that big thing is missing from a real dev job.

please do sometihng about this. the restriction is not making any sense for education purposes as they teach students to use git the wrong way.

thanks!

**Comment by nprimo** [comment]
Hi @mathisen99 thank you for pointing out this problem. 

It is never good practice to store big files in repos - the specific zip file is quite big since it contains a compiled version of the required executable for computers with Apple M1 chips: hopefully soon, we'll replace it with something lighter. 

About the limit, it is a "push" limit: it is limited since Gitea is hosted on your school server and not by a company's server like GitHub/Microsoft. 

I hope this clarifies the situation.

**Comment by mathisen99** [comment]
yes i understand your point but, and i know big files sizes and specaly binaries is bad practice to store on git repo. but 1mb is still pretty low. if you think about it. just make something "pretty" that uses sound files, images and so on. 
1mb will not be enough and i still argue that that is to low.

and i have a hard time beliving that the servers on prem on paf would have any issues with this. as even have seen and worked with them myself. so i really dont accept that answer :) no harm ment.

i will also still argue that a a switch to github would make way more sense to prep someone for the "real" world. like i mentioned earlier github actitions/workflows is a big part any dev pipeline.  i also understand why you dont want to do this as you want to protect the solusions from beeing "googled" but if you think about it most people have github repos anyway. and you can setup "comunities" with private repos also to avoid this.

the platform is maybe using some "API" calls to gitea for whatever reasons that i dont know, but if that is the case it is solveable and could be fixed in the feature.

**Comment by mathisen99** [comment]
@nprimo if you can give me the name of the person on paf that has told you to keep this restriciton i will talk to them myself. as i worked there myself. but maybe should keep names out of this thread so just give me a way to contact to you privately.

**Comment by nprimo** [comment]
Hi @mathisen99, this is not indeed a technical issue, whether a strategy to incentivize people not to push big files to gitea, I forgot to mention this before :)

About the tools you would like to use to develop, I do agree that GithubActions is a good CI/CD tool as many others you can find in the market. To develop your projects you're open to using any git hosting solution, the only things that should be submitted on your gitea repo are only the code solutions of the curriculum.
