### ISSUE TITLE
rot14 subject

### ISSUE THREAD

**Issue by alnshine** [01-edu/public#2242]
rot14
---
![3107469b-2273-4262-995e-bc6d9e398370](https://github.com/01-edu/public/assets/62517503/97005fa8-c48e-4b3b-9527-705745884d6f)

in the hackathon, if you log in via your phone, you can see the names of all tasks

**Comment by MSilva95** [comment]
Hello @alnshine!
Thank you for creating this issue, we replicated the issue here <https://01talent.atlassian.net/browse/SUP-806> so that the Dev team can take a look at it. For now i will close this issue, thank you for the feedback!
