### ISSUE TITLE
system-monitor audit

### ISSUE THREAD

**Issue by vechivar** [01-edu/public#2243]
Two questions on the audit of system monitor, about the process list on the memory tab, feel weird to me.

First :
Try and run the application, then use the filter to search for the process "monitor". Were you able to filter the table?
Try and run the command "top", then search for the process "monitor". Are the values from each column the same as in the command "top"?

Here we are supposed to compare the values of the monitor process on our own monitor and on the top command. But there is no way we can get the exact same values : 
- the cpu usage depends on how and when we calculate it. 
- the state field can't be the same either. When my own program reads its own state, it will necessarily be on a R state, just as running " top | grep ' top' " will always indicate that the top process is on a R state.

So this question on the audit really doesn't make sure that the process table is built properly.

Second :
Try and run the application, then select from the table three processes. Was it possible to select three processes?

I don't know what this is supposed to be. Are we supposed to find a search filter that only gives three results ? 

Thank you for reading this.

**Comment by nprimo** [comment]
Hi @vechivar, thank you for sharing with us your doubt :) 

About point 1, I am confused about your doubt: if you open both your monitoring program and let `top` run in your terminal the results (number of tasks, CPU usage, ... ) should be the same, am I missing something? 

About point 2, in the subject, it is stated (right on top of the second gif)
```
* Memory and process monitor, that will contain :
...
  - A text box that lets the user filter the table. Users must be able to select multiple rows of the table.
```
Therefore, using the program you should be able to select 3 (or any other type of number) of tasks (using the filter feature) and be able to monitor just those. The second gif shows a very quick filtering example :)

 I hope this clarifies your doubts :)

**Comment by vechivar** [comment]
About 2nd point, the filtering feature can only filter from the name of the processes (or from the pid if that matters). So trying to filter 3 processes feels kind of weird, like it means I should find some research that would only give 3 results. But maybe the idea is just to select a process from its name 3 times, rather than selecting three processes at once ?

For 1st point, I'm gonna try to explain what's on my mind.
- As I said, the state of my monitor process inside my monitor will always be R, because when my program is reading its own info on the /proc/pid/stat file, it's necessarily running. On the other hand, when I run top and filter my monitor program it's quite likely that top will say my monitor is S (sleeping).

- CPU usage is very subjective. For example, let's say I have a process that runs for 1 second every 10 seconds. If i choose to calculate my cpu usage on a 5 seconds time reference, my cpu usage will be 20% half the time (1 second usage over 5 seconds), and 0% the rest of the time (0 second usage over 5 seconds). If I calculate it every 10 seconds it will always be 10%, and any other choice of time reference will find a different value.

So I end up with a monitor program that looks different from the top command. I was able to explain to my auditors why it looks different, but my main concern is that I can't really know if I made a mistake in my program.

**Comment by nprimo** [comment]
About point 2:
- you can see filtering and selecting the process to monitor as two separate users - I am going to change the subject and split the two to make this point clearer.

About point 1: 
- I still don't understand well what is the issue: from the information you wrote down, it looks to me like you are well aware of which CPU usage and processes are displayed in your program :) If you can explain that and justify potential differences with `top` (or any other similar tool) during your audits it means you have learnt the project's topic, which, in the end, is the goal of developing this program. 

Hopefully, I clarified your doubts @vechivar. Thank you for the feedback :)
