### ISSUE TITLE
GetGoogleMapsUrl subject

### ISSUE THREAD

**Issue by 40TJG940** [01-edu/public#2248]
GetGoogleMapsUrl
---
Assert.AreEqual failed. Expected:<https://www.google.com/maps/place/Bordeaux+Ynov+Campus/@44.854186,-0.5663056,15z/>. Actual:<https://www.google.com/maps/place/Bordeaux%20Ynov%20Campus/@44.854186,-0.5663056,15z/>.

euh ! ...
la concaténation dans un lien de recherche se fait avec des "%20" , pas des "+" :

https://www.google.com/maps/place/Bordeaux%20Ynov%20Campus/@44.854186,-0.5663056,15z/>.

**Comment by nprimo** [comment]
Hi @40TJG940, please, talk to your school manager about this issue. This exercise is not part of our core curriculum (is not part of this repository)
