### ISSUE TITLE
corewar audit

### ISSUE THREAD

**Issue by vechivar** [01-edu/public#2251]
As I was preparing my audit for corewar, I noticed this question in the audit git : 

Run the VM using four players with the name starting with strong_* and the flag -d 40000.

But I can't find those strong players in the playground. I would enjoy some real players to test my program, because the player I made to beat ameba doesn't feel complex enough to really limit test my vm.

Thanks for your answer !

**Comment by nprimo** [comment]
Hi @vechivar, you're right. there are no `strong_*` players. 
This project aims to be able to develop the logic behind the assembler and the VM - try to come up with strong players yourself to test your VM compared to the reference one. 
To test the assembler you should have quite some extra cases to check.
