### ISSUE TITLE
cat subject

### ISSUE THREAD

**Issue by namagau** [01-edu/public#2253]
cat
---
Issue Title:
Cannot Push Completed Task "cat" - "No such file or directory" error

Issue Description:
I'm encountering a problem when trying to push a completed task (Quest 8 task called "CAT"). This issue is affecting not only me but also my classmates, and we've all followed the same steps, so it seems to be a common problem.
Expected Behavior:
I expected to be able to push the completed task without any issues.

Actual Behavior:

I receive the following error message when trying to push:

stat: no such file or directory

Additional Information:

    Operating System: [Linux]
    Programming Language (if relevant): [Go]
    GitHub Repository URL: [https://01.alem.school/git/]
    
    
    Task URL:https://01.alem.school/intra/alem/piscine-go/quest-08/cat?event=906
 
![Screenshot from 2023-10-17 22-20-13](https://github.com/01-edu/public/assets/148217228/d38ba58c-3ef6-49cd-9bae-cf9079497044)

    
![Screenshot from 2023-10-17 22-21-35](https://github.com/01-edu/public/assets/148217228/d3291d3a-c96b-4c31-8041-f8da70dbc095)

![Screenshot from 2023-10-17 22-22-56](https://github.com/01-edu/public/assets/148217228/9c92864b-728e-4322-b192-a6f8a704c3e9)

    
    here is my code 
    
    package main

import (
	"io"
	"io/ioutil"
	"os"

	"github.com/01-edu/z01"
)

func eZ(s string) {
	for _, v := range s {
		z01.PrintRune(v)
	}
}

func main() {
	args := os.Args[1:]
	if len(args) == 0 {
		// Read from standard input (stdin)
		io.Copy(os.Stdout, os.Stdin)
	} else {
		for _, v := range args {

			fileName := v
			fileContent, err := ioutil.ReadFile(fileName)
			if err != nil {
				eZ(string("ERROR: open " + fileName + ": no such file or directory\n"))
				os.Exit(1)
				return
			}
			eZ(string(fileContent))

		}
	}
}

Notes:

    This issue has been encountered by all my classmates.
    We have reviewed our code and file structure, and it appears to be correct.
    We've pushed and submitted all necessary files "cat/main.go, quest8.txt, quest8T.txt" inside the cat folder and outside it also, tried different ways
    I've read a previous cat issues and tried to give a permission using chmod +x 
    I've tried to delete folder multiple times and  tried to push different codes , still we all have the same issue .
    We suspect there might be an issue with the repository configuration.
    
 Any help or guidance on resolving this issue would be greatly appreciated. 
 We only have 20 hour left to submit this assignment.

**Comment by MSilva95** [comment]
Hello @namagau the issue was solved here <https://01talent.atlassian.net/browse/SUP-804>
The school didn't have the exercise updated. Thanks for the report.

**Comment by namagau** [comment]
I understand, and I'm glad the problem has been resolved. Thank you for the information.
