### ISSUE TITLE
boxing_todo subject

### ISSUE THREAD

**Issue by jimmy7294** [01-edu/public#2255]
boxing_todo
---
Punctuation of the task description vs. test code causes the correct function to fail.
# Task
For each data structure, you will have to implement a function called fmt for the Display trait. It should write the message "**Fail to parse todo**" in the case of any parsing error. Otherwise, it should write the message "Fail to read todo file".

# Test code:
    #[test]
    fn test_empty_tasks() {
        let result = run(
            object! {
            "title" : "empty tasks",
            "tasks": []},
            "empty_tasks.json",
        )
        .unwrap_err();

        assert_eq!(result.to_string(), "**Fail to parses todo**");
        assert!(result.source().is_none());
    }

**Comment by MSilva95** [comment]
Thank you @jimmy7294 i will do the change!

**Comment by MSilva95** [comment]
<https://github.com/01-edu/rust-tests/pull/138>
