### ISSUE TITLE
athlete-keep-hydrated subject - "Read all the scripts very carefully."

### ISSUE THREAD

**Issue by blueskiy01** [01-edu/public#2257]
athlete-keep-hydrated
---
Hello. 
<img width="2197" alt="Screenshot 2023-10-18 at 14 43 39" src="https://github.com/01-edu/public/assets/122779689/5657d70f-6fe0-4613-8a70-dc8bcf599065">

In this first task, regarding the interview scripts I can't seem to find it anywhere in the task. However, it is present here in the public repo : https://github.com/01-edu/public/tree/master/subjects/user-experience/piscine-ux/athlete-keep-hydrated/user-interviews .

**Comment by MSilva95** [comment]
I have added the links in the subject, thank you for the feedback!
