### ISSUE TITLE
file-researcher subject

### ISSUE THREAD

**Issue by hemo200** [01-edu/public#2264]
In file-researcher file. The students are required to perform grep command over a text file. I have noticed that the file "facts.txt" is missing and nowhere to be found. Hence, I would like to confirm if the file is supposed to be provided.

**Comment by MSilva95** [comment]
Hello @hemo200!
The file does not need to be provided in the exercise, only the path. If you feel like you need a file to test your function you can create it on your machine.
Thank you for the feedback!
