### ISSUE TITLE
using-reduce subject

### ISSUE THREAD

**Issue by khiboulAllAH** [01-edu/public#2268]
using-reduce
---in the last function funcExec we ask us a value but it's not declared in the subject .

**Comment by MSilva95** [comment]
Hello @khiboulAllAH!
Can you elaborate and provide the example, I'm not understanding the problem.

**Comment by khiboulAllAH** [comment]
Hello I was talking about exercise 3 of quest5 the 3rd function i.e.
funcExec once having created the function when I submit the test tells me
that the number is NaN i.e. the initialvalue that I I hadn't declared but I
saw that it was me who had made a mistake. Sorry to have disturbed
