### ISSUE TITLE
mini-framework specifications : audit questions VS todoMVC specs ?

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2275]
Hi,
I think it would be helpful to be more specific about the exigences :

> A todoMVC project consists of creating a [webpage](http://todomvc.com/examples/vanillajs/) (this example is written in VanillaJS) with the same elements present in the example, so we advise you to test it around first. You have to make your todoMVC project, a pretty much perfect copy of the examples given in the links above, but using your framework.

"***a pretty much perfect copy***"

According to the above, if I am thorough I will reproduce every functionalities, especially the one listed here:
https://github.com/tastejs/todomvc/blob/master/app-spec.md

but if only look at audit questions then I can just copy the provided css and only provide the basic (~3 times less work).

Can you be more explicit between audit's spec and todoMVC git's specs ?

**Comment by nprimo** [comment]
Hi @fulverin, thank you for your feedback. As far as I can see [here](https://github.com/tastejs/todomvc/blob/master/app-spec.md#functionality), all the listed features are required (from a high-level perspective) to pass the audit. Could you clarify which of the features or specs listed is creating confusion and why?

**Comment by fulverin** [comment]
Hi @nprimo , 
well , what do you call "*high-level perspective*" ?
there is many little things in the [todoMVC specs](https://github.com/tastejs/todomvc/blob/master/app-spec.md#functionality) that are just cosmetic details but are challenging to implement in a clean way.
For example:

> Clear completed button
> Removes completed todos when clicked. Should be hidden when there are no completed todo

***Should be hidden when there are no completed todo***
This is little one among many that can make a big difference; but is not mentioned in audit questions.

If we do not have to satisfy those points, I suggest to "relax" the "***a pretty much perfect copy***".
I' d suggest something like:  "***a functional copy***".

**Comment by nprimo** [comment]
Hi @fulverin, I understand what you're saying, but I still find the subject/audit "fair" and quite clear. For the specific case you mentioned, there is a specific question in the audit about the `Clear Completed` button, for example. I can see that for some other cases it might not be as clear what should be implemented and what not: at the same time you have access to the audit of the project so it is possible to clarify some doubts by reading it.

I will rephrase the subject as you suggested: I hope it will help future learners to have a better perspective on what it is supposed to be achieved :)
