### ISSUE TITLE
Ray tracing documentation unclear in basic requirement vs bonus requirements

### ISSUE THREAD

**Issue by jo-eman** [01-edu/public#2280]
**Describe the bug**
In Ray Tracing(https://github.com/01-edu/public/blob/master/subjects/rt/) instructions it is say the project should be able to recreate this image which contains reflective+refractive sphere:
https://github.com/01-edu/public/blob/master/subjects/rt/raytrace.png

However in objectives for the project it's mentioned "implement simple light management, which includes: different brightness and shadows."

The bonus requirements it's mentioned:
As bonus for this project you can implement:

Textures to the surfaces of the objects
Reflection and refraction effects on the objects (make them shiny or reflective)

In the audit it is also mentioned under bonus section:
"Is it possible to make reflective or refractive objects"

It is unclear if reflective+refractive objects is required for passing basic audit or only needed for bonus.

**Users**
All doing rust https://github.com/01-edu/public/blob/master/subjects/rt/

**Severity**
(❗️minor)

**Type**
(🗂️ documentation)

**To Reproduce**

read https://github.com/01-edu/public/blob/master/subjects/rt/

**Workarounds**
Any known workarounds for the issue:

**Expected behavior**
More clear instructions or example of what basic project without bonus should create

**Attachments**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nprimo** [comment]
HI @jo-eman, thank you for the feedback. I will add some extra details on the subject to clarify this point to avoid confusion
