### ISSUE TITLE
alphacount subject

### ISSUE THREAD

**Issue by SyntaxError-Izzy** [01-edu/public#2281]
alphacount
---
While it's not strictly required for this task, you are allowed to use the "github.com/01-edu/z01" package. However, be cautious, as its usage could potentially result in confusion or mistakes.

**Comment by nprimo** [comment]
Hi @SyntaxError-Izzy, thank you for your feedback!
Being allowed to use a function does not assume you should use it ;)

**Comment by SyntaxError-Izzy** [comment]
> Hi @SyntaxError-Izzy, thank you for your feedback!
> Being allowed to use a function does not assume you should use it ;)

Yes just a little ADHD problem couldn't stand it, sorry to bother you.

**Comment by nprimo** [comment]
Hi @SyntaxError-Izzy, don't feel sorry, every feedback is welcomed and we do appreciate your input to improve the current curriculum whenever we can :)
