### ISSUE TITLE
numpy subject, Exercise 6: why Broadcasting?

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2284]
numpy
---
[Exercise 6](https://github.com/01-edu/public/tree/master/subjects/ai/numpy#exercise-6-broadcasting-and-slicing) is titled "Broadcasting and Slicing" and also there is a note at the end of the exercise referring to a handbook section about broadcasting. While it is a very interesting read, there is little use of that in the exercise.

The task clearly instructs to use slicing only:

> Using **slicing**, output this array:

I imagine the initial array could be created using broadcasting, but it is far more convenient to initialise the array with regular NumPy array creation routines.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for your feedback. I will update the subject (and audit) to make this more relevant to the topic of `broadcasting`

**Comment by jarmo-seljamaa** [comment]
Thanks for this. Please wait with the updates for a couple of days. We're in the middle of the piscine and it would be terribly confusing if the tasks change while we're doing them.

**Comment by jarmo-seljamaa** [comment]
I'm sorry, I looked at your suggested fix, but adding `Using a combination of **slicing** and **broadcasting**, output this array:` doesn't make it any clearer on how broadcasting is supposed to be used there. The solution is still a regular numpy array creation with `np.ones()`. Isn't broadcasting about applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes?

**Comment by nprimo** [comment]
For the first part of the exercise (the creation of the matrix) yes, you can use a simple `np.one()` call. About the second part of the exercise, you're supposed to create the final matrix as shown on the subject. To achieve the final result, you can use slicing, as the example shown in the audit or a combination of both slicing and broadcasting to perform operations between matrixes that don't share the same shape (only one common dimension)

**Comment by jarmo-seljamaa** [comment]
OK, looking at the new example of a possible solution, I'm not sure if it is a good learning example of broadcasting. The previous slicing example was better, imho. But maybe that's just me.

**Comment by nprimo** [comment]
Thank you for the feedback! I updated the new version to have an extra question to use `broadcasting` alone and kept the old questions as they were. We will wait to merge until you all finish with your piscine.

**Comment by jarmo-seljamaa** [comment]
Well, me actually still might need sooner merges, because there are too many mistakes, ambiguities etc as you can see from the other tickets I've opened (and we're only on day 2!).
