### ISSUE TITLE
IsOdd subject

### ISSUE THREAD

**Issue by justachips** [01-edu/public#2287]
IsOdd
---
YO,
VOTRE TEST EST CORRECT
CEPENDANT LE INTRA EST INVERSE
VOTRE ENONCER = Write a function IsOdd that returns true if the int passed as parameter is odd, otherwise return false.

alors que sa devvrais etre =

Write a function IsOdd that returns false if the int passed as parameter is odd, otherwise return true.
0 return true aussi

Derien.

**Comment by MSilva95** [comment]
Hello @justachips, there is no subject IsOdd in this repository, please contact your school management team to solve the issue.
