### ISSUE TITLE
numpy subject Audit questions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2288]
numpy
---

### Exercise 3
[Audit question 4 for Exercise 3](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#for-question-4-is-the-array-nparray0-10340099100-there-are-at-least-two-ways-to-get-this-results-without-for-loop-the-first-one-uses-integers13--0-and-the-second-involves-creating-a-boolean-array-that-indexes-the-array) has a typo in it. In `is the array np.array([0, 1,0,3,4,0,...,0,99,100])?` the array should start with 1 (first 0 is excessive).

### Exercise 4
[Audit questions for Exercise 4](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#for-question-2-is-the-solution-nprandomrandn100-the-value-of-the-first-element-is-017620087373662233) suggest that the solution must be achieved using `np.random.randn(100)`. I used `np.random.normal(size=100)` and got the same result.

### Exercise 5
In [Audit question for Exercise 5](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#for-question-1-is-the-output-the-same-as-the-following) the wording is not precise. `For question 1, is the _output_ the same as the following?` should be `For question 1, is the _solution_ the same as the following?` 
Furthermore I did not use the suggested solution of `np.ones([9,9], dtype=np.int8)` but used `np.full((9,9), np.int8(1))`, so I guess multiple solutions are correct. (Perhaps the wording might be "is the solution the same (or using an equivalent similar method)"?)

### Exercise 7
[Audit question for Exercise 7](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#without-having-used-a-for-loop-or-having-filled-the-array-manually-is-the-output-the-following) there are mentioned two ways to add the third column. I used a third way and it seemed to work well:
```python
third_col = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])
np.column_stack((grades, third_col))
```

### Exercise 8
In [Audit question for Exercise 8](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#has-the-text-file-successfully-been-loaded-in-a-numpy-array-with-genfromtxtwinequality-redcsv-delimiter-and-the-reduced-arrays-weights-76800-bytes) the delimiter is wrong: the correct one is semicolon, not comma.

The [expected result](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#is-the-answer-the-following) lists `mean` as one of the statistics. However, the task asked for `median`.

### Exercise 9
The expected result for [Audit question for Exercise 9](https://github.com/01-edu/public/tree/master/subjects/ai/numpy/audit#is-the-output-the-following-1) is rather confusing. The given dataset is asymmetrical, although if team `i` plays against team `j` then their score differences should be `x` and `-x` depending on which team is winning. 

![image](https://github.com/01-edu/public/assets/80747520/9cac2316-a6a2-42ae-b926-80bce6b945b6)

Looking at the given dataset, only the first values in the corner (green) are symmetrical), the rest are randomly scattered. The audit result implies that the most interesting match would be between team 2 and team 1, but their score differences are far from lowest... I tried to use the values from above the diagonal or below the diagonal only, but the results are not the same as audit says. Are we missing something here?

**Comment by sariyya-abdullayeva** [comment]
I totally agree about confusion and the given "output" in the exercise 9 audit results.

The given results gives way higher squared-sum score than my result
 [[2 9 6 0 8]
  [1 3 5 7 4]]
gives squared sum of 283.842
   
whereas my optimal sum of squared score is 21.7982

**Comment by nprimo** [comment]
@jarmo-seljamaa @sariyya-abdullayeva thank you both for your feedback :)

About Exercise 6 (what you referred to as Exercise 5) it looks to me clear enough that it is expected to have the same output: it doesn't matter the formula used.

For Exercise 7: the ones shown in the audit are just 2 examples, there are many ways to get to the same result :) - the important point here is using `np.where` and getting to the expected output

About Exercise 9, I am looking into it and checking the dataset with the author of this exercise to fix it. I will open a new PR to fix or clarify the requirements for this one.
