### ISSUE TITLE
pandas subject missing datafile & unclear instructions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2290]
pandas
---
[Exercise 3](https://github.com/01-edu/public/tree/master/subjects/ai/pandas#exercise-3-e-commerce-purchases) is missing the datafile:

> The data set used is **E-commerce purchases.**

The 'E-commerce purchases' is not an active URL, so the task is not doable.

**Comment by jarmo-seljamaa** [comment]
Aha, found the file in the [data](https://github.com/01-edu/public/tree/master/subjects/ai/pandas/data) folder here on GitHub, but it should be linked to be usable in our 01 platform where the Piscine takes place.

**Comment by jarmo-seljamaa** [comment]
Apparently [Exercise 4](https://github.com/01-edu/public/tree/master/subjects/ai/pandas#exercise-4-handling-missing-values) is missing any reference to a datafile. I'm assuming it is the other dataset in the `data` folder I referred in my previous comment?

**Comment by jarmo-seljamaa** [comment]
Please clarify the instructions of [Exercise 4](https://github.com/01-edu/public/tree/master/subjects/ai/pandas#exercise-4-handling-missing-values), especially task 2:

>   1. Fill the missing values with a different "strategy" for each column:
>    `sepal_length` -> `mean`
>    `sepal_width` -> `median`
>    `petal_length`, `petal_width` -> 0
>   2. Fill the missing values using the median of the associated column using `fillna`.

We already filled the missing values (using also `fillna` and also median for `sepal_width`) in task 1. What should be done in task 2? There are no missing values left.

The [audit question](https://github.com/01-edu/public/tree/master/subjects/ai/pandas/audit#for-question-2-is-the-solution-dfloccolfillnadfcolmedian) doesn't make it any clearer as it only refers to a line of code that has already been used for task 1, too.

**Comment by jarmo-seljamaa** [comment]
In the [Audit question 6 for Exercise 2](https://github.com/01-edu/public/tree/master/subjects/ai/pandas/audit#for-question-6-were-one-of-the-two-approaches-below-used) additional note has the word `why` missing:

> You may wonder _why_ `df.loc[:,'A']` is required

**Comment by jarmo-seljamaa** [comment]
[Audit question 2 for Exercise 1](https://github.com/01-edu/public/tree/master/subjects/ai/pandas/audit#for-question-2-are-the-columns-types-as-below-and-are-the-types-of-the-first-value-of-the-columns-as-below) describes the expected output for first values of the colums as:

```
        <class 'str'>
        <class 'list'>
        <class 'float'>
```

However, the third column is automatically converted to type `<class 'numpy.float64'>`, no matter how the dataframe is constructed. As we understood it, Pandas tends to automatically convert numerical data to NumPy data types for efficiency. Is there something we are missing?

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa! Thank you for the feedback :)

**Comment by jarmo-seljamaa** [comment]
I'm sorry  @nprimo, but you missed some of the mistakes:

- Changing `<class 'float'>` to `<class 'float64'>` does not resolve the issue in [audit question 2 for Exercise 1](https://github.com/01-edu/public/tree/master/subjects/ai/pandas/audit#for-question-2-are-the-columns-types-as-below-and-are-the-types-of-the-first-value-of-the-columns-as-below), as the type is automatically cast to `<class 'numpy.float64'>` only.
- The [Audit question 6 for Exercise 2](https://github.com/01-edu/public/tree/master/subjects/ai/pandas/audit#for-question-6-were-one-of-the-two-approaches-below-used) additional note still has the word _why_ missing in the sentence `You may wonder _why_ df.loc[:,'A'] is required...`
- Nothing was updated the setup of Exercise 4 (confusing instructions described [here](https://github.com/01-edu/public/issues/2290#issuecomment-1821755315))

**Comment by nprimo** [comment]
Thank you for the additional feedback! To facilitate addressing all the suggestions you made it is easier to separate them into separate issues to avoid missing some details (like it happened :sweat_smile:)

- I will update `float64` -> `numpy.float64`
- Fix the grammar suggestion on exercise 2
- About Exercise 4, I have added an extra sentence before the bullet points - basically, it is to try filling in the missing values either by specifying the strategy per each column or by using one strategy for the all dataset
