### ISSUE TITLE
visualizations subject errors and questions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2295]
visualizations
---
## Exercise 1
The [visualization](https://github.com/01-edu/public/blob/master/subjects/ai/visualizations/w1day03_ex1_plot1.png) of Exercise 1 task 1 has a title `Histogram` but it's a bar graph. The task description is correct, though.

## Exercise 6
The [link](https://plotly.com/python/time-series/e) at the end of [Exercise 6 task 2](https://github.com/01-edu/public/tree/master/subjects/ai/visualizations#exercise-6-plotly-1) gives 404.

## Exercise 7
The instructions are a bit confusing, especially this: `Plot in the same Figure 2 box plots as shown in the image.` What is meant by `Figure 2`? The given sample image has box plot of 2 data columns, but we are given 3 arrays as input. I guess this can be overlooked as the instructions also say `In this exercise the style is not important.`

So I solve it, creating a visually similar graph - it is a box plot with different coloured series, a title and a legend. Then I look at the audit questions and see that the expected solution uses `plotly.graph_objects` while I used `plotly.express`. Furthermore, the solution in audit also takes the 3 arrays as input, but completely ignores the y2 array and visualizes only y0 and y1. Why???

Is this a valid solution, or should I rewrite it to match the audit solution? The task says `In this exercise the style is not important.` but the audit says `does the plot reproduce the plot in the image` and my plot is not an exact replica...

![image](https://github.com/01-edu/public/assets/80747520/11282b54-ccac-4945-8012-0ecec82f08d6)

**Comment by nprimo** [comment]
@jarmo-seljamaa thank you for the feedback
