### ISSUE TITLE
data-wrangling subject environment

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2296]
data-wrangling
---
The [Virtual Environment for data-wrangling tasks](https://github.com/01-edu/public/tree/master/subjects/ai/data-wrangling#virtual-environment) lists Tabulate as one of the libraries. No task involves using Tabulate by task description or audit questions.

On the other hand, [the second task in Exercise 6](https://github.com/01-edu/public/tree/master/subjects/ai/data-wrangling#exercise-6-unstack) instructs to `Plot the 5 times series in the same plot using Pandas built-in visualization functions with a title.`

Pandas built-in visualisation functions are essentially a wrapper around the Matplotlib library, so by trying to call .plot() methods on my dataframe I get an error:

> ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

Importing `matplotlib` cannot also be done, because it was not included in the environment, so `import matplotlib.pyplot` does not resolve.

**Comment by jarmo-seljamaa** [comment]
Correction: after removing the `tabulate` library I learned that `.to_markdown()` has a dependency to `tabulate`, so this is needed in the environment (would be nice to mention that fact somewhere in the intro, though). 

The `matplotlib` dependency question remains. Should we figure out a way to solve the task without `matplotlib?

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa thank you for the feedback. `matplotlib` should be included in the dependencies: as you said, "Pandas built-in visualisation functions are essentially a wrapper around the Matplotlib library" is correct :)
