### ISSUE TITLE
time-series subject audit question 1 of Exercise 4

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2299]
time series
---
In the [audit questions of Exercise 4](https://github.com/01-edu/public/tree/master/subjects/ai/time-series/audit#for-question-1-is-the-return-computed-as-returnt--pricet1---pricetpricet-and-returns-the-following-output-note-that-if-the-index-is-not-ordered-in-ascending-order-the-future-return-computed-is-wrong-the-answer-is-also-accepted-if-the-returns-is-computed-as-in-the-exercise-2-and-then-shifted-in-the-futur-using-shift-but-i-do-not-recommend-this-implementation-as-it-adds-missing-values)  you write:

>  The answer is also accepted if the returns is computed as in the exercise 2 and then shifted in the futur using `shift`, but I do not recommend this implementation as it adds missing values!

Then below that you give an example solution that uses that same method with `shift`, which you do not recommend. How will we learn what is the _recommended_ calculation method if that method is not described?

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa thank you for the feedback
