### ISSUE TITLE
[TOAD] - Not displayed through the Mozilla Firefox browser

### ISSUE THREAD

**Issue by Zulbukharov** [01-edu/public#23]
Toad page doesn`t appear from Mozilla Firefox browser.

1. Install Mozilla Firefox browser
2. Login to Intra
3. Open 
4. See nothing

**Expected behavior**
Game page

**Screenshots**
![=(](https://i.imgur.com/uvbEw6s.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: mozilla firefox
 - Version: 10.14.4

**Type**
blocking

**Priority**
normal

**Subject**
toad

**Comment by kigiri** [comment]
Ah yeah we currently make use of `dynamic imports`
Which only works behind a flag right now in firefox.

This is the current availability of this feature: https://caniuse.com/#feat=es6-module-dynamic-import

in FF 66+ support can be enabled via `javascript.options.dynamicImport` flag.

*(type in `about:config` in the url)*


Now, of course this won't be the case for the production build, but right now we kept transpilation of the javascript code minimal so errors would be closer to the real code.
