### ISSUE TITLE
[BUG] ai branch contains reference links to paid subscription sites

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2310]
ai
---
Many of the tasks contain links to articles at [https://towardsdatascience.com/](https://towardsdatascience.com/) or [https://medium.com/](https://medium.com/) which are behind paywall with this notice:
> The author made this story available to Medium members only. Upgrade to instantly unlock this story plus other member-only benefits.

For example:

- [NumPy](https://github.com/01-edu/public/tree/master/subjects/ai/numpy#resources)
- [Data Wrangling](https://github.com/01-edu/public/tree/master/subjects/ai/data-wrangling#exercise-3-merge-multiindex)
- [Linear Regression resources](https://github.com/01-edu/public/tree/master/subjects/ai/linear-regression#linear-regression-1)
- [Linear Regression task](https://github.com/01-edu/public/tree/master/subjects/ai/linear-regression#exercise-4-forecast-diabetes-progression)

This is not a complete list.

Please replace these references with materials that are publicly available.

**Comment by jarmo-seljamaa** [comment]
Same goes for [kaggle-titanic](https://github.com/01-edu/public/tree/master/subjects/ai/kaggle-titanic#preliminary) task.

**Comment by Oumaimafisaoui** [comment]
Hello @jarmo-seljamaa . Thank you for your feedback. There had been a review for all the  links and it had been updated to free accessible resources.
