### ISSUE TITLE
graphql subject : is external libraries allowed (for svg graphs)

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2312]
graphql
---
Hi,
I audited a lot of grahql that used external libraries to display data as graph.
Seems like most people assume that is OK; it wasn't my understanding.
I suggest to make an explicit statement in the instructions/audit.

**Comment by fulverin** [comment]
but if it is ok and it is only me misunderstanding instructions, then nevermind.
>This graphs must be done using [SVG].
but the phrase makes me think it should be done from scratch.

**Comment by MSilva95** [comment]
Hello @fulverin thank you for the feedback and the attention to detail, I've reshaped the questions in the audit and and improved the language as well, now we ask for the usage of "svg" in the audit as we ask in the readme instructions.
