### ISSUE TITLE
[BUG] pipeline subject datafile, data info and example do not match

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2318]
pipeline
---
The [datafile](https://github.com/01-edu/public/blob/master/subjects/ai/pipeline/data/breast-cancer.csv), the [datafile readme info](https://github.com/01-edu/public/blob/master/subjects/ai/pipeline/data/breast_cancer_readme.txt) and the [example assumptions on the variables](https://github.com/01-edu/public/tree/master/subjects/ai/pipeline#exercise-5-categorical-variables) do not match.

Datafile columns (note the 1st and 10th column contents):
![image](https://github.com/01-edu/public/assets/80747520/03b4b529-5458-4ebd-8ef1-86beb7e3e2b2)

The datafile readme info (note the 1st and 10th variable descriptions):
![image](https://github.com/01-edu/public/assets/80747520/4be27dd1-66c7-44e4-8d57-4a274b837e22)

The assumptions on the variables (note the 1st and 9th variable assumptions):
![image](https://github.com/01-edu/public/assets/80747520/ab83406a-f39a-49bc-a954-51cdea6d2bb2)

**Comment by brad-gh** [comment]
I'll look at this one. I remember I changed the input file and its readme, but I might have forgotten to update the exercise. 
Thanks for flagging the issue.
