### ISSUE TITLE
[BUG] pipeline subject deprecated sample code

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2319]
pipeline
---
The [Exercise 5](https://github.com/01-edu/public/tree/master/subjects/ai/pipeline#exercise-5-categorical-variables) contains sample code that uses deprecated function `get_feature_names()`. Instead `get_feature_names_out()` should be used.

Also, not sure if it is because an outdated version of Scikit has been used or because the datafiles were messed up (explained [here](https://github.com/01-edu/public/issues/2318)) but the results in this expected output are not replicable (the transformed test set):

![image](https://github.com/01-edu/public/assets/80747520/d0e194d7-6d89-4c8c-9c04-93a0d4f2c78d)

**Comment by Oumaimafisaoui** [comment]
Hello @jarmo-seljamaa ! Thank you for your input, the deprecated functions were changed, please do not hesitate to declare any further encountered issue.
