### ISSUE TITLE
buy-02 subject

### ISSUE THREAD

**Issue by danglam88** [01-edu/public#2323]
buy-02
---

In the "**User Profile**" section, there is a sentence saying "**Develop a user profile section where users can see their best products, most buying products, and how much money they spent**"

What do you mean by "**best products**"? Isn't it the same as "**most buying products**"?

**Comment by NafiRanta** [comment]
@zanninso Could you please clarify the above as soon as you can. Thank you in advance!

**Comment by zanninso** [comment]
best baying products can be the products that you search many time, the products that you put in your wish list and may be the most buying products also, the goal here is to give the users a report about his actions in the platform .

**Comment by zanninso** [comment]
@NafiRanta  i will close this issue issue you can reopen it if you still see that it's not clear enough
