### ISSUE TITLE
training subject audit questions missing

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2326]
training
---
The audit questions for [Exercise 1](https://github.com/01-edu/public/tree/master/subjects/ai/training/audit#exercise-1-mse-scikit-learn) and [Exercise 2](https://github.com/01-edu/public/tree/master/subjects/ai/training/audit#exercise-2-accuracy-scikit-learn) are missing. Instead the audit contains a copy of the task description.

@nprimo Please fix urgently, as we are in the middle of the piscine and these are today's tasks!

**Comment by MSilva95** [comment]
Hello @jarmo-seljamaa!
I will add the questions, Nico is on vacations so i will take a look, thank you for the feedback!
