### ISSUE TITLE
nlp-spacy subject Exercise 1 lack of instructions & audit question about non-existing task

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2345]
nlp-spacy
---
The following instruction for [Exercise 1](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-spacy#exercise-1-embedding-1) is insufficient:

> Compute the embedding of `car`.

It would make sense, if we could look up keyword `embedding` in the provided [API docs](https://spacy.io/api/doc) or the provided [English language pipeline](https://github.com/explosion/spacy-models/releases/tag/en_core_web_sm-3.4.0) but there appears to be nothing about that. Thanks to the audit question I figured that we are required to print the `.vector.shape` for the word embeddings of the string `car`.

The audit of that task refers to [an additional question 2](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-spacy/audit#for-question-2-do-the-20-first-values-of-the-vector-sum-to-29790137708187103) which is not present in the task description.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for the feedback. 

About the wording, it would be nice to do a quick search in the documentation to find out more about it. However, you can easily find out about `embedding` terminology in the scope of NLP with a quick Google search/[Wikipedia](https://en.wikipedia.org/wiki/Word_embedding)

Related to the audit, I feel the wording of the question are a bit off - I have already made some changes to make it clearer during the audit what is required to check

**Comment by jarmo-seljamaa** [comment]
@nprimo you seem to have missed my point. Of course it is easy to look up what does `embedding` mean, but the goal of AI piscine is to give us the skills and tools to learn to use NLP, specifically spaCy in this quest. Therefore I feel that the task instructions should include a bit more precise information on what is the expected result of such `computing`. In this specific case I would expect to see something like this: `Compute the embedding of the word 'car' and print out the vector shape of it`. 

Furthermore, considering your suggested change in audit questions, an additional line is expected in the task instructions: `Using the computed embeddings of the word 'car' print out it's vector shape and the sum of the first 20 values of the vector.`

**Comment by jarmo-seljamaa** [comment]
Ah, and by the way, I got `2.9790106` for the sum of the first 20 values, not `2.9790137708187103`. Is the precise float value important here, which is why so many decimal places were given in audit?

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for the additional feedback. I do agree with the two points you raised. I will add more details to the subject and audit to make it clearer what is supposed to achieve / do
