### ISSUE TITLE
nlp-spacy subject Exercise 3 audit specifies extra task

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2346]
nlp-spacy
---
[Audit question for Exercise 3](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-spacy/audit#for-question-1-have-the-embeddings-of-each-word-a-shape-of-300-and-are-the-first-20-values-of-the-embedding-of-laptop-the-following) includes two parts. The first (`shape of the embeddings of each word`) is included in the task, but the second (`the first 20 values of the embedding of laptop`) is not specified in task description.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for the feedback.

If you have calculated the embeddings of each word, you should be able to verify the first 20 values of the embedding related to `laptop` words :)

The audit is not a machine test therefore, you should be able to show the results to the person that is going to audit you. 
In any case, I am reviewing the exercise to add the version of the language model to use to avoid mismatches in the values

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa thank you for sharing with us your opinion :pray:
