### ISSUE TITLE
nlp subject Exercise 7 audit results fail to follow task instructions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2349]
nlp
---
We struggled to get the results as described in the [audit of Exercise 7](https://github.com/01-edu/public/tree/master/subjects/ai/nlp/audit). After a lot of trial and error we discovered that we get the exact audit results ONLY when we ignore the task instructions.

The instructions say:

> Steps:
> 1.  Preprocess the data using the function implemented earlier. Then, use CountVectorizer from scikit-learn with max_features=500 to compute the word count of the tweets. The output is a sparse matrix.

We could get the expected audit results for Question 1, 2 and 3 when we skip preprocessing completely and feed the raw data from the given file into the CountVectorizer. Most probably this is not the intended solution. Please re-check the audit.

**Comment by brad-gh** [comment]
Thanks for flaggin the issue.

You are right the audit assumes that there's no pre-processing. That's an error. It was not easy to spot, great work ! I'll fix it tomorrow. I'll send you the notebook with the answer to make sure we're on the same page and that you reproduce the audit with my solution.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for the feedback! The subject and audit are going to be updated in the following days to resolve this issue.
