### ISSUE TITLE
push-swap subject

### ISSUE THREAD

**Issue by Bakarseck** [01-edu/public#2352]
push-swap
---
Hello !!!
There is a problem in the audit, regarding this question
```bash
ARG=("4 67 3 87 23"); ./push-swap $ARG | ./checker $ARG
``` 
there should have been quotes at $ARG in front of push-swap and in front of checker like this
```bash
ARG=("4 67 3 87 23"); ./push-swap "$ARG" | ./checker "$ARG"
```

**Comment by nprimo** [comment]
Hi @Bakarseck, thank you for pointing this out :) Different shells can indeed interpret the current audit commands in different ways. We will update the audit commands to run to be in line with the one shown in the subject
