### ISSUE TITLE
wget subject

### ISSUE THREAD

**Issue by MalekLahbib** [01-edu/public#2356]
wget
---
if you do "wget --mirror http://corndog.io/" you get "index.html" and 3 png files but locally the site doesn't work as the original one. I have the same problem with my own wget. The problem is that the css of the page have "background-image: url('/corndog-tile-1.png')" that works online but not locally.

**Comment by MSilva95** [comment]
Hello @MalekLahbib!
I will create a pr with a fix for this problem, thank you for the feedback.
Meanwhile you can use  the `--convert-links` flag. This flag will convert all the links (including those in CSS) to work locally.

**Comment by MalekLahbib** [comment]
thanks for your response, I saw that you modified the audit question but in the subject it's not asked to create the "--convert-links" flag so what's the solution
