### ISSUE TITLE
Repo usage

### ISSUE THREAD

**Issue by abduakhatov** [01-edu/public#2365]
Dear 01-Edu team, 

I found this repo rather useful and interesting. Is it possible to get for of this repo and use for personal purposes? Unfortunately I could not find any license for this repo. 

For further contacts:
**tg:** sabduakhatov
**email:** abduakhatov.shohruh@gmail.com

Best regards.

**Comment by kigiri** [comment]
Yes we have not defined a proper licencing yet, personal use is fine as long as you do not use it commercial there is no issue with you using this content, I'll talk with the legal team to make sure we have a license that reflect that.

How ever this is low priority so for now you can juste take my word for it 😅
