### ISSUE TITLE
make-your-game 60fps not accessible

### ISSUE THREAD

**Issue by goobric** [01-edu/public#2366]
make-your-game

not able to access the link to the required '60fps' 
https://pics.me.me/60-fps-59-fps-35518800.png
Error: the image cannot be displayed, because it contains errors.

![240108_01F_MYG_60fps_err](https://github.com/01-edu/public/assets/23141638/5456b837-e8a6-4759-b823-e2aa769da79a)

---

**Comment by nprimo** [comment]
Hi @goobric thank you for your feedback! We'll try to fix the link as soon as possible
