### ISSUE TITLE
retrieve-block-date subject

### ISSUE THREAD

**Issue by MalekLahbib** [01-edu/public#2367]
retrieve-block-date
---
I created a js file beginning with async function retrieveBlockDate(blockHeight) {, as a normal js file but I have this error msg each time I submit the project :
1) retrieve block date
       latest block is ok:
     TypeError: retrieveBlockDate is not a function
      at Context.<anonymous> (/app/btc/retrieve-block-date.test.js:21:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by MalekLahbib** [comment]
Hello, here's my file content:

const Client = require('bitcoin-core');

async function retrieveBlockDate(blockHeight) {
  //console.log(blockHeight);
  // Create a new client to connect to the Bitcoin Core instance
  const client = new Client({
    network: 'regtest', // Replace with your desired network (mainnet, testnet, regtest, etc.)
    host: '127.0.0.1', //
    username: 'leeloo',
    password: 'multipass',
    port: 18443, // Replace with your RPC port
  });

  try {
    // Get block hash from block height
    const blockHash = await client.getBlockHash(blockHeight);

    // Get block information
    const blockInfo = await client.getBlock(blockHash);

    // Extract the block timestamp (Unix timestamp)
    const blockTimestamp = blockInfo.time;

    // Convert Unix timestamp to JavaScript Date object
    const blockDate = new Date(blockTimestamp * 1000); // Multiply by 1000 to convert seconds to milliseconds

    return blockDate;
  } catch (error) {
    console.error('Error:', error);
    throw error;
  }
}

module.exports = retrieveBlockDate;

**Comment by nprimo** [comment]
There is an issue with the way you're exporting your solution. Try to successfully import (and therefore export) your solution from another file before resubmitting :)

**Comment by MalekLahbib** [comment]
I found a solution for exporting the function but, I think there's a problem with the instructions, it's said:
Using Node.js, create and exports a function retrieveBlockDate() that takes as input the height of a block and returns the date of this block. The date must be a date javascript object.
But I passed the test providing a number without converting it to javascript date, here's my code:
 // Get block hash from block height
    const blockHash = await client.getBlockByHash(blockHeight);
   

    // Get block information
    const blockInfo = await client.getBlock(blockHash.hash);

    // Extract the block timestamp (Unix timestamp)
    const blockTimestamp = blockInfo.time;

    // Convert Unix timestamp to JavaScript Date object
    // const blockDate = new Date(blockTimestamp * 1000); // Multiply by 1000 to convert seconds to milliseconds
    return blockTimestamp;

**Comment by nprimo** [comment]
Thank you for the feedback @MalekLahbib - I will update the subject to make it coherent with the test :)
