### ISSUE TITLE
guess-it-1 subject

### ISSUE THREAD

**Issue by MAATII** [01-edu/public#2369]
guess-it-1
---
exec file from ai directory can't work on Mac m1, m2 & m3 (silicon)

**Comment by nprimo** [comment]
Hi @MAATII, could you provide us with some more information? For example:
1. What error message are you getting when trying to follow the instructions provided in the subject and/or audit? 
2. How did you structure the testing? A copy of the standard output of a `tree` command from the root of your project, for example, could help

**Comment by MAATII** [comment]
Hello, Thank you for your answer, here is the error message when I try to test a data set : 
`Listening in port 3000
/bin/sh: ./ai/average: cannot execute binary file
/Users//Desktop/guess-it-1/server.js:26
    throw Error('No file found\n' + err)
          ^

Error: No file found
Error: spawnSync /bin/sh EPIPE
    at /Users/Desktop/guess-it-1/server.js:26:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
`
I structure the testing as asked in the audit : `─ guess-it/
├── ai/
│   ├── big-range
│   └── ...
├── index.html
├── index.js
└── ...
└── student/
    ├── solution.py
    └── script.sh`
It's the same problem for maths-skills, linear-stats, guess-it-2. Other peoples from my class who have Mac M1 or M2 have the same problem.
My Programm work perfectly on other computers

**Comment by nprimo** [comment]
Thank you for the feedback @MAATII. We will soon provide a solution that can run on also on Mac M1/2/3 PCs
