### ISSUE TITLE
hash-160 subject

### ISSUE THREAD

**Issue by MalekLahbib** [01-edu/public#2382]
hash-160
---
I have this error when I run the test:
ReferenceError: exports is not defined
    at eval (eval at main (file:///app/test.mjs:109:3), <anonymous>:10:1)
    at main (file:///app/test.mjs:109:3)

********** here's my code:

const crypto = require('crypto');

const hash160 = (input) =>{
    const sha256Hash = crypto.createHash('sha256').update(input).digest();
    const ripemd160Hash = crypto.createHash('ripemd160').update(sha256Hash).digest();
    return ripemd160Hash;
}

exports.hash160 = hash160;

**Comment by nprimo** [comment]
Hi @MalekLahbib, the issue is that in this case you're not supposed to export the function.
