### ISSUE TITLE
printcomb2 subject

### ISSUE THREAD

**Issue by adunayev** [01-edu/public#2384]
printcomb2
---
why test compares printcomb.go, since it is not me uploaded file into the repository, it automatically were uploaded, trough the previous exercise?
I try to adjust the format trough gofmt -w printcomb.go and updating it but it still does not compare correct files. Task said that i have to submit printcomb2.go and it is not compared correctly

**Comment by adunayev** [comment]
i am getting following return(which is not the function that should be comared in this task
Your Go files are not correctly formatted :

$ gofumpt -d .
diff -u printcomb.go.orig printcomb.go
--- printcomb.go.orig
+++ printcomb.go
@@ -3,11 +3,9 @@
 import "github.com/01-edu/z01"
 
 func PrintComb() {
-
 	for i := '0'; i <= '9'; i++ {
 		for j := '0'; j <= '9'; j++ {
 			for k := '0'; k <= '9'; k++ {
-
 				if i < j && j < k {
 					z01.PrintRune(i)
 					z01.PrintRune(j)
@@ -19,10 +17,7 @@
 						z01.PrintRune(' ')
 					}
 				}
-
 			}
-
 		}
-
 	}
 }

**Comment by nprimo** [comment]
Hi @adunayev, thank you for your feedback. Could you please tell us what is the error you're getting? :)

As far as I can see from the subject of `printcomb2` (and from the tests linked to `printcomb2`), no solution is provided for `printcomb` in our curriculum: to which file are you referring?

**Comment by adunayev** [comment]
Hello @nprimo, thank you for response. Let me try to explain the issue. The task princomb was not uploaded by me trough the regular way when i add the files, then commit, then push. I wrote code in the built-in window on the website, tested it right there and submitted trough the website interface. 
After i submitted it was successful, i proceeded with the next taks printcomb2. Meanwhile to my repository there were a commit by [Christopher Fremond] - i think it is automated and the file printcomb.go was added to the repository trough that commit. Then when i uploaded file printcombo2 to check the solution and pushed test button the error i got is exactly which i provided earlier.
that starts with 
$ gofumpt -d .
diff -u printcomb.go.orig printcomb.go
--- printcomb.go.orig
+++ printcomb.go
@@ -3,11 +3,9 @@
import "github.com/01-edu/z01"
func PrintComb() {
for i := '0'; i <= '9'; i++ {
	for j := '0'; j <= '9'; j++ {
		for k := '0'; k <= '9'; k++ {
etc.
which as i understand, if about format of the code that i wrote manully in the previous task.
I resolved this issue by removing the code that was uploaded by Christopher Fremond, then it started to check the right file. and it happens not only here, but in other tasks where i have to write code manually, someone uploads it to my repository.
Hope the issue is more clear, when try to check file printcomb2, it should not check dif of printcomb.

**Comment by nprimo** [comment]
Thank you for the clarification: now the issue is clearer :) 
The issue (wrong formatted file) was caused when the solution was submitted through the platform code editor. Every time a test runs, all the files in your solution directory are checked for formatting issues, that's why you can get an error linked to a previous solution.

We will try to fix this as soon as possible.

**Comment by Frenchris** [comment]
Hello @adunayev . How are you? May you tell me your gitea loggin?

**Comment by adunayev** [comment]
Hello!Thanks, I’m doing good. I believe my login is adunayev.On 18 Jan 2024, at 22:17, Christopher Fremond ***@***.***> wrote:﻿
Hello @adunayev . How are you? May you tell me your gitea loggin?
