### ISSUE TITLE
Question about the project 0-shell

### ISSUE THREAD

**Issue by xrisc** [01-edu/public#2388]
I suppouse "You must implement the following commands:" means that the code/shell should include its own code for handling these commands in opose to calling those provided by the os? As most shells make use of the same binaries for the listed commands, it would be good if it was clear both in the project description as in the audit what is allowed.

**Comment by nprimo** [comment]
Hi @xrisc, the mentioned commands are "builtins" and, therefore, present in the shell source code. The idea is for your `0-shell` to have those commands implemented (from scratch) in your shell source code, without calling the `bash` commands :)

I will see how to update the subject/audit to ensure that the "implementation" is not a simple OS call.

**Comment by bomanviktor** [comment]
Also, in the project description, there is nothing that indicates that any flags have to be implemented. In the audit, we are being asked to implement `-l -a -F` for `ls` and the `-r` flag for `rm`.

**Comment by jo-eman** [comment]
This project description could need even more clarifications.

What exactly is the "Shell call" that is prohibited? Calling another existing shell like bash or zsh?

So then calling OS service binaries like "ls" is still OK? Since it is a standalone binary and not a "bash command"
