### ISSUE TITLE
displayfile "io/ioutil" allowed function is deprecated and should be replaced with "io"

### ISSUE THREAD

**Issue by TomPadmanathan** [01-edu/public#2392]
As of go 1.16 the "io/ioutil" package has been deprecated and has been replaced with "io". You can either update the allowed functions to use "io" or just remove the package entirely as the already allowed "os" package allows you to complete this task as well.

The "io/ioutil" package is also used of other questions as well so you may need to check them also.

**Comment by MSilva95** [comment]
Thank you for the feedback we will update the allowed functions as soon as possible!

**Comment by MSilva95** [comment]
It was fixed here <https://github.com/01-edu/all/pull/1877/files>
