### ISSUE TITLE
math-skills subject

### ISSUE THREAD

**Issue by jo-eman** [01-edu/public#2395]
math-skills
---
provided binary for generating the dataset during the audit does not run on mac
https://assets.01-edu.org/stats-projects/math-skills

**Comment by MSilva95** [comment]
Hello @jo-eman ! This issue is the same as this one #2369, we are already taking action to solve the issue, thank you for the feedback.
 I will close this issue as it is a duplicated.

**Comment by nprimo** [comment]
@jo-eman we will update the provided files to be able to run on Mac M machines.
