### ISSUE TITLE
wget subject

### ISSUE THREAD

**Issue by amali01** [01-edu/public#2399]
wget
---
in the audit questions{
Mirror
Try to run the following command ./wget --mirror --convert-links http://corndog.io/, then try to open the index.html with a browser}

the command has "--convert-links" flag which has not been mentioned in the project at all , it looks like a typo  !
    
![Screenshot from 2024-01-24 00-04-44](https://github.com/01-edu/public/assets/140966242/87f003e3-202e-473c-a605-ed84afbc15d5)

**Comment by MSilva95** [comment]
Hello @amali01!
The flag is there in order to convert all the links (including those in CSS) to work locally.

**Comment by MSilva95** [comment]
Hello @amali01!
I will close the issue since i think you got clarified.
If you still have questions regarding this subject, please reopen the issue!
