### ISSUE TITLE
sortwordarr subject

### ISSUE THREAD

**Issue by amaftah** [01-edu/public#2400]
sortwordarr
---
# piscine/sortwordarr
sortwordarr/main.go:9:2: undefined: SortWordArr

**Comment by MSilva95** [comment]
Can you please elaborate this?
It seams like its something wrong with your code but i cant know for sure without any info.

**Comment by amaftah** [comment]
when i run the exercise i get this error sortwordarr/main.go:9:2: undefined: SortWordArr

package piscine

func SortWordArr(a []string) {
	x := len(a)
	for i := 0; i < x; i++ {
		for j := i + 1; j < x; j++ {
			if a[i] > a[j] {
				a[i], a[j] = a[j], a[i]
			}
		}
	}
}

**Comment by MSilva95** [comment]
If you are using the code editor to test the function you need to use the imports of the piscine in the provided main.go file like so :
```go
package main

import (
	"fmt"
	"piscine"
)

func main() {
	result := []string{"a", "A", "1", "b", "B", "2", "c", "C", "3"}
	piscine.SortWordArr(result)

	fmt.Println(result)
}
```

**Comment by amaftah** [comment]
alright thanks
