### ISSUE TITLE
send-hash subject

### ISSUE THREAD

**Issue by MalekLahbib** [01-edu/public#2403]
send-hash
---
I pushed a solution using "web3.js" module and had this result: 

 1) Uncaught error outside test suite

  0 passing (288ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught Error: Cannot find module 'web3'
Require stack:
- /jail/student/send-hash.js
- /jail/test/send-hash.test.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
      at Function.Module._load (node:internal/modules/cjs/loader:920:27)
      at Module.require (node:internal/modules/cjs/loader:1141:19)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> (student/send-hash.js:1:14)
      at Module._compile (node:internal/modules/cjs/loader:1254:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Function.Module._load (node:internal/modules/cjs/loader:958:12)
      at Module.require (node:internal/modules/cjs/loader:1141:19)

error: "hardhat" exited with code 1 (SIGHUP)

This is my code:
const Web3 = require('web3');
const crypto = require('crypto');

// Create a web3 instance, connecting to a local node
const web3 = new Web3('http://localhost:8545');

async function sendHash(text, RECEIVER_ADDRESS) {
    try {
        // Get the first account available on the local node
        const accounts = await web3.eth.getAccounts();
        const senderAddress = accounts[0];

        // Create a hash using sha256
        const hash = crypto.createHash('sha256').update(text).digest('hex');

        // Prepare the transaction object
        const transactionObject = {
            from: senderAddress,
            to: RECEIVER_ADDRESS,  // Replace with the recipient's Ethereum address
            value: '0x0',  // Sending 0 ETH
            data: '0x' + hash,  // Attach the hash to the data field
            gasPrice: await web3.eth.getGasPrice(),
            gas: 21000,  // Gas limit for a simple transfer
        };

        // Sign the transaction
        const signedTransaction = await web3.eth.sendTransaction(transactionObject);

        return signedTransaction.transactionHash
    } catch (error) {
        console.error('Error sending transaction:', error.message);
    }
}

is this normal? Am I making a mistake?

**Comment by nprimo** [comment]
Hi @MalekLahbib, there are a couple of things that do not match the subject requirements: your solution should have the following structure (not considering the initial "imports").
```js
function sendHash(text) {
  //...
}
module.exports = sendHash
```
The solution you shared does not export any function and your function signature is different than the one required.

However, there is a bug in the test infrastructure (that is causing the error `Uncaught Error: Cannot find module 'web3'`). I will update the testing to allow any solution to use the `web3` as suggested in the subject. 

In the meantime, you can explore the other alternative package: `ethers`

**Comment by MalekLahbib** [comment]
Hi @nprimo , thanks for your response, I finally passed this subject with ethers package, I forgot to copy module.exports in my message. 
I lost nearly 24hr because of this: "sends a transaction to an address with the hash of the document in the data field". I was thinking that the receiver address will be given by the test file, I was having different error msg each time but without clearly saying that the receiver is missing, till I tried taking the second account as the receiver and it worked, I think the instructions needs to be clearer/more precise.
thanks

**Comment by nprimo** [comment]
Hi @MalekLahbib, the error messages are given by the `ethers` package. Unfortunately being able to read "cryptic" error messages is a required skill to program.
Regarding the address to send the hashed text to, it does not matter to which account to pass the tests, as far as I can see.
