### ISSUE TITLE
atoibase subject

### ISSUE THREAD

**Issue by adunayev** [01-edu/public#2406]
atoibase (Quest 5, last task)
---
Hello!
Both me and my auditor when we submitted our code, and try to run atoibase test, face similar issue - test started to run and it shows Testing... for quite a while(more than 10 minutes, and looks like it don't want to stop). it does not break with something like timeout error, it just keep running. In another tab, when i tried to submit to the same exercise a function that instantly return 0, in order to check maybe some infinite loop is called, it still shows that test is running and not showing an error. So perhaps something is not handle things as it was intended in the test of atoibase.
Now since we matched each other platform shows that we have to test each other, but since it is constantly running i keep seeing this message("You have to audit on atoibase! You already bet, but now you have to run the tester to send your result to aaidynul.").
Before i submitted this issue i tried to submit another exercise, and it was submitted correctly and accepted my solution, so i tend to think that something is not working correctly with this specific exercise(atoibase).
My account name is adunayev.

**Comment by adunayev** [comment]
Now when we try to submit another exercises that requires audit(i.e. rotatevowels), we cannot check for them, looks like platform thinks we have to finish previous exercise first and it is not allowing us to check for the new one.

**Comment by MSilva95** [comment]
Hello @adunayev!
I am currently trying to replicate your problem and all is working fine, the test are passing wit the solutions we have for the exercise.

Can you please send us your solution?
And what school and campus are you in?

**Comment by adunayev** [comment]
Hello, @MSilva95 
Here is my code. I know the last func IntToBase is unnecessary, but it still does not return anything, test keeps running.
package piscine

import "github.com/01-edu/z01"

func AtoiBase(numStr string, base string) int {
	if !isValidBase_new(base) {
		return 0
	}
	result := 0
	baseLength := len(base)
	isNegative := false
	if numStr != "" && numStr[0] == '-' {
		isNegative = true
		numStr = numStr[1:]
	}
	for i := 0; i < len(numStr); i++ {
		digitValue := getDigitValue(rune(numStr[i]), base)
		if digitValue == -1 {
			return 0
		}
		result = result*baseLength + digitValue
	}
	if isNegative {
		result = -result
	}
	return result
}

func getDigitValue(digit rune, base string) int {
	for i, b := range base {
		if b == digit {
			return i
		}
	}
	return -1
}

func isValidBase_new(base string) bool {
	if len(base) < 2 {
		return false
	}
	for i := 0; i < len(base); i++ {
		if base[i] == '-' || base[i] == '+' {
			return false
		}
		for j := i + 1; j < len(base); j++ {
			if base[i] == base[j] {
				return false
			}
		}
	}
	return true
}

func PrintInt(n int) {
	if n < 0 {
		z01.PrintRune('-')
		n = -n
	}
	if n == 0 {
		z01.PrintRune('0')
		return
	}
	var runes []rune
	for n > 0 {
		digit := rune(n%10) + '0'
		runes = append(runes, digit)
		n /= 10
	}
	for i := len(runes) - 1; i >= 0; i-- {
		z01.PrintRune(runes[i])
	}
}

func IntToString(n int) string {
	if n == 0 {
		return "0"
	}
	isNegative := n < 0
	if isNegative {
		n = -n
	}
	str := ""
	for n > 0 {
		digit := n % 10
		str = string('0'+digit) + str
		n /= 10
	}
	if isNegative {
		str = "-" + str
	}
	return str
}
Also i try to send an image of this running code
<img width="997" alt="Screenshot 2024-01-25 at 17 15 00" src="https://github.com/01-edu/public/assets/156910410/d4659ff3-8106-49bb-9ce6-09a33b5f8e55">

**Comment by adunayev** [comment]
Also im in Almaty, Kazakhstan using following link to access platform zero.academie.one

**Comment by MSilva95** [comment]
It looks like its a problem only when using the code editor, i will look a bit more into this and fix it as soon as possible!

**Comment by MSilva95** [comment]
This is fixed here <https://github.com/01-edu/all/pull/1745> it still needs to be deployed and we will do it as soon as possible.
meanwhile we will close this ticket, thank you for the feedback!
