### ISSUE TITLE
select-invoices-order-desc subject

### ISSUE THREAD

**Issue by devilsc0d3** [01-edu/public#2418]
my sql query: SELECT * FROM invoices
WHERE BillingCity IN ('Bordeaux', 'Paris', 'Stuttgart')
ORDER BY Total DESC; I have this mistake there Missing student solution for select-invoices-order-desc. I think that this pool was really badly designed, I find it unacceptable, I asked my establishment and he told me that it was not the establishment but a commit a few weeks ago I hope this message will make you change this pool! Between the other exercise where there is a .php instead of the sql and the one I think it's the a in select-invoiaces-order-desc.sql
Change that for me!

**Comment by MSilva95** [comment]
Hello @devilsc0d3!
The sql content in question is not part of the 01 team. Please contact the school admin for any question or problem regarding that!
