### ISSUE TITLE
nlp-scraper audit

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2423]
nlp-scraper audit
---
1. Audit includes [a question](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper/audit#does-the-readme-file-give-an-introduction-of-the-project-show-the-username-describe-the-feature-engineering-and-show-the-best-score-on-the-leaderboard) that belongs to the [kaggle-titanic](https://github.com/01-edu/public/tree/master/subjects/ai/kaggle-titanic/audit) project.

2. Recommendation [to stop the scraper at 3 articles](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper/audit#run-the-scrapper-with-python-scrapper_newspy-and-fetch-3-documents-the-scrapper-is-not-expected-to-fetch-3-documents-and-stop-by-itself-you-can-stop-it-manually-does-it-run-without-any-error-and-store-the-3-files-as-expected) is not very good. It should be advised to run the scraper to download all 300 articles. Like mentioned in https://github.com/01-edu/public/issues/2390#issuecomment-1902697037 we cannot push the CSV files to school Gitea due to file size limitations. Therefore the auditor should run the scraper to download all the articles.

3. The auditors are assigned from the pool of all students not only the ones who took the AI branch, so asking the auditor to evaluate [learning curves](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper/audit#do-the-learning-curves-prove-the-topics-classifier-is-trained-correctly---without-overfitting) is not a very good idea. A random person is unqualified to evaluate the learning curves without any background knowledge.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you so much for all the feedback!
