### ISSUE TITLE
btreedeletenode subject

### ISSUE THREAD

**Issue by amaftah** [01-edu/public#2424]
btreedeletenode
when i submit the exercise i get this error
 # github.com/01-edu/go-tests/tests/btreedeletenode_test
tests/btreedeletenode_test/main.go:117:41: cannot use selectedS (variable of type *piscine.TreeNode) as type string in argument to student.BTreeDeleteNode

**Comment by MSilva95** [comment]
Hello @amaftah! Can you tell me if it happens in the ques or in the exam? Also can you provide your solution here please?

**Comment by amaftah** [comment]
hey @MSilva95 it happen in  quest12, i tried to modified the main.go it did work , thanks for your time
