### ISSUE TITLE
Cybersecurity - Project Local

### ISSUE THREAD

**Issue by mathisen99** [01-edu/public#2427]
The OVA image provided can't be used on our m1 machines at campus.
We can only run UTM as hypervisor, there is virtualbox Beta versions for M1 but that version is extremly limited to what it can run.

I assume the OVA image is also created for amd64 architecture and not arm64.

i tried to convery the image to qcow2 and mount the vmdk disk image into UTM but that failed badly.
i also tried to virtualize x64 arch in UTM, bad that also failed.

Thanks!

**Comment by nprimo** [comment]
Hi @mathisen99, thank you for the feedback. We are already working on this and we will try to update the available resources with some "M-compatible" ones as soon as possible.

**Comment by lvisgrit** [comment]
Hi @nprimo, it's been 3 months. What is the current update on this issue?

**Comment by nprimo** [comment]
Hi @lvisgrit, unfortunately we don't have any update yet. Our team is working on this and we'll give an update here as soon as we have some news.

**Comment by lvisgrit** [comment]
What is the estimated timeline for fixing this @nprimo? Our school uses only macOS. We have been stuck on this and we have strict deadlines.

**Comment by nprimo** [comment]
Hi @lvisgrit @mathisen99, the project `local` (and `hole-in-bin` that had a similar issue) have now a VM compatible with Apple Silicon machines. 
Thank you for your patience :pray:
