### ISSUE TITLE
divmod subject

### ISSUE THREAD

**Issue by brownajuoga** [01-edu/public#2441]
divmod
---
package piscine

func DivMod(a int, b int, div *int, mod *int) {
	*div = a / b
	*mod = a % b
}

**Comment by brownajuoga** [comment]
failed to run

**Comment by MSilva95** [comment]
Hello @brownajuoga !
Is this still an issue to you? 
What is the error message you received?

**Comment by MSilva95** [comment]
If needed please reopen the issue.
