### ISSUE TITLE
pandas audit

### ISSUE THREAD

**Issue by jo-eman** [01-edu/public#2460]
pandas
---
For question 11 in excercise 2 audit is expecting values that are not in the dataset:

from https://github.com/01-edu/public/tree/master/subjects/ai/pandas/audit

   ```Date
    2006-12-16    3.053475
    2006-12-17    2.354486
    2006-12-18    1.530435
    2006-12-19    1.157079
    2006-12-20    1.545658
                    ...
    2010-12-07    0.770538
    2010-12-08    0.367846
    2010-12-09    1.119508
    2010-12-10    1.097008
    2010-12-11    1.275571
    Name: Global_active_power, Length: 1433, dtype: float64
    
   ```
   This dataset does not contain data after 2010-11:
   https://assets.01-edu.org/ai-branch/piscine-ai/household_power_consumption.txt

**Comment by nprimo** [comment]
Hi @jo-eman, thank you for the feedback. I have checked the dataset, and it contains data that can lead to the expected answer: the dataset provided might not be already ordered.

Have you tried to print the dataset ordered by date, for example?

**Comment by nprimo** [comment]
Feel free to comment if you're still facing any issues linked to this topic :)

**Comment by nprimo** [comment]
Hi @jo-eman, thank you again for the input. After further investigation, I found out that there were other discrepancies in other questions related to exercise 2. I have opened a PR to fix these issues
