### ISSUE TITLE
emotions-detector subject audit script execution references

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2462]
emotions-detector audit
---
The audit refers to two script executions:

- `python predict.py`
- `python predict_live_stream.py`

However, in the [preliminary](https://github.com/01-edu/public/tree/master/subjects/ai/emotions-detector/audit#preliminary) section the required project structure defines scripts to be inside `scripts` folder. Therefore to avoid confusion and make the audit easier to follow, the executions should be listed as:

- `python scripts/predict.py`
- `python scripts/predict_live_stream.py`

**Comment by nprimo** [comment]
@jarmo-seljamaa, thank you for the feedback. I will open a PR to make this clear.
