### ISSUE TITLE
insert-genre subject

### ISSUE THREAD

**Issue by 4skl** [01-edu/public#2463]
insert-genre
---
Error : Missing student solution for insert-genre
With valid code in file 
`primitive-declarations.php` :
```php
INSERT INTO genres (Name) VALUES ('Electro');
```
I don't understand the issue.

**Comment by 4skl** [comment]
You need to create an empty `primitive-declarations.php` file and have `insert-genre.sql` with the right code which isn't specified by the instructions and a bit misleading

**Comment by MSilva95** [comment]
Hello @4skl!
This content is was not done by us, please speak to some admin on the school you're at. Thank you for the feedback!
