### ISSUE TITLE
Suggestion for improvement - ARMY-OF-ONE Gaming Project

### ISSUE THREAD

**Issue by Valkamo** [01-edu/public#2482]
**Describe the bug**
In this is task it is specified that the student should use "aim-offset" for head movement. Whilst this may have been standard practice a few years ago, the adoption of Unreal Engine 5 and associated techniques, means that methods involving the "control rig" are far more up to date and in line with industry standards. 

Doing this is by no means easier, and does not result in lightening the task load / complexity, but it is better practice and prepares one for real-world tasks in GAMING.

For instance, the Unreal Engine 5 documentation states the following:

_"What is a Control Rig?
Control Rig is Unreal Engine's solution to animating characters directly in the engine."_

[](https://docs.unrealengine.com/5.0/en-US/how-to-create-control-rigs-in-unreal-engine/)

**Users**
Students following the GAMING specialisation, grit:lab, Åland.

**Severity**
(❗️minor)

**Type**
(🗂️ documentation)

**To Reproduce**
N/A

**Workarounds**
Remove limiting constraints in the task description (we for instance have treated it as more of a "suggestion")

**Expected behavior**
Similar, but just better practice. By no means easier, or a "shortcut".

**Attachments**
N/A

**Desktop (please complete the following information):**

- OS: Mac OS, Sonoma
- Browser: N/A
- Unreal Engine
- Version: 5

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nprimo** [comment]
Hi @Valkamo, thank you for your feedback! I will open a PR to add Control Rig as an allowed technique to achieve the final result
