### ISSUE TITLE
[BUG]  Mobile-Dev piscine - Package task: can't be run on android

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2485]
When you try to run the app on a android device you get the error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Package 'com.example.package' from AndroidManifest.xml is not a valid Java package name as 'package' is a Java keyword.

Project: https://github.com/01-edu/public/tree/master/subjects/mobile-dev/package

**Comment by blueskiy01** [comment]
Can confirm, was victim of this and took 2 days to figure out it doesn't work with android device but works with desktop ios. 
<img width="1184" alt="Screenshot 2024-03-07 at 9 59 00" src="https://github.com/01-edu/public/assets/122779689/a7079dd7-0228-4761-ab98-024b28fa372f">

**Comment by nprimo** [comment]
Hi @sailordi and @blueskiy01 could you please add more details? The subject ask to develop a library using a [Flutter package](https://pub.dev/packages/sqflite) that supports iOS, Android and MacOS.

**Comment by sailordi** [comment]
@nprimo 
When you create the project package the module name automatically becomes package. This means a package named package is created for Android. In Kotlin / Java the word package is a keyword which can cause the app to not run on Android. This means we have to change the module name when creating the project to get it to run on Android which is not something that we should have to do to get a project to work.

**Comment by nprimo** [comment]
Hi @sailordi, thank you for the additional information. 

In the subject it is stated:
> In the end you should be able to import it like:
> ```dart
> import 'package:note/note.dart';
> ```

I assume the package name should be `node` and not `package`. (I am assuming that in the above comment `module` is used as an equivalent of `package`). Was the error occurring when the name of the package was `package` and the import statement was as follows?
```dart
import 'package:package/note.dart';
```

**Comment by nprimo** [comment]
@sailordi I am still confused about the cause of the issue. The subject ask to create a package (not an application) name `note` (so far no issues should arise due to "naming conflicts"). The subject also refers to a previously made application (`secure-note`) that could use the classes implemented in this package. Therefore, where is the `package` application coming from?

**Comment by nprimo** [comment]
Hi @sailordi, thank you for the clarification: now everything is clear :)

I will update the subject to have a direct link to the referred project. Besides that, the subject looks good to me: it is not required to create an app with the exercise name and, overall, it is always a good practice to use key words to name your apps/libraries/packages... 
If there are other things that could improve feel free to comment here.
