### ISSUE TITLE
credit-scoring datafiles messed up, important info not linked

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2486]
credit-scoring
---
The [Files needed in this project](https://github.com/01-edu/public/tree/master/subjects/ai/credit-scoring#files-needed-for-this-project) refers to 2 zip files. These files are a complete mess.

- The 001.zip contains all the required files of the project EXCEPT `instalments_payments.csv` but WITH an extra `home-credit-default-risk.zip` inside of the other zip that contains a duplicate copy of all required files of the project INCLUDING the `instalments_payments.csv`.
- The 002.zip contains `instalments_payments.csv` separately.

As a result of that the downloaded files are 1.44 GB together, while it should be sufficient to provide only the `home-credit-default-risk.zip` file that contains all required files and is only 721.6 MB.

Additionally: the repo contains an [image file](https://github.com/01-edu/public/blob/master/subjects/ai/credit-scoring/data_description.png) and a [readme_data.md](https://raw.githubusercontent.com/01-edu/public/master/subjects/ai/credit-scoring/readme_data.md) that are crucial in understanding the relations of the datafiles. However, this image nor the readme file don't have a single reference in the task description, hence it does not appear on our study platform. How are the students supposed to get this information that way?

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for your feedback
