### ISSUE TITLE
[BUG] piscine-ui/rules/grids

### ISSUE THREAD

**Issue by blueskiy01** [01-edu/public#2491]
**Describe the bug**
In [this task](https://github.com/01-edu/public/tree/master/subjects/user-experience/piscine-ui/rules), "Open these 5 images on Figma and draw lines and grids every time you find aligned elements". There was no link provided to the images.
**Users**
Piscine UI participants

**Severity**
 (‼️ major)  

**Type**
(🖌️ ui) (🗂️ documentation)

**Comment by healingdrawing** [comment]
> Hello @blueskiy01! We will get in contact with the creator of the branch so that she can give us the images and we will make it right!

Three weeks... 0 result, looks like the 1 was lost somewhere.

Next time , before write the response, first think about read both the task description and the audit section. Then you will see that any pictures of the site where some content(elements) placed in imagined columns and rows, obviously can be used as fix of the task bug. It is obviously about 50%+ of internet shops. And you do not need to contact the creator, and waiting for weeks. It is the 10 minutes deal, especially for such professional, who is ready to take responsibility for time of other persons.

The second (easiest) solution can be just change both, the task and the audit section, from specific pictures of the sites to pictures of the sites of your choice (this approach actively used in the next sections of the same task ).

**Comment by healingdrawing** [comment]
For emergency case this can be used. Feel free to use it
![picture-5](https://github.com/01-edu/public/assets/39751647/9a8c247c-31b5-4711-af44-c289861a7d18)
![picture-4](https://github.com/01-edu/public/assets/39751647/db1465be-3072-461d-9102-0a3bbe85e9f3)
![picture-3](https://github.com/01-edu/public/assets/39751647/089b9c6b-c72b-46fd-b98a-be048c90c615)
![picture-2](https://github.com/01-edu/public/assets/39751647/9e1f0cf6-2441-4737-8725-99ecde7cdcce)
![picture-1](https://github.com/01-edu/public/assets/39751647/63590f63-7cf9-4ea5-aba7-092855a7e538)

**Comment by Oumaimafisaoui** [comment]
Hello @healingdrawing ,
Thank you for your feedback, and we understand your frustration, but the provided alternative attachment does not meet the subject's requirements and the new fix made by our UX/UI contributor does have a more suitable material to the exercise. We thank you for your patience, you should be able to access the changes shortly after this response.
