### ISSUE TITLE
[ADMIN OBJECTS FORM] Add Drag'n'drop

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#25]
We need children and attributes to be drag'n'dropable to reorganized them easily.

<img width="1552" alt="Screenshot 2019-04-15 at 18 41 16" src="https://user-images.githubusercontent.com/4631239/56153527-49e1e500-5fae-11e9-853b-b5acaaeb46f0.png">
<img width="1552" alt="Screenshot 2019-04-15 at 18 41 19" src="https://user-images.githubusercontent.com/4631239/56153528-4a7a7b80-5fae-11e9-8076-f8dda01e85b8.png">

**Comment by bde-maze** [comment]
done
