### ISSUE TITLE
friend-support subject

### ISSUE THREAD

**Issue by kirsikapiiskop** [01-edu/public#2500]
friend-support
---
In some of the test cases if you fail it says + is actual - is expected but it is the other way around.

**Comment by MSilva95** [comment]
Hello @kirsikapiiskop!
Im going to take a look at the tests, meanwhile can you provide your solution so that i can replicate the error?

**Comment by MSilva95** [comment]
feel free to reopen if the issue is persists, at the moment we weren't able to reproduce the error
