### ISSUE TITLE
bloody-sunday subject

### ISSUE THREAD

**Issue by yomarhub** [01-edu/public#2502]
bloody-sunday
---
Subject not shown
![image](https://github.com/01-edu/public/assets/144997613/58c45762-239c-4b30-929b-7ac04e1bd0c4)

**Comment by nprimo** [comment]
Hi @yomarhub, the exercise was renamed and substituted more than 1 year ago with an equivalent one called `sunny-sunday` :) Please, get in contact with your local managers to update the local configuration settings.

**Comment by FireCheck** [comment]
> Hi @yomarhub, the exercise was renamed and substituted more than 1 year ago with an equivalent one called `sunny-sunday` :) Please, get in contact with your local managers to update the local configuration settings. 

Ok thanks.
