### ISSUE TITLE
primitives subject

### ISSUE THREAD

**Issue by AbdallahYnov** [01-edu/public#2508]
primitives
---
Error: Get repository info failed: Not Found

**Comment by nprimo** [comment]
Hi @AbdallahYnov, could you provide us with a little bit more information about the issue?  
Is this the error message you're getting from the platform? If so, have you checked if you have submitted your solution correctly?

**Comment by nprimo** [comment]
@AbdallahYnov, if you're still having a problem with this exercise, please, feel free to open a new issue with some additional information as described above :)
