### ISSUE TITLE
[FEATURE] crud-master project difficult on MacOS + ARM64 CPU

### ISSUE THREAD

**Issue by jo-eman** [01-edu/public#2518]
The project description at https://github.com/01-edu/public/blob/master/subjects/devops/crud-master/README.md requires to use virtualbox 

We use macs at grit:lab and VirtualBox 7.0.8 Developer preview for macOS / Arm64 (M1/M2/M3) have not worked well as provider for Vagrant this far.

It would be nice if the project could be updated with some methods that work equal on all big platforms, or more specific instructions what to use on mac, or some workaround suggested for Mac with ARM cpu

**Comment by nprimo** [comment]
Hi @jo-eman, thank you for the feedback. We will update the subject and audit to be compatible with new MacOS Arms CPUs machines.
