### ISSUE TITLE
unable to access required data for system-monitor

### ISSUE THREAD

**Issue by akhaled01** [01-edu/public#2519]
unable to access required data for system-monitor
---

Hi there! for this project, we are required to access some data from the `/proc` directory and display it using `ImGui`,  yet Im facing some issues regarding the access of data, as some computers dont allow access to certain sensors (like CPU temp / fan speed), and so, there is no way to get that data at all.

For example, getting the CPU temp involves running the command `cat /proc/acpi/ibm/thermal`, but `/proc/acpi/ibm/thermal` directory does not exist on my PC. So i am unable to work on the project.

Are there any alternatives or steps i should follow?

**Comment by nprimo** [comment]
Hi @akhaled01, could you please let us know on which machine/OS are you currently working on? For example, are you on a Linux distro, AMD or macOS ARM machine?

The provided commands in the audit are specific but you should be able to find alternatives if those specific paths are not present in your PC.

**Comment by akhaled01** [comment]
Hi there @nprimo. 

I am running Ubuntu 23.10 (mantic minatour), which is also dualbooted with windows 11

My CPU is a AMD Ryzen 7 7730 with radeon graphics.  

I tried multiple commands, and looked all over the `sys` directory to find anything for the temperature and fans, but no luck.

I will definitely keep looking and will update you guys if i find anything. But so far nothing.

**Comment by nprimo** [comment]
@akhaled01 I close the issue since there is nothing we can do (at the moment). Feel free to comment here if there is anything else related to this ticket that will come up in the future :)
