### ISSUE TITLE
iterativefactorial subject

### ISSUE THREAD

**Issue by Richard-AungKhantMin** [01-edu/public#2533]
iterativefactorial
---

The question does not say anything about the limit of the input.
How would the programmer know what to do?

**Comment by nprimo** [comment]
Hi @Richard-AungKhantMin, the subject specifies:
```
...
Errors (non possible values or overflows) will return `0`.
...
```

This sentence is providing all the information needed to know how the function should behave in all edge cases. 

What do you think is missing?

**Comment by Richard-AungKhantMin** [comment]
> @Richard-AungKhantMin please open a new issue or feel free to comment here if there is anything else you would like to add to the conversation :)

I figured it out why. There's a limit that int type can handle.
