### ISSUE TITLE
[ONBOARDING] - input type date doesn't appear in safari

### ISSUE THREAD

**Issue by atlekbai** [01-edu/public#254]
**Describe the bug**
Datetime choosing input in Sign up doesn't work

**To Reproduce**
1. Use Safari as browser

**Screenshots**
<img width="717" alt="изображение" src="https://user-images.githubusercontent.com/29381624/61451053-4f1e4980-a97a-11e9-8e57-37e279bac3cc.png">

**Desktop (please complete the following information):**
 - Browser safari 12.0.3 (14606.4.5)

**Smartphone (please complete the following information):**

**Type**
Add the correct label to your bug report : minor

**Priority**
Add the correct label to your bug report : normal

**Subject**
Add the correct labels to your bug report : onboarding

**Comment by lfoussat** [comment]
the browser controls the display of input type date, we can't change it
