### ISSUE TITLE
descendcomb subject

### ISSUE THREAD

**Issue by lotoussa** [01-edu/public#2541]
descendcomb
---
The participant have an error (newline problem), but the runner show a different error, that doesn't respect the subject :
![image](https://github.com/01-edu/public/assets/66522867/355c1d06-6abb-4959-ac86-e6cf382a2eaa)
https://platform.zone01.gr/intra/athens/piscine-go/quest-10/descendcomb?event=5

**Comment by MSilva95** [comment]
@lotoussa If there is a problem with a new line it needs to be fixed...
Also what is the other error? what are you trying to show with that picture? Please add more info in the issue, like who is  "The participant" and what is the runner error that doesn't respect the subject.

**Comment by lotoussa** [comment]
the participant said: the subject ask for this output:
`... 02 00, 01 00'
but the runner ask for this output:
`... 02 00, 01 '

but when the participant fix his newline problem, the runner said BIM.

**Comment by MSilva95** [comment]
The runer asks for the rigth output... what is happening is that the output doesn't fit in the console, if the student do a zoom out in the window it will show the correct thing:

![image](https://github.com/01-edu/public/assets/53977751/0b031d8a-a3f0-45d9-82d8-46ab27c5bc00)

**Comment by lotoussa** [comment]
ok thank you for feedback
