### ISSUE TITLE
[BUG] Mobile: Chess task - Link in resourses not working 

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2542]
In the Chess task (https://github.com/01-edu/public/tree/master/subjects/mobile-dev/chess) recources there is a link (https://github.com/01-edu/public/blob/master/subjects/mobile-dev/chess/resources/long-algebraic-notation) that should show the chess move notation, but the link leads nowere

**Comment by MSilva95** [comment]
Hello @sailordi thanks for the feedback I will take a look into it!
