### ISSUE TITLE
Made a change to my original issue...cant reopen it so made a reference

### ISSUE THREAD

**Issue by GuitarGuy99** [01-edu/public#2546]
When running this locally it works perfectly fine... as well as any other terminal/IDE i dont see why someone would have to recreate the EXACT file to pass a test if it performs the same functionality...for example i could declare 'i' as type rune beforehand and it would not pass due to the nature of diff?
<img width="532" alt="image" src="https://github.com/01-edu/public/assets/122157280/f29cbf3f-29b6-4cfa-8d85-a4fd06562995">
Is this not the expected outcome/result to pass the challenge?

Also im really upset because due to this i was unable to complete Quest2...and therefore was totally unprepared for Exam1...despite having the knowledge to probably pass...i wanted to complete all tasks beforehand. I missed exam 1 due to this. I attended the Open Day and was told there was a Discord Server i could join...but there isn't one. If there was one, the response time given the ability to contact ANYONE from 01Founders would be far quicker and the problem could be resolved in minutes rather than the day it took to reply (i only had 11 hours to finish the WHOLE of Quest2). Does this mean i failed the selection pool despite actually completing the task? Will i get a second chance? I dont know...because i still cant get past the damn 'diff' error.

Please provide a link to a Server or i'll make my own and post a link perhaps? It would be a good asset to 01Founders.

Sorry for the rant, i am just really annoyed right now about it all

_Originally posted by @GuitarGuy99 in https://github.com/01-edu/public/issues/2540#issuecomment-2068570150_

**Comment by GuitarGuy99** [comment]
here's an invite link that will never expire ...https://discord.gg/dHtXskNZSK ... might wanna talk to me there about it and get this set up?

**Comment by MSilva95** [comment]
Hello again @GuitarGuy99!
Like i said, you have a badly formatted code.
Just add a new line at the end of your code and it will pass!
One advice for the next time, you should talk with the people in the school, your colleges, sometimes its easier and faster to solve problems like that.
Regarding the discord chat i dont have knowledge of any, maybe some admin on the school can help with that. 
Let me know if it passed, have a nice day!
