### ISSUE TITLE
[INVALID] slicer subject

### ISSUE THREAD

**Issue by AntoineEugenie** [01-edu/public#2550]
slicer
---

Create a function named slice that works like Array.slice() and String.slice().

It takes 3 arguments:

    string or array to process.
    starting index.
    **optional ending index.**
() => slice('abcdef',0,2)==='ab'
 012 abc

**Comment by nprimo** [comment]
@AntoineEugenie could you please provide more information about the issue you're facing? :)

**Comment by nprimo** [comment]
@AntoineEugenie feel free to open a new issue with more details if you're still having problem with this exercise :)
