### ISSUE TITLE
Mobile dev: stock-market task [no way to get complete stock price data] 

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2551]
In the mobile stock-market task (https://github.com/01-edu/public/tree/master/subjects/mobile-dev/stock-market) the resource given (https://github.com/01-edu/public/tree/master/subjects/mobile-dev/stock-market/resources/mock-stock-data-server) can not be used to fetsh a stocks complete price history (From start to current date). 

This will makes it hard to impossible to do the Historical Charts. 

Also the .csv files only contain data up to 01 of April 2020 so data from then untill the current date would need to be generated.

**Comment by nprimo** [comment]
Hi @sailordi, thank you for the feedback. Have you tried to use the provided server to generate the **mock** data? The server is using the historical data till 2020 to mock real time market data - the values are not the real ones.
We provided this solution to avoid relying on third party APIs that can change their usage condition and make this project hard (or impossible) to complete.

**Comment by sailordi** [comment]
@nprimo The Server provided can only generate mock current data. It can not fetch all historical price data for a stock. The historical price data is necessary according to the task description. 

The serve has only two endpoints. One to retrieve current data for the specified symbol and one to display a list of available stock symbols.

There is no way to get all historical price data for a stock with the mock server. 

The historical price data is needed for 

Historical Data: Create a page that displays historical data for a chosen stock. This feature will allow users to view and analyze the past performance of a particular stock.

and

Historical Charts: Provide historical charts of stock prices to help users visualize the stock performance over time. Implement a page that displays charts for the selected stock's price history.

**Comment by nprimo** [comment]
@sailordi with this PR the mock-data server is going to have an extra endpoint to fetch historical data as well
