### ISSUE TITLE
Mobile dev: sky-map task [No api or other recources]

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2552]
For the sky-map task (https://github.com/01-edu/public/tree/master/subjects/mobile-dev/sky-map) there is no link to any api or other recources that could help with making the app making it very difficult to make the app in flutter

**Comment by MSilva95** [comment]
Hello @sailordi!
The purpose is for you to look for a public api at your choice, so that's why we don't provide one.
Good luck with your task and thank you for your feedback!
