### ISSUE TITLE
[MISLINKED] Guess-It-1 ZIP file 

### ISSUE THREAD

**Issue by YusufMJ** [01-edu/public#2553]
guess-it-1
---
The ZIP file in the audit page is linked to the old non dockerized version, while it is linked to the new dockerized ZIP file during the project description page. 
URL in project description: https://assets.01-edu.org/guess-it/guess-it-dockerized.zip
URL in audit questions: https://assets.01-edu.org/guess-it/guess-it.zip

![guess-it-1-aq](https://github.com/01-edu/public/assets/132362556/5b852b88-c2d2-40d9-90d0-935694651302)
![guess-it-1-pdd](https://github.com/01-edu/public/assets/132362556/d7b27947-329a-4401-a665-c032da44ab6e)

**Comment by MSilva95** [comment]
Hello @YusufMJ  i will take a look at the issue thanks for the feedback!
