### ISSUE TITLE
cl-camp4 subject

### ISSUE THREAD

**Issue by atouba** [01-edu/public#2560]
cl-camp4
---
I've been stuck in this exercise for hours, and now only after I've changed my solution that it got accepted and I passed the exercise. I'm 100% positive that my previous solution that didn't pass the automatic tester is correct. So I really want to know what's wrong with it. Because otherwise if it's actually correct as it fulfils what the exercise asks for, then there is a problem with the automatic tester code. 

the code
```shell

if [[ $(find . -name 'a*') ]]; then
	find . -name 'a*'
elif [[ $(find . -type f -name '*z') ]]; then
	find . -type f -name '*z'
else
	find . -type f -name 'z*a!'
fi

```

**Comment by MSilva95** [comment]
Hello @atouba!

Here's the output of that code on the test folder:
```console
./folder1/ac
./folder1/az
./folder1/ab
./folder2/ac
./folder2/az
./folder2/ba/alphabetz
./folder2/ba/ac
./folder2/ba/aa
./folder2/ba/aa/alphabetz!
./folder2/ab
./folder2/alphabet
./folder2/aa
./folder2/aa/az
./folder2/aa/ba/ab
./folder2/aa/aa
```

and the output of a correct sol:

```console
./folder1/cz
./folder1/bz
./folder1/ac
./folder1/za!
./folder1/az
./folder1/ab
./folder2/cz
./folder2/bz
./folder2/ac
./folder2/za!
./folder2/az
./folder2/ba/alphabetz
./folder2/ba/ac
./folder2/ba/aa
./folder2/ba/aa/alphabetz!
./folder2/ba/aa/cz
./folder2/ba/aa/za!
./folder2/ab
./folder2/alphabet
./folder2/aa
./folder2/aa/az
./folder2/aa/ba/bz
./folder2/aa/ba/ab
./folder2/aa/aa
```
