### ISSUE TITLE
Game Branch Audit System

### ISSUE THREAD

**Issue by maryamkheirkhah** [01-edu/public#2561]
**Describe the bug**
In the audit questions there are 2 issues:

1-Problem with Putting Files into Gitea Repository:
When students try to put files into the Gitea repository, they can't upload files that are too big, larger than 1 MB. This is a big issue because gaming projects usually have big files that need to be uploaded. Because of this, students can't upload the whole project, which means they fail the first question of the audit.

2- Students are required to complete bonus tasks as part of the audit process. If they don't do these bonuses, they fail the project.

**Users**
Students following the Gaming specialization, grit:lab, Åland.

**Severity**
(⚠️ critical)

**Type**
(⚙️ functionality)
**To Reproduce**
N/A

**Workarounds**
it would be better to increase the size limit of files to push to gitea and then allow us to use git LFS too,Since gaming projects usually have big files, it's important to make it easier for students to handle them and not penalize them for not doing bonus tasks.

**Expected behavior**
students should be able to do the audit without any problems.
**Attachments**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nprimo** [comment]
@maryamkheirkhah thank you for the feedback! We are going to look at how we can improve this
