### ISSUE TITLE
pig_latin subject

### ISSUE THREAD

**Issue by Ainarnomm** [01-edu/public#2565]
pig_latin
---
println!("{}", pig_latin(&String::from("queen")));  gives wrong output 
$ cargo run
eenquay
$

it should be
$ cargo run
ueenqay
$
In definition:
If a word starts with a consonant followed by "qu", move it to the end of the word, and then add an "ay" at the end.

word starts with consonant but is not followed by "qu".

**Comment by nprimo** [comment]
Hi @Ainarnomm thank you for your feedback! We'll update the subject to be coherent with what is expected from the solution
