### ISSUE TITLE
[BUG] Issue in the `stealth-boom` gaming project

### ISSUE THREAD

**Issue by Valkamo** [01-edu/public#2566]
**Describe the bug**

In the task description it says: 

"The basics assets you will need for this project can be found in the [Stealth-Boom.zip](https://assets.01-edu.org/Unreal-Engine-Projects/StealthBoom.zip) file. It contains the basic animations, character, enemies and props you will need for this project."

After downloading the StealthBoom.zip it only contains Drone.fbx and the task description in a docx file.

So in other words the file provided to us students is missing the basic animations, character, enemies and props. 

**Users**

Students following the Gaming specialization, grit:lab, Åland.

**Severity**

(‼️ major)

**Type**

(⚙️ functionality), (🗂️ documentation)

**To Reproduce**

Downloading the file

**Workarounds**

It would be helpful is you could provide the files as mentioned in the task description.

**Expected behavior**

The zip file should contain what is said in the task description. 

**Attachments**

N/A

**Desktop (please complete the following information):**

OS: mac OS, Sonoma
Browser: Google Chrome
Unreal Engine : 5.3.2
Epic Game Launcher: 16.1.1

**Smartphone (please complete the following information):**

N/A

**Additional context**
N/A

**Comment by nprimo** [comment]
@mario1599 @Valkamo thank you for reporting this inconsistency. We'll be coming back to you as soon as we are going to work to fix this. Unfortunately, we don't yet have a time estimation of how long it will take us.

**Comment by EldritchGriffin** [comment]
Hi @Valkamo 

The issue with the assets has been resolved. I've also made slight modifications to the subject. If you run into any further issues, feel free to open a new ticket.

Thanks!
