### ISSUE TITLE
matrix_ops subject

### ISSUE THREAD

**Issue by abdotop** [01-edu/public#2567]
matrix_ops
---
hello in fact I wanted to report an error on the quests matrix, matrix_ops and matrix_mult you ask for the files `matrix/src/ops.rs` for the ops and `matrix/src/mult.rs` for the mult but the program tests the libraries matrix_ops and `matrix_mult`.
![Screenshot from 2024-05-15 11-58-59](https://github.com/01-edu/public/assets/119938180/6069cad8-63ab-4630-9681-a5cbd1e5def4)

**Comment by nprimo** [comment]
Hi @abdotop, thank you for the feedback! As far as I can see, the expected files are in line with the error you're receiving:
- for `matrix_mult` -> "expectedFiles": ["matrix_mult/src/lib.rs"]
- for `matrix_opts` -> "expectedFiles": ["matrix_ops/src/lib.rs"]
(These values were updated in February 2023)

The issue might be that the curriculum you're seeing is still referring to an older version: please, get in contact with your school admins to update the referenced used

**Comment by abdotop** [comment]
Hello to you too. Yes, that's exactly it and it's finally been sorted out. Thank you
