### ISSUE TITLE
point subject

### ISSUE THREAD

**Issue by atouba** [01-edu/public#2570]
After using the code to be copied and making the necessary changes so that it works, I get this
```
Cheating:
	TYPE:         	NAME:  	LOCATION:
	illegal-import	fmt    	point/main.go:3:8 rintf("x = %d, y = %d\n",points.x, points.y)
}
```
Printf is from fmt package that was already in the code to be copied, which seems that it's illegal to call

**Comment by atouba** [comment]
> Hello @atouba! That's why we ask in the subject the following:
> 
> `- The necessary changes must be applied so that the program works.`

Okay I get that, in my case I used two functions (printstr and printnbr) from two different previous quests to print the output, that's okay for me, I think the issue is, maybe, how can someone else who, for example, didn't do PrintNbr from quest-02 which was optional, solve this exercise which is required, that considering that combining PrintNbr and PrintStr is the only way to get output printed (which is, probably, not). I guess the goal of the exercise was to get the Pisciner to know how to make a structure that has x and y int, rather than how to print "x = %d, y = %d\n"

**Comment by MSilva95** [comment]
Hello @atouba !
We understand the frustration but we actually do this on purpose so that the student is forced to go back and do some of the bonuses.
Because for example PrintNbr is something that will be used multiple times so eventually the student has to be forced to do it.
