### ISSUE TITLE
ascii-art-color subject

### ISSUE THREAD

**Issue by yassinekharkhache** [01-edu/public#2571]
ascii-art-color
---
in the subject of ascii-art-color they mention "set of letters" but they have to say "word" or "sub string" 
because in audit there's a case like this
go run . "guys" "hey guys"
in order to colour "guys" but "y" of "hey" shouldn't be coloured

**Comment by zanninso** [comment]
Hello @yassinekharkhache following out discussion on Linkedin I will review the subject and the audit then apply the required changes.
Thank you
