### ISSUE TITLE
displayfile subject

### ISSUE THREAD

**Issue by krsecprof** [01-edu/public#2574]
displayfile
---
Package io/ioutil. is out of date and can't be used to complete this exercise. 

As is the command "echo "Almost there!!" > quest8.txt" Instead of creating a file with contents "Almost there!!", It creates a file quest8.txt, with the last command that has been executed trough the terminal

**Comment by nprimo** [comment]
@krsecprof thank you for your feedback. Soon all the `io/utils` will be updated to the `io` module
