### ISSUE TITLE
Rust piscine Quest 9 Task Events error on testing

### ISSUE THREAD

**Issue by Ainarnomm** [01-edu/public#2583]
Hello

Testing events will give an error:

error: package `colored v2.1.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.68.2
Either upgrade to rustc 1.70 or newer, or use
cargo update -p colored@2.1.0 --precise ver
where `ver` is the latest version of `colored` supporting rustc 1.68.2

This has to be testing side problem as my version is 1.77 and I have removed colored dependency alltogether and still geting that error message

Best regards,
Ainar Nõmm

**Comment by nprimo** [comment]
@Ainarnomm @mikkadler the issue should be fixed now. Please, let us know if you're still facing any problems with the exercise tests.

Please, remember to use the specified `colored` version in the subject

**Comment by mikkadler** [comment]
The issue is fixed. I was able to submit and pass the test. (did not use colored crate at all in my code)
