### ISSUE TITLE
events subject

### ISSUE THREAD

**Issue by LordWelldown** [01-edu/public#2586]
events
---
running the test for events fails, because the of a mismatch of the colored crate version requierments and the servers rust version. this is the output
```
error: package `colored v2.1.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.68.2
Either upgrade to rustc 1.70 or newer, or use
cargo update -p colored@2.1.0 --precise ver
where `ver` is the latest version of `colored` supporting rustc 1.68.2
```

**Comment by MSilva95** [comment]
Hello @LordWelldown!
This was solved here, <https://github.com/01-edu/rust-tests/pull/141/files>
Let us know if you still have this problem! Thank you for the feedback!

Same as: #2584
