### ISSUE TITLE
git subject

### ISSUE THREAD

**Issue by jgleggit** [01-edu/public#2588]
git
---
I think the line numbering mentioned is incorrect.
See what I think it should be below...
__________________________________________

# Default is "World"
name=${1:-"World"}
echo "Hello, $name"

    Make two separate commits:
---        The first commit should be for the comment in line 1.
---        The second commit should include changes made to lines 3 and 4.

+++        The first commit should be for the comment in line 3.
+++        The second commit should include changes made to lines 4 and 5.

**Comment by MSilva95** [comment]
Hello @jgleggit !
Good catch, i will change the numbers, thanks for the feedback!
