### ISSUE TITLE
ascii-art-output subject

### ISSUE THREAD

**Issue by vomolo** [01-edu/public#2595]
ascii-art-output
--- expected output on the question have an extra line. during the audit the expected output do not have this extra line

**Comment by MSilva95** [comment]
Hello @vomolo Can you please specify the question that you saw the extra line?

**Comment by vomolo** [comment]
Ascii art output

**Comment by MSilva95** [comment]
Yes, i understand that its that project, but in the audit there are many questions, i need to understand where did you saw the extra line, in which question?

**Comment by vomolo** [comment]
The extra line is not in the audit tests. It's on the actual question. The
ones we use to develop the program before audits

**Comment by vomolo** [comment]
Look at the tests on the question before we submit for audits, they have
extra lines. While the audit questions don't have that extra line

**Comment by MSilva95** [comment]
I think you mean the usage example in the actual subject right?
Here?
![image](https://github.com/01-edu/public/assets/53977751/e2680dc8-6099-4c33-a863-48b8f30cb037)

If that is the case those are not extra lines, they are the terminal prompt and `$` is the symbol indicating that the terminal is ready for input.
I understand the confusion, and i guess i could remove the one in the middle to avoid future misunderstandings.
