### ISSUE TITLE
[BUG]  No task called KAQUIZ (Mobil dev)

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2608]
In the platform for mobile dev there is a task called KAQUIZ, but there is no such task in the repo (subjects/mobile-dev)

<img width="325" alt="Screenshot 2024-06-26 at 16 54 27" src="https://github.com/01-edu/public/assets/18734845/3f52a8b1-02fa-4b6d-ad91-100ce357d5f3">

**Comment by nprimo** [comment]
@sailordi thank you for raising this issue!

**Comment by nprimo** [comment]
This issue should be fixed. @sailordi, feel free to comment here if there is anything else related to this still pending.

Thank you again for your feedback :)
