### ISSUE TITLE
sortintegertable subject

### ISSUE THREAD

**Issue by Satfie** [01-edu/public#2609]
sortintegertable
---
For some reason it gives me error 404, which tells me that i dont have access to the Gitea link to view the code. This is my first audit so i dont really know if it is a problem on my knowledge. please let me know.
Thanks.

**Comment by nprimo** [comment]
Hi @Satfie this exercise is not supposed to be audited. You should be able to see the subject and submit your solution directly on the platform. The solution is going to be tested automatically and not via audit.

Is this still an issue? Could you please share some screenshots or more information on why you thought this exercise was supposed to have an audit?

**Comment by nprimo** [comment]
@Satfie I will close this issue for the time being. Feel free to comment here or open a new issue if the problem persist
