### ISSUE TITLE
[GENERAL] localhost subject: ambiguous understanding 

### ISSUE THREAD

**Issue by alpapie** [01-edu/public#2642]
localhost
---
the server: "It can listen on multiple ports and instantiate multiple servers at the same time."

the configuration file: "The host (server_address) and one or multiple ports for each server.
The first server for a host:port will be the default if the "server_name" didn't match any other server."

 what sould be considered as a server :
- host:port ?
- host ?

**Comment by nprimo** [comment]
@alpapie you have access to the subject and the audit - all the information you need is provided there. If you're in doubt, try to replicate the behaviour of NGINX.

I hope this helps :) Good luck with the project
