### ISSUE TITLE
[DUPLICATE][BUG]  Issue `stealth-boom` subject

### ISSUE THREAD

**Issue by mario1599** [01-edu/public#2644]
stealth-boom
---
The provided zip file does not contain necessary assets.

![image](https://github.com/user-attachments/assets/1be71bea-d302-4ee7-adb5-98c787fbeb2d)

![image](https://github.com/user-attachments/assets/9a4920c2-7f25-4732-bbbe-c899ade82d77)

**Comment by HarryVasanth** [comment]
> [!NOTE]
> @01-edu/content: this issue is a duplicate of #2566
