### ISSUE TITLE
[BUG] `has-city` subject

### ISSUE THREAD

**Issue by shiiiiroo** [01-edu/public#2650]
has-city
---
![image](https://github.com/user-attachments/assets/71f432fc-7d47-4a11-86c9-67423018fae2)
nothing here in description

**Comment by nprimo** [comment]
HI @shiiiiroo, thank you for reporting this issue. [Here](https://github.com/01-edu/public/tree/master/subjects/has-city) you can find the subject of this exercise. We're going to fix this issue as soon as possible
