### ISSUE TITLE
[BUG] [CRITICAL] Chess project page not showing up after fail

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2655]
After failing the chess project in mobile the chess page on the platform is black and it wont show me the page again

<img width="1596" alt="Screenshot 2024-07-22 at 17 32 31" src="https://github.com/user-attachments/assets/a3cf1fb9-3f35-43cf-b926-08248af1ae63">

<img width="1604" alt="Screenshot 2024-07-22 at 17 34 40" src="https://github.com/user-attachments/assets/248a4ef9-3ece-4300-934d-4665a462a0ac">

**Comment by nprimo** [comment]
Hi @sailordi thank you for the feedback. Our team has already fixed this bug and the new release should be out soon

**Comment by sailordi** [comment]
@nprimo closing this it seems to work again
