### ISSUE TITLE
cl-camp1 subject

### ISSUE THREAD

**Issue by lfarssi** [01-edu/public#2656]
something wrong here!!!

**Comment by Oumaimafisaoui** [comment]
Can you please elaborate?

**Comment by HarryVasanth** [comment]
> [!IMPORTANT]
> ## 🚫 @lfarssi: This issue has been closed due to lack of context/clarity/substance/responsiveness!
> If you find there is something wrong with a subject/exercise/feature, please feel free to open a new issue with an appropriate title, context and further details that would help our team to address the issue effectively. 
> 
> We could use the following information to help us resolve a potential issue:
> - The issue/error you are encountering from the platform
> - The solution you're trying to submit / steps to reproduce the issue/error
> - The screenshot of the issue/error
> - Any additional details
