### ISSUE TITLE
[ADMIN OBJECT FORM] - App crashes when selecting Function type in update

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#27]
The app crashes if we switch from 'Null' to 'Function' type in the Select component to define the type of the attribute.

1. Create an attribute with the 'Null' type if it doesn't exist yet and add it to the attributes list
2. Then go on this new added attribute and select the 'Function' type

It should be displaying the 'Function' input.

<img width="1552" alt="Screenshot 2019-04-15 at 18 51 15" src="https://user-images.githubusercontent.com/4631239/56154286-130cce80-5fb0-11e9-93ca-61b00b6c8c03.png">
 and the result is : 
<img width="1552" alt="Screenshot 2019-04-15 at 18 51 23" src="https://user-images.githubusercontent.com/4631239/56154302-1d2ecd00-5fb0-11e9-9822-22574ba316e4.png">

**Comment by bde-maze** [comment]
Fixed
