### ISSUE TITLE
printalphabet subject

### ISSUE THREAD

**Issue by Antonyftn** [01-edu/public#2714]
printalphabet
---
package main

import (
	"github.com/01-edu/z01"
)

func main() {
	for i := 'a'; i <= 'z'; i++ {
		z01.PrintRune(i)
	}
	z01.PrintRune('\n')

**Comment by MSilva95** [comment]
Hello @Antonyftn! 
Please provide details of the problem if you found one! 
Feel free to reopen the issue!
