### ISSUE TITLE
[QUESTION] `cl-camp3` subject

### ISSUE THREAD

**Issue by gbones** [01-edu/public#2717]
cl-camp3
---
Even though it seems I my outputs are the same as the desired ones I failed the test 
Is something that missed ?
 
5a6
> ./ba/aa
9d9
< ./ba/aa
13a14
> ./aa
18d18
< ./aa

**Comment by MSilva95** [comment]
Hello @gbones can you please provide your solution so we try to understand the problem?

**Comment by HarryVasanth** [comment]
> [!IMPORTANT]
> ## 🚫 @gbones : This issue has been closed due to lack of context/clarity/substance/responsiveness!
> If you find there is something wrong with a subject/exercise/feature, please feel free to open a new issue with an appropriate title, context and further details that would help our team to address the issue effectively. 
> 
> We could use the following information to help us resolve a potential issue:
> - The issue/error you are encountering from the platform
> - The solution you're trying to submit / steps to reproduce the issue/error
> - The screenshot of the issue/error
> - Any additional details
