### ISSUE TITLE
[QUESTION] go-reloaded subject

### ISSUE THREAD

**Issue by atouba** [01-edu/public#2718]
go-reloaded
---
It seems that there is a contradiction - a mistake in the subject and specifically in the last test case in the Usage section, regarding how ' should be handled. As per the subject:

> The punctuation mark ' will always be found with another instance of it and they should be placed to the right and left of the word in the middle of them, without any spaces. (Ex: "I am exactly how they describe me: ' awesome '" -> "I am exactly how they describe me: 'awesome'")

However, the last test case in the Usage section:
```
$ cat sample.txt
Punctuation tests are ... kinda boring ,don't you think !?
$ go run . sample.txt result.txt
$ cat result.txt
Punctuation tests are... kinda boring, don't you think!?
```

**Comment by MSilva95** [comment]
Hello @atouba ! 
thanks for the feedback, I will rephrase the example!
