### ISSUE TITLE
nrune subject

### ISSUE THREAD

**Issue by Tewicodes** [01-edu/public#2723]
nrune
---
.package piscine
.
.func NRune(s string, n int) rune {
.    if n > len(s) || n < 1 {
.        return 0
.    }
.    runes := []rune(s)
.    return runes[n-1]
.}

le correcteur m'indique une faute de frappe mais je ne la voit pas

**Comment by HarryVasanth** [comment]
> [!IMPORTANT]
> ## 🚫 @Tewicodes: This issue has been closed due to lack of context/clarity/substance/responsiveness!
> If you find there is something wrong with a subject/exercise/feature, please feel free to open a new issue with an appropriate title, context and further details (use the prebaked [issue templates](https://github.com/01-edu/public/issues/new/choose) that we provide) that would help our team to address the issue effectively. 
> 
> We could use the following information to help us resolve a potential issue:
> - The issue/error you are encountering from the platform
> - The solution you're trying to submit / steps to reproduce the issue/error
> - The screenshot of the issue/error
> - Any additional details
