### ISSUE TITLE
[BUG] quad subject

### ISSUE THREAD

**Issue by Warezzly** [01-edu/public#2729]
quad
---
 In the first team project (Quad), me and my team failed, and on the right side where it showed the issue it says "Does the function **returns** the value above?" (should say return instead)
 https://platform.zone01.gr/intra/athens/piscine-go/quad/?audit=103&event=77&details=open
![image](https://github.com/user-attachments/assets/8c83bfcc-1a18-40cc-923c-18181e452d83)

**Comment by MSilva95** [comment]
Thanks for the catch, we will fix it
