### ISSUE TITLE
[QUESTION] emotions-detector subject

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2746]
emotions-detector
---
Hi,
instructions says that accuracy should be 60% and audit says 70% and then 60% again.
As far as I can tell, it takes my laptop to burn for hours to get a model with millions of parameters to reach 60%. so unless I picked the wrong neural architecture; I would suggest that 60% is the right choice (people need to audit and train it on their machine too)

Instruction says that tensorboard is strongly recommended the audit question *ask* about tensorboard output

**Comment by Oumaimafisaoui** [comment]
Hello @fulverin ! Thank you for bringing these issues to our attention. We've reviewed your feedback and made the following corrections:

Accuracy requirement: We've clarified that the target accuracy is 60%. This has been consistently updated throughout the instructions and audit criteria.
TensorBoard: We've ensured that the instructions and audit questions are aligned regarding TensorBoard usage. It remains strongly recommended, and the audit now explicitly asks for TensorBoard output.

**Comment by fulverin** [comment]
> TensorBoard: We've ensured that the instructions and audit questions are aligned regarding TensorBoard usage. It remains strongly recommended, and the audit now explicitly asks for TensorBoard output.

hhhhuuuuuuuu .... if audit question ask explicitly for the output of tensorboard, that makes it mandatory and not recommended ?
