### ISSUE TITLE
[BUG] guess-it-1 subject

### ISSUE THREAD

**Issue by Rinrino** [01-edu/public#2749]
guess-it-1
---
The audit file is not working. Already report this to staff over 2 months ago. Still didn't get anything back.

**Comment by MSilva95** [comment]
Hello @Rinrino!
I wasn't able to replicate this issue, on my side all is working as expected.
![image](https://github.com/user-attachments/assets/b1a7318a-0fe5-4548-9acb-8fbce994e5fe)

Can you tell me in what "school"/"campus" are you having this issue?

**Comment by Rinrino** [comment]
Hi, thanks for your  quick reply.

It’s London campus.
As far as I remember, I follow the audit introductions. But it kept saying
can’t find the file.


2024年10月2日(水) 10:13 MSilva95 ***@***.***>:

**Comment by MSilva95** [comment]
Hello @Rinrino! 
We spoke to the support team, and they created a ticket for the school to update an attribute that is wrong on their side.

### SUP-1274

**Comment by Rinrino** [comment]
Hi! Thank you so much for your help!

2024年10月3日(木) 11:37 MSilva95 ***@***.***>:

**Comment by HarryVasanth** [comment]
@Rinrino The issue has been addressed by your local admins. 
Thank you!

**Comment by Rinrino** [comment]
Hi! Thanks a lot.

2024年10月17日(木) 0:47 Harry ***@***.***>:

**Comment by Rinrino** [comment]
Hi, I’m not so sure this got fixed.
I didn’t check the file at all.
Have you checked?

As far as I can see, the latest modify for audit folder is 6 months
ago…means nothing has been changed.

2024年10月16日(水) 23:56 Rin Yeh ***@***.***>:

**Comment by HarryVasanth** [comment]
Hello @Rinrino, 
As far as I know, on `16 October 2024` at `15:38`, the 01 Founders admins instructed us that it has been fixed. 
Please contact your local admin regarding the issue with the support ticket no `SUP-1274`.
Thank you.

**Comment by Rinrino** [comment]
Thank you, I will do that.

2024年11月5日(火) 17:05 Harry ***@***.***>:
