### ISSUE TITLE
[QUESTION] [AI] emotions-detector subject - `hack the CNN` optional or not ?

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2751]
**Describe the bug**
instructions say that `Hack the CNN` is optimal and very cool, audit validation say like it is mandatory. I say it is not cool at all.

**Users**
AI branch users and auditors 

**Type**
Choose the label (⚙️ functionality), (🗂️ documentation),

**Comment by Oumaimafisaoui** [comment]
Hello @fulverin. Thank you for your feedback. I want to clarify an important point about the project requirements:
Using a Convolutional Neural Network (CNN) is not optional - it is mandatory and forms the core of this project. The CNN is essential for the emotion classification task, which is the primary goal of the assignment.
The reason CNNs are required is that they are particularly well-suited for image processing tasks like facial emotion recognition. This project is designed to give you hands-on experience with CNNs, which are a fundamental tool in modern computer vision.
