### ISSUE TITLE
[BUG] get-account subject

### ISSUE THREAD

**Issue by abdotop** [01-edu/public#2772]
get-account
---
Title: Correction needed for local node server address in test files

Description:

Hello,

I have identified a recurring issue in the test files of the "anchoring" quest, particularly in the "get-account" exercise, but potentially present in other tests using a similar approach.

Problem:
The tests fail with a timeout error when attempting to connect to the local node server.

Cause:
The test files are trying to connect to `http://localhost:8545`, but the local node server is actually accessible at `http://0.0.0.0:8545` in the Docker environment.

Proposed solution:
Modify the provider address in all affected test files. For example, for `get-account.test.js`, the correction would be:
```javascript
before(async function () {
provider = new ethers.providers.JsonRpcProvider("http://0.0.0.0:8545")
await provider.ready
})
```

Required actions:
1. Identify all test files using this approach to connect to the local node server.
2. Update the provider address in each of these files.
3. Test the solution to ensure that the tests run correctly after the modification.

This correction will allow the tests to properly connect to the local node server and avoid timeout errors, thus improving the learning experience for all users.

Thank you for considering this issue and resolving it as soon as possible.

Best regards,
Abdou TOP

**Comment by zanninso** [comment]
Thank you @abdotop for reporting that issue, we already working on it.It will be solved as soon as possible
