### ISSUE TITLE
[QUESTION] wget subject

### ISSUE THREAD

**Issue by kinoz01** [01-edu/public#2780]
wget
--- Audit links aren't working!

**Comment by MSilva95** [comment]
Hello @kinoz01, can you please specify the link not working?

**Comment by kinoz01** [comment]
@MSilva95 hello, these:
http://ipv4.download.thinkbroadband.com/100MB.zip
http://ipv4.download.thinkbroadband.com/20MB.zip

**Comment by kinoz01** [comment]
Maybe you can update to use this website:
https://sample-videos.com/
For example:
https://sample-videos.com/zip/20mb.zip

**Comment by MSilva95** [comment]
Thanks for the feedback, the PR is already created, and the changes will be applied as soon as possible!
We decided to add some files in our own storage so that this way we can always have them available and working.

**Comment by kinoz01** [comment]
@MSilva95 Ok Thank You
