### ISSUE TITLE
printcomb subject

### ISSUE THREAD

**Issue by boundioulagare** [01-edu/public#2790]
printcomb
--- Je suis nouvelle en info et je suis au niveau printcomb j'ai tout fait comme demandé mais on me dis qu'il ya un probleme je comprend pas

**Comment by MSilva95** [comment]
> [!IMPORTANT]
> ## 🚫 @boundioulagare : This issue has lack of context/clarity/substance/responsiveness!
> If you find there is something wrong with a subject/exercise/feature, please feel free to add details that would help our team to address the issue effectively. 
> 
> We could use the following information to help us resolve a potential issue:
> - The issue/error you are encountering from the platform
> - The solution you're trying to submit / steps to reproduce the issue/error
> - The screenshot of the issue/error
> - Any additional details
>
> For future issues, write in English, please!
