### ISSUE TITLE
[BUG] cat subject

### ISSUE THREAD

**Issue by Konixy** [01-edu/public#2794]
cat
---

The fourth exercise of the 8th quest doesn't work at all.
I talk to many coaches, my code is right, my files are at the right place, but a still have the following error : `stat : no such file or directory`

According to the coaches, this error is there since many others piscine.

**Comment by pedrodesu** [comment]
Hello @Konixy!

I'll be reviewing the exercise in question. Can you please comment below/attach the code you used?

**Comment by Konixy** [comment]
`cat/main.go`:
```go
package main

import (
	"io"
	"os"

	"github.com/01-edu/z01"
)

func main() {
	args := os.Args[1:]

	if len(args) < 1 {
		content, err := io.ReadAll(os.Stdin)
		if err != nil {
			printStr(err.Error(), true)
			return
		}

		printStr(string(content), false)
		return
	}

	for _, arg := range args {
		f, err := os.Open(arg)
		if err != nil {
			printStr("ERROR: "+err.Error(), true)
			return
		}

		content, err := io.ReadAll(f)
		if err != nil {
			printStr("ERROR: "+err.Error(), true)
			return
		}

		printStr(string(content), false)
	}
}

func printStr(str string, newLine bool) {
	for _, v := range str {
		z01.PrintRune(v)
	}
	if newLine {
		z01.PrintRune('\n')
	}
}
```

`cat/quest8.txt`:
```
"Programming is a skill best acquired by practice and example rather than from books" by Alan Turing

```

`cat/quest8T.txt`:
```
"Alan Mathison Turing was an English mathematician, computer scientist, logician, cryptanalyst. Turing was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general-purpose computer. Turing is widely considered to be the father of theoretical computer science and artificial intelligence."

```

**Comment by pedrodesu** [comment]
Indeed, with the error `stat : no such file or directory` I'm guessing you're referring to the output when you test `cat quest8.txt | ./cat`. This does indeed seem to be a mistake, the file `./cat` does not exist. The purpose of this input is to try and read lines directly from a piped, fixed stdin. I believe the correct prompt to be `cat quest8.txt | go run .` instead.
I will go ahead and make the change, I appreciate you pointing out this issue.

On a side note, while this input definitely was incorrect, I'd like to point out your code doesn't seem to be 100% correct, as you initially pointed out:
```sh
$ go run .
Hello
Hello
^C
```
This input doesn't seem to be compliant with your code. You're expecting and reading a full stdin, which you won't get in this interactive mode. You probably need to read the stdin line by line to fully pass the exercise ;)

Thank you!

**Comment by pedrodesu** [comment]
Of course, I forgot to point out, feel free to reopen the issue and discuss if I missed something or if you have any further comments.

**Comment by Konixy** [comment]
I re tested the exercise and I still have the same error, I guess you didn't fix the issue yet.
I tried to do what you just told, but I don't find a way to do it without the `bufio` package.

**Comment by pedrodesu** [comment]
Good evening @Konixy.

Yes, the error is yet to be fixed. I've already suggested a change and am currently awaiting approval. Soon enough the change should be merged. I'll let you know when it's approved :)

And yes, I'd say you would need some sort of buffering to do what I suggested. Is it disallowed to use `bufio`?

**Comment by Konixy** [comment]
Good evening, @pedrodesu!

Okay, no worries. I'm finishing my piscine tomorrow, so I guess it won't be fixed by then.

And no, `bufio` isn't allowed in this exercise :/

**Comment by pedrodesu** [comment]
After thorough discussion with a peer, we've come to the realisation `bufio` should be allowed to make the interactive mode work. Otherwise making the interactive mode work becomes much more difficult and probably somewhat limited. Some pushes are being made. I'll let you know once they go through.

Once again, thank you for pointing out your initial issue and discussing further.
