### ISSUE TITLE
Broken Link Results in Access Denied Error

### ISSUE THREAD

**Issue by MohcineDev** [01-edu/public#2797]
I've found that a link on the website leads to an "Access Denied" error page.
the link is located in the piscine-js/dom/where-do-we-go

Current Link: https://public.01-edu.org/subjects/where-do-we-go/where-do-we-go_images/arlit.jpg

Issue: When clicked, this link returns an "Access Denied" error, preventing access to the intended content.

If you decide to remove it, I can create a pull request to make the change

**Comment by HarryVasanth** [comment]
Hello @MohcineDev,

I appreciate you bringing this issue to my attention. 
I've configured our content to be able to hotlinked.

Once again, thank you!
