### ISSUE TITLE
[BUG] tetris-optimizer subject AUDIT

### ISSUE THREAD

**Issue by tsnarsen** [01-edu/public#2806]
tetris-optimizer
---
Hello there, I was checking the audit tests for this project, and I noticed some grammatical errors.
It says "Does the program **prints** the value above?", the word "prints" should instead be "print".
Also,
"Does the project **runs** quickly and effectively (Favoring of recursive, no unnecessary data requests, etc.)?". Here also the word "runs" should be "run" (In general when the question includes the word "does" the verb doesn't take an S in the end. I'm saying this cause I've seen this error a number of times).
Thank you!

**Comment by MSilva95** [comment]
Hello @Warezzly thank you for the feedback, we will take a look at this!
