### ISSUE TITLE
[QUESTION] social-network subject - definition of who can see Posts

### ISSUE THREAD

**Issue by geoo115** [01-edu/public#2813]
social-network
---
The definitions of 'public' , 'private' , 'almost-private' for Posts is incorrect and not logical.

The 'almost-private' definition is MORE private than the 'private' definition.

Please swap the definitions. The 'almost-private' definition should be associated with 'private'
The 'private' definition should be associated with 'almost-private'

This is then make the Post section logical.
Thank you.

**Comment by pedrodesu** [comment]
Hello @geoo115!

The issue you pointed out seems valid. We appreciate your input very much!
I've started working on the changes you suggested, they should be merged soon. In case you're curious, feel free to track its progress [here](https://github.com/01-edu/public/pull/2814).

As the problem should be fixed soon, I'll be closing this issue. Please feel free to reopen/comment on it if you have any extra feedback!

Cheers.
