### ISSUE TITLE
ownership subject

### ISSUE THREAD

**Issue by husainkarim** [01-edu/public#2816]
ownership
---

Expected functions

pub fn first_subword(mut s: String) -> String {
}

----------------------------------------------------------------

function can work without mut if we keep mut it show warning from rust

**Comment by pedrodesu** [comment]
Hello @husainkarim!

That mut in the function signature implies that you can and should mutate the original string to get the correct output. However, as you pointed out correctly, it is not enforced in the subject that the original string is checked, and you can indeed get the same correct output without mutating it. That exercise among others will be subject to a refactoring soon enough, so as to avoid this and other clarity issues.

In the meantime, take that mut as a sign that you can or not mutate the string, as you see fit, to get to the desired solution.
