### ISSUE TITLE
[QUESTION] checkpoint question hiddenp

### ISSUE THREAD

**Issue by AllenLeeyn** [01-edu/public#2820]
**Describe your question or potential issue**
One requirement of the question is to do nothing if the number of arguments are incorrect. As fas as I can tell, the solution doesn't check for the number of arguments. And in one of the test cases, it is giving an incorrect behavior.

**Context & Use Case**
When doing checkpoint, one of the test case is when the program is given no arguments.
Base on requirement, the expected output should be nothing.
However, the solution is printing something.

**Steps taken**
I have checked the repo to make sure the solution does check for arguments or the test files have a list of expected output.
I am not sure if am missing something obvious.

**Comment by MSilva95** [comment]
Hello @AllenLeeyn! thank you for the feedback we will fix the problem!
