### ISSUE TITLE
[ADMIN OBJECT FORM] - Entry moving in the list when updated

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#30]
When updating an attribute or a child of an object, its line moves somewhere else in the list (apparently at the end or at the top), which is a non practical a strange behaviour.

1. Go to update an attribute or a child
2. Save your changes
3. See the line moving somewhere else in the list

It should stay at the same place in the list.

<img width="1552" alt="Screenshot 2019-04-15 at 19 30 01" src="https://user-images.githubusercontent.com/4631239/56156657-9bda3900-5fb5-11e9-8315-42893b540777.png">
<img width="1552" alt="Screenshot 2019-04-15 at 19 30 08" src="https://user-images.githubusercontent.com/4631239/56156658-9bda3900-5fb5-11e9-9d8a-72183961186d.png">
<img width="1552" alt="Screenshot 2019-04-15 at 19 30 16" src="https://user-images.githubusercontent.com/4631239/56156659-9c72cf80-5fb5-11e9-8979-2a58fe8e6e4e.png">

**Comment by bde-maze** [comment]
i think it's related to the fact that the index is updated when you update the field. It should be fixed by the implementation of the sweet drag and drop
