### ISSUE TITLE
[ADMIN OBJECT FORM] - Mapped element have same key

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#34]
Some objects which have the same name / key return an error in the console. 

1. Go to the object edit form
2. See in the console this error

<img width="317" alt="Screenshot 2019-04-17 at 12 10 59" src="https://user-images.githubusercontent.com/4631239/56283705-685cf300-610a-11e9-8cff-04e9794db4ad.png">

We have to add a unique ID when the components are generated in the map function.

**Comment by bde-maze** [comment]
Je n'ai pas revu ce comportement depuis que l'on a retirer les doublons dans la db mais j'ai ajouté l'id dans la key juste pour etre sur! Fixes 01-edu/public#34
