### ISSUE TITLE
teacher subject

### ISSUE THREAD

**Issue by azakost** [01-edu/public#365]
I've submitted my 27-line code using commands like 'find', 'grep', 'tail' and never used an 'echo' in there, but still I ve got a message:

> ??? What ?? Wrong answer, teacher. Did you really do the job previously? Or was is just an "echo" of luck??

Locally it prints everything that required.
I guess an output of code should be printed by a certain format, that students don't know.  
If so, please provide these format.

**Comment by Frenchris** [comment]
Based on another comment, a clarification has been added to this subject. The folders tested are not called mystery. they have all different names but are at the same level. Please share your code next time in order to make our investigation smoother. thank you for your feedback. Sincerely, Chris
