### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by atlekbai** [01-edu/public#43]
**Is your feature request related to a problem? Please describe.**
We need to collect information regarding users.

**Describe the solution you'd like**
Before the game part, there should be fields to gather information about:
- email and its verification
- phone and its verification

Also, the ability to add custom fields as:
- Address (City)
- Age
- Field: "where did you find out about our school?"

**Additional context**
Screen from submit.alem.ai
![image](https://user-images.githubusercontent.com/29381624/56422358-c20b1c00-62c8-11e9-98b0-28b57a007bf4.png)

**Priority**
high

**Subject**
onboarding

**Comment by lfoussat** [comment]
you can now custom fields as you wish in onboarding and signup with modular steps, and email verification is handled thanks to github. We let you add your module for phone verification :)
