### ISSUE TITLE
printstr subject

### ISSUE THREAD

**Issue by samatt90** [01-edu/public#473]
printstr
---

There is example of output in the description of task:

student@ubuntu:~/piscine-go/test$ go build
student@ubuntu:~/piscine-go/test$ ./test | cat -e
Hello World!%
student@ubuntu:~/piscine-go/test$

Where we can note that the output should be the next: 
Hello World!%

However: the git.01.alemschool don't accepts this output, but accepts the output: 
Hello World!

**Comment by OGordoo** [comment]
It is supposed to be an "$", thanks
