### ISSUE TITLE
teacher subject

### ISSUE THREAD

**Issue by abduakhatov** [01-edu/public#474]
teacher
---
```
/jail/student/teacher.sh: line 14: cd: *mystery*/: No such file or directory
grep: crimescene: No such file or directory
grep: crimescene: No such file or directory
??? What ?? Wrong answer, teacher. Did you really do the job previously? Or was is just an "echo" of luck??
```

I tried to change directory to training as in the description. The problem is where is the training folder?

**Comment by Frenchris** [comment]
Added some precision in the subject because of that comment. for clarification, the folder is not called mystery. It is different folders at the same root. I will pm you today.
