### ISSUE TITLE
Field "This project will help you learn about"

### ISSUE THREAD

**Issue by enthusiast17** [01-edu/public#522]
Field `"This project will help you learn about"` is an effective approach to explain students what knowledge they will get and of course it will motivate them. (IMHO) But, some subjects do not have that field.

Subjects that do not contain this field:
- tetris-optimizer
- forum
- may some optional subjects :)

Thanks.

**Comment by Frenchris** [comment]
We will address this issue **after** the PR #520 is merged

**Comment by OGordoo** [comment]
it's corrected thanks
