### ISSUE TITLE
sortedlistmerge test case in go-reloaded

### ISSUE THREAD

**Issue by alseiitov** [01-edu/public#529]
instruction for sortedlistmerge says that

> During the tests n1 and n2 will already be initially sorted.

But in this test case lists are not sorted

> Try with the arguments: n1 = 0-> 7-> 39-> 92-> 97-> 93-> 91-> 28-> 64-> <nil> and n2 = 80-> 23-> 27-> 30-> 85-> 81-> 75-> 70-> <nil>

**Comment by LEEDASILVA** [comment]
its corrected, thanks
