### ISSUE TITLE
/intra/piscine-go/raid-02 Page

### ISSUE THREAD

**Issue by bde-maze** [01-edu/public#541]
Error when loading /intra/piscine-go/raid-02/ page

![image](https://user-images.githubusercontent.com/15313830/83418069-47955100-a423-11ea-8ff8-d0fd99178e31.png)

Was log as a student (Akmaral Bibassarova / AkmaralB)

**Comment by Frenchris** [comment]
C'est parce que cette piscine est déjà terminée.
