### ISSUE TITLE
elementary subject

### ISSUE THREAD

**Issue by azamatamirzhan** [01-edu/public#575]
elementary
---
The * sign is prohibited to use in multiply function.
But tests gives error to my divide and modulo functions that they has * in the code.
Is it error in the tests or in the task?

**Comment by kigiri** [comment]
the `*` sign is also prohibited for modulo and divide.

**Comment by azamatamirzhan** [comment]
Please, add the limit to "allowed functions" of task.
From task it looks like you can use prohibited symbols of one function in another.
