### ISSUE TITLE
find-expression subject

### ISSUE THREAD

**Issue by azamatamirzhan** [01-edu/public#579]
find-expression
---
In test there is a control of using 5-9 digits, but in task it's not declared.
Please, add conditions to allowed functions in find-expression and elementary

**Comment by azamatamirzhan** [comment]
I don't know where to find this files to add pull-request.
If it posible, can you give the link?

**Comment by kigiri** [comment]
https://github.com/01-edu/public/blob/master/subjects/find-expression.en.md

**Comment by azamatamirzhan** [comment]
I mean this: https://01.alem.school/api/object

**Comment by kigiri** [comment]
oh yeah we don't have an open way to contribute to this structure at the moment.

**Comment by azamatamirzhan** [comment]
жаль
