### ISSUE TITLE
Create new branches/folders for optional tasks, instead of creating new repositories

### ISSUE THREAD

**Issue by Sarmerer** [01-edu/public#586]
New repo for every optional of every project is not convenient and turns git profile into a mess. It would be way better to create new branches instead.

**Comment by enthusiast17** [comment]
@Sarmerer But, the auditors will get access some undone projects for them. Is there any possible way to hide unnecessary projects from auditors by splitting branches/folders and etc?

**Comment by Frenchris** [comment]
@Sarmerer @enthusiast17, This is a slightly more complicate issue that it looks. 
Among the team, we had a discussion about the branches splitting but we quickly decided that the best course of action was to ask each student to separate each repo. 
At the moment the system is working well as it is. 
A way of requiring options and its main to be kept in the same repo was discussed among the possible features but it is not a priority as it is. 

Your remarks are however noted, and I will log and share that feedback with my colleagues.  Thank you for sharing :)
