### ISSUE TITLE
[PAGE_LOADING] - loading page shows 'campus not found'

### ISSUE THREAD

**Issue by Yenlik29** [01-edu/public#59]
**Describe the bug**
When the page is loading, the title 'campus not found' shows for 1-2 seconds

**To Reproduce**
1. Refresh page, for example 'alem.01-edu.org/intra'
2. See the title 'campus not found'

**Expected behavior**
Expected just normal page [loading](url) without title 'campus not found' :)

**Screenshots**

**Desktop (please complete the following information):**
- Chrome :)
- Firefox

**Smartphone (please complete the following information):**
- Safari

**Type**
 minor

**Priority**
normal

**Subject**
![unnamed](https://user-images.githubusercontent.com/29530727/56643220-0452a580-669b-11e9-9e3e-d1c2731cbd2b.jpg)

Intra

**Comment by lfoussat** [comment]
this bug is related to #10 ticket :)

**Comment by Yenlik29** [comment]
oh thanks :) didn't notice we had it
