### ISSUE TITLE
date-is subject

### ISSUE THREAD

**Issue by Danonika** [01-edu/public#594]
date-is
---
Problem statement - isPast, will return true if the date given as parameter less then the present date
Test use incorrect date or statement should be changed
test #22 failed:
() => !invalid(isPast)
Error:
Error: isPast('') should be false

**Comment by kigiri** [comment]
yes we should update the statement to:
> `isPast`, will return true if a valid date given as parameter is less than the present date

Would that be good @Danonika ?

**Comment by Danonika** [comment]
Yes, but to make exercise more tricky can u change just word date to data?

**Comment by Danonika** [comment]
Like -  isPast, will return true if the data given as parameter less then the present date

**Comment by kigiri** [comment]
that would imply that unix timestamp are handled, actually I don't see the problem with the current statement:
> return true if the date given as parameter less then the present date

Now is `''` less than the current date ? no it's not even a date so it's expected to be false, that would be my reasoning.

Maybe I did not understood your point properly

**Comment by Danonika** [comment]
> Now is `''` less than the current date ? no it's not even a date so it's expected to be false, that would be my reasoning.
>  As you said '' no it's not even a date, how can be it's a parameter(return true if the date given as parameter less then the present date)

**Comment by LEEDASILVA** [comment]
hey, so a fix the subject to 
> - `isAfter`, this function will receive two valid dates and return true if the first date is bigger then the second date
> - `isBefore`, this function will receive two valid dates and return true if the first date is lesser then the second date
> - `isFuture`, will return true if it is a valid the date given as parameter is higher then the present date
> - `isPast`, will return true if it is a valid date given as parameter is less than the present date

just like @kigiri sayd i added them on the statements
