### ISSUE TITLE
[INTRA] - automatic opening of a new task does not work correctly

### ISSUE THREAD

**Issue by alseiitov** [01-edu/public#596]
When you successfully submit one subject, the next one opens automatically, but instructions for this subject and 'Run' button are not available until you update the page

**Screenshots**
![Screen](https://i.imgur.com/DcI12ui.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser:  Google Chrome
- Version:  83.0.4103.97

**Type**
minor

**Priority**
low

**Subject**
intra

**Comment by enthusiast17** [comment]
The same issue in Windows 10, Google Chrome.
@MarieMalarme

**Comment by MarieMalarme** [comment]
@enthusiast17 @alseiitov thanks for the issue, I will work on that and come back to you.

**Comment by ZoeVig** [comment]
This issue has been fixed
