### ISSUE TITLE
get-them-all subject

### ISSUE THREAD

**Issue by kuzikov** [01-edu/public#622]
get-them-all
---
> On top of the webpage, each of the four buttons fires a function which has to return an array  containing 2 arrays of HTML elements (except for the last function): the targetted people, and the others eliminated at that step - the ones previously eliminated mustn't be included.
> 
> Write the body of the `getArchitects` function, which targets the architects, all corresponding to a `<a>` tag, and eliminates all the non-architects people.
> 
> Write the body of the `getClassical` function, which targets the architects belonging to the classical class, and eliminates the non-classical architects.
> 
> Write the body of the `getActive` function, which targets the classical architects who are active in their class, and eliminates the non-active classical architects.
 >
> Write the body of the `getBonannoPisano` function, which targets the architect you're looking for, whose id is BonannoPisano (return only this one as a single element, not an array), and eliminates all the remaining active classical architects.
---
What is the purpose of this task? @kigiri  @MarieMalarme 
One part of the conditions is described in the preface about the architect, says `return 2 arrays`.
The instructions for the functions say `elimination` of non-target elements.
What does `elimination` mean in this context?
How should I understand the instructions?

1. Should I only return 2 arrays (target elements and all other remaining ??) as stated in the `description`?
2. Should I just remove non-target elements from the DOM tree, as the function instructions say?
3. Should I combine all the conditions and write functions that return 2 arrays with elements and remove non-target elements from the DOM tree?

**Comment by kuzikov** [comment]
And what should the getBonannoPisano function do? Only return an element with BonannoPisano ID or remove active and classic architects and return that element at the same time?

**Comment by MarieMalarme** [comment]
@kuzikov in that task you don't have to remove anything for the DOM tree, just to return the targeted people and the non-targeted people of each step. It's to make you use the `getElement...` methods, that's it. I'll try to clarify even more the instructions.

**Comment by MarieMalarme** [comment]
@kuzikov i clarified the instructions, you can have a look at it now!

**Comment by kuzikov** [comment]
thanks a lot!
