### ISSUE TITLE
[ADMIN OBJECT FORM] Display the inherited attributes of children

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#63]
In an object, when we add it some children, they appear like they don't have any attribute (but they actually have some, inherited from the original object), so we don't know what we are really modifying / adding as attributes.
We should display the existing attributes (with a visual marker that those are inherited attributes, and they can't be deleted) + adding new ones to surcharge.

<img width="1552" alt="Screenshot 2019-04-24 at 11 17 05" src="https://user-images.githubusercontent.com/4631239/56655783-ab2f4580-668b-11e9-9678-07d68be108fd.png">

**Comment by bde-maze** [comment]
It's an advance feature, will be done later (the user can use the navigation between object for now, it's not blocking)
