### ISSUE TITLE
[ADMIN OBJECTS] - Create a new type of objects

### ISSUE THREAD

**Issue by MarieMalarme** [01-edu/public#67]
At the moment we cannot create a new type of objects in the Admin (we can only do this in the DB).

We should add this feature in the Objects page.

<img width="1552" alt="Screenshot 2019-04-24 at 13 03 18" src="https://user-images.githubusercontent.com/4631239/56658118-aff6f800-6691-11e9-9f75-ff818db34e47.png">

**Comment by bde-maze** [comment]
Why do you need this feature? I find it little bit touchy for now considering that we are Hard Filtering types in the code, and if you really need to add a new type you can do a migration. What do you think?

**Comment by MarieMalarme** [comment]
I needed it when I wanted to add exams and raids in the database (which I did directly in hasura) ; I am just guessing users may want to be able to add new custom types in the future. But it's not a priority, we can focus on other stuff for the moment !

**Comment by bde-maze** [comment]
Ok, I close the issue then :)
