### ISSUE TITLE
net-cat subject

### ISSUE THREAD

**Issue by Danonika** [01-edu/public#673]
net-cat
---
statement
*If a Client joins the chat, all the previous messages sent to the chat must be uploaded to the new Client.
But on example2(Client2 Lee):
*Can't see previous messages from example1(Client1 Yenlink).

I Can't make propose to change, because I don't know duration time when Yenlik messages will come to Client Lee after typing and sending messages.

**Comment by OGordoo** [comment]
Hi Danonika, good eye spotting the issue. Thank you
