### ISSUE TITLE
printalphabet subject

### ISSUE THREAD

**Issue by CieIa** [01-edu/public#675]
printalphabet
---
student@ubuntu:~/challenge-go/printalphabet$ go build
student@ubuntu:~/challenge-go/printalphabet$ ./printalphabet
abcdefghijklmnopqrstuvwxyz
student@ubuntu:~/challenge-go/printalphabet$

fmt.println("abcdefghijklmnopqrstuvwxyz")

**Comment by ZoeVig** [comment]
Hi @CieIa could you tell us more about this issue? It's unclear for us

**Comment by OGordoo** [comment]
@CieIa fmt package is not  allowed in that exercise
