### ISSUE TITLE
tron subject

### ISSUE THREAD

**Issue by Danonika** [01-edu/public#679]
tron
---
On https://raw.githubusercontent.com/01-edu/public/master/subjects/tron/ai/random.js
comment:
Each AIs contains:
  //   color: A number that represent the color of a AI
  //   name: A string of the AI name
  //   score: A number of the total block collected by this AI
  //   coords: An array of 4 coordinates of the nearest blocks
but ais objects doesn't have key - score
![Screenshot from 2020-09-16 22-10-23](https://user-images.githubusercontent.com/52859990/93364089-f1c9a500-f869-11ea-93c8-2c92f591afd9.png)

**Comment by LEEDASILVA** [comment]
corrected thank you
