### ISSUE TITLE
[INTRA] copy commands from audit page/header/main

### ISSUE THREAD

**Issue by enthusiast17** [01-edu/public#687]
Hey. it would be awesome add double ampersand `&&` between commands when click `copy commands` button.

What I've got:
``` bash
git clone https://git.01.alem.school/no-name/ascii-art-justify
cd ascii-art-justify
git reset --hard 5f374743aa183c8325d184ec58aad4ec3e922d7c
```
What I really want:
``` bash
git clone https://git.01.alem.school/no-name/ascii-art-justify && cd ascii-art-justify && git reset --hard 5f374743aa183c8325d184ec58aad4ec3e922d7c
```

**Comment by Frenchris666** [comment]
Hello @enthusiast17 , may you tell me which subject you are making this suggestion for?

**Comment by Frenchris** [comment]
Hello @enthusiast17, may you tell me which subject you are making this suggestion for?

**Comment by enthusiast17** [comment]
Hey @Frenchris. This suggestion for user interface on 01 website, i guess.

**Comment by Frenchris666** [comment]
I am sorry @enthusiast17 . I am not sure I understood. Can you give me more details as a concrete example please? In which page of the platform would that button appear? And would the button be customizable? what would it do exactly?

**Comment by Frenchris** [comment]
I am sorry @enthusiast17 . I am not sure I understood. Can you give me more details as a concrete example please? In which page of the platform would that button appear? And would the button be customizable? what would it do exactly?

**Comment by augusto-mantilla** [comment]
Hello @enthusiast17. Why do you want to add the `&&`?

**Comment by enthusiast17** [comment]
Hey @augusto-mantilla, because it is convenient, and line by line won't work for me.

**Comment by augusto-mantilla** [comment]
Which shell are you using? In bash and zsh works fine

**Comment by enthusiast17** [comment]
@augusto-mantilla bash in Ubuntu 20.04

**Comment by augusto-mantilla** [comment]
@enthusiast17 Please run `bash --version` in your terminal and post the output here. And if you could make a short video showing the copied command failing, it would be really useful to figure out what is happening.

**Comment by enthusiast17** [comment]
@augusto-mantilla Hey, sorry for late response. I had to wait a new audit. So, here is the video link -> https://www.awesomescreenshot.com/video/2775893?key=b069f4116ea41ce90849f2ca7512c781

**Comment by xpetit** [comment]
@enthusiast17 what happens if you register your SSH public key in Gitea so that you don't have to type your credentials while cloning ?

**Comment by Frenchris** [comment]
Closing this issue because of lack of answer.
