### ISSUE TITLE
[rust-tests] - temperature_conv_test - test fails even if got expected result

### ISSUE THREAD

**Issue by abduakhatov** [01-edu/public#732]
**Describe the bug**
Test fails for fahrenheit_to_celsius in temperature_conv_test. Specifically, 

**To Reproduce**

1. Copy paste the code of mine 
```
const OFFSET: f64 = 32.0;
const WEIGHT_FACTOR: f64 = 5.0/9.0;

pub fn fahrenheit_to_celsius(f: f64) -> f64 {
    println!(">> res {}",(f - OFFSET) * WEIGHT_FACTOR );
    return (f - OFFSET) * WEIGHT_FACTOR
}
```

**Expected behavior**
This is the expected test results:
```
assert!(eql(fahrenheit_to_celsius(20.0), -6.666666666666666));
assert!(eql(fahrenheit_to_celsius(83.0), 28.333333333333332));
```

**Screenshots**
This is the result
![image](https://user-images.githubusercontent.com/16864907/108620001-9d46d900-744a-11eb-935a-4c85dc958a45.png)

**Desktop (please complete the following information):**

- OS: rust docker image

**Subject**
temperature_conv_test

**Comment by augusto-mantilla** [comment]
Hello @abduakhatov, it should be fixed now.
