### ISSUE TITLE
[ADMIN OBJECT EDIT] - select attribute type to small, prevent to view all options

### ISSUE THREAD

**Issue by bde-maze** [01-edu/public#74]
The type selector doesn't show its full content when open, which prevent to have acces to all types.

![](https://cdn.discordapp.com/attachments/504684628754432040/570654396753379362/Screenshot_2019-04-24_at_17.56.03.png)

**Comment by MarieMalarme** [comment]
Fixed on branch [issue74](https://github.com/01-edu/all/tree/issue74)
