### ISSUE TITLE
debounce subject

### ISSUE THREAD

**Issue by riamon-v** [01-edu/public#755]
debounce
---
I don't understand what's  wront with my code. I checked all over the internet and found the result for this to be implemented was the same.

The issue is I cannot pass the last test of this subject with the `leading` value set to `true`. 

The expected result is apperentrly `[1, 2]` but I keep getting `[1, 3]` whatever I do

Here is my code for you to try.

``` js
const debounce = (callback, wait, options = null) => {
    let time = null

    return (...args) => {
        const later = () => {
            if (!options?.leading)
                callback(...args)
            time = null
        }
        
        if (time)
            clearTimeout(time)
        else if (options?.leading === true )
            callback(...args)
        time = setTimeout(later, wait)
    }
}

```

**Comment by Frenchris** [comment]
I think you overcomplicated your life. 
It is written in the subject and look at the test.  The options part was supposed to be ignored.
