### ISSUE TITLE
introduction subject

### ISSUE THREAD

**Issue by Armanarmanarman** [01-edu/public#771]
introduction
---

introduction_test.sh: line 8: ./student/hello.sh: Permission denied
To whom do I need to give access?

**Comment by xpetit** [comment]
Ask Google "shell script permission denied"

**Comment by DAVINCIPRO19** [comment]
I have same problem with permission. I already use chmod, but it still does not work! What should i to do?

**Comment by xpetit** [comment]
@DAVINCIPRO19 either you didn't use chmod correctly or you forgot to push the modifications

**Comment by Armanarmanarman** [comment]
https://github.com/Homebrew/discussions/discussions/439
I found answer to this problem here.

Hint:


brew reinstall gettext


brew reinstall pcre2


Пн, 26 апр. 2021 г. в 19:18, xpetit ***@***.***>:

**Comment by Marines93** [comment]
I have same problem with permission

**Comment by DAVINCIPRO19** [comment]
Arman, do I write this command in bash console?

**Comment by Armanarmanarman** [comment]
Oh sorry i wrote another thing in previous messages
This command should solve your issue

chmod +x filename

https://qna.habr.com/q/201649

Пн, 26 апр. 2021 г. в 19:27, DAVINCIPRO19 ***@***.***>:

**Comment by xpetit** [comment]
and don't forget to add/commit/push your changes.
I'm closing this issue

**Comment by DAVINCIPRO19** [comment]
> @DAVINCIPRO19 either you didn't use chmod correctly or you forgot to push the modifications

I don't know, I used chmod 777 filename.sh and push also. But it does not work

**Comment by DAVINCIPRO19** [comment]
can anyone help me with it? My discord: DAVINCIPRO.19#6595

**Comment by xpetit** [comment]
Your file is not executable on Git I just checked. This place is for issues with the subjects and exercises, not your solutions.
Please ask for help directly on Discord, not here.
