### ISSUE TITLE
make-it-better subject

### ISSUE THREAD

**Issue by Armanarmanarman** [01-edu/public#773]
make-it-better
---
I've created the files and changed the dates so it looks like in the example given.

But after I push it to git and run Make-it-better it shows different date and time 

Also when I pass
 $ TZ=utc ls -l --time-style='+%F %R' | sed 1d | awk '{print $1, $6, $7, $8, $9, $10}'
to terminal it says:
ls: illegal option -- -
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]

**Comment by xpetit** [comment]
Use coreutils `ls`/use Linux
