### ISSUE TITLE
make-it-better subject

### ISSUE THREAD

**Issue by Armanarmanarman** [01-edu/public#774]
make-it-better
---
It says 
"Bim! Your code passed the tests successfully!" 
But the next exercise is still "BLOCKED" and for "make-it-better" it still shows "AVAILABLE"

**Comment by xpetit** [comment]
> ## make-it-better
> It says
> "Bim! Your code passed the tests successfully!"
> But the next exercise is still "BLOCKED" and for "make-it-better" it still shows "AVAILABLE"

ask help on Discord, this place is about issues with subjects & tests, not implementation problems
