### ISSUE TITLE
introduction subject

### ISSUE THREAD

**Issue by asfann** [01-edu/public#775]
introduction
---
I did everything exactly as asked, everything worked for me, but now it says that I have an error in the code
![изображение_2021-04-28_001332](https://user-images.githubusercontent.com/64355174/116291578-9162f480-a7b6-11eb-892c-acabe1b2383a.png)

**Comment by xpetit** [comment]
Hello @asfann, ask around you, on Discord.
You have an invisible character somewhere, I let you look

**Comment by xpetit** [comment]
@asfann **and don't use Windows** Use Linux line ending
