### ISSUE TITLE
isnegative subject

### ISSUE THREAD

**Issue by ScarletDragon3101** [01-edu/public#778]
isnegative
---
go: student@v0.0.0 requires
    github.com/acroca/go-symbols@v0.1.1: missing go.sum entry; to add it:
    go mod download github.com/acroca/go-symbols

this library is already exist, but it return me this error every time
<img width="658" alt="Снимок экрана 2021-04-29 в 05 41 38" src="https://user-images.githubusercontent.com/62964136/116485786-e6cdfd00-a8ad-11eb-9893-b0cd5e74ac46.png">
<img width="658" alt="Снимок экрана 2021-04-29 в 05 44 21" src="https://user-images.githubusercontent.com/62964136/116485808-f3eaec00-a8ad-11eb-8456-019951726182.png">

**Comment by xpetit** [comment]
Hi, you just need `github.com/01-edu/z01` the rest is garbage I don't know how you ended up with it.

**Comment by xpetit** [comment]
@ScarletDragon3101

**Comment by xpetit** [comment]
Also, this is not the place where you ask questions about your problems, ask it on Discord
