### ISSUE TITLE
atoibase subject

### ISSUE THREAD

**Issue by MPuust** [01-edu/public#806]
atoibase - return to decimal base is not mentioned but seems to be expected here.
---
![image](https://user-images.githubusercontent.com/58730686/125787175-26a23fc5-9314-4016-8629-427df79873d3.png)

**Comment by OGordoo** [comment]
Hello @MPuust, when we say `And return the integer value (...)`, we assume that this integer is already in decimal base.

**Comment by Frenchris** [comment]
In addition @MPuust , I would add that you need to read the subject in its **entirety.**
The exercise also has a **usage** part and its examples right **below** your screenshot. The very first example is a decimal base.
