### ISSUE TITLE
Complicated instructions

### ISSUE THREAD

**Issue by F1am3r** [01-edu/public#813]
teacher
---
So the instructions say that you need to enter the mystery directory (so you are one level up from mystery folder), and the directory name can be different to "mystery" - and to look how to create a loop. 
Basically the code below should pass from what I understand: 

```
for d in */ ; do
    mystery_number=$(head -n 179 $d/streets/Buckingham_Place | tail -n 1 | cut -d '#' -f2)
    echo $mystery_number
    head $d/interviews/interview-${mystery_number}
    grep -A 4 "L337" $d/vehicles | grep -B 1 -A 3 "Honda" | grep -C 2 "Blue" | grep -B 4 "6'"
    cat $d/memberships/Delta_SkyMiles $d/memberships/AAA $d/memberships/United_MileagePlus | grep "$MAIN_SUSPECT" | wc -l
done
```

But at the end of the task it says you are already inside the mystery folder. Either way the description is contradictory, but which way is it intended to be solved is not clear.

**Comment by Frenchris** [comment]
Ok, apologies for the delay.
After review I decide to rewrite this exercise. I will closed this issue when the subject is rewritten this way you will be informed.
Thank you for this complete feedback.

**Comment by Frenchris** [comment]
Subject was simplified and tests were rewritten accordingly.
