### ISSUE TITLE
[INTRA] - wrong time period in current status widget

### ISSUE THREAD

**Issue by alseiitov** [01-edu/public#815]
When a student has two submitted but not yet successful projects, there is a period of the first subject, but the name of the second one. I submitted real-time-forum-typing-in-progress 11 days ago (not sure), and graphql 2 days ago. It shows that i submitted graphql 11 days ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/54891339/127808550-161a7041-a128-41cd-a52f-e2b5b65ba8c4.png)

**Type**
minor

**Priority**
low

**Subject**
intra

**Comment by alseiitov** [comment]
UPD: I passed graphql, and now it shows real-time-forum-typing-in-progress and 14 days.

![image](https://user-images.githubusercontent.com/54891339/127829218-f13dc4bc-7c74-4fd8-b615-4ec660b15fc3.png)

**Comment by alseiitov** [comment]
UPD2: passed real-time-forum-typing-in-progress. And now widget shows that i finished graphql 12 days ago🤔
![IMG_20210803_211647](https://user-images.githubusercontent.com/54891339/128041458-8f4d081c-3656-45d7-8079-565f11b17171.jpg)

**Comment by LEEDASILVA** [comment]
@Frenchris do you know anything about this?

**Comment by Frenchris** [comment]
@alseiitov Please know that I transfered this issue here https://www.notion.so/01edu/INTRA-wrong-time-period-in-current-status-widget-a216a435d09b40d1b7a8718732e910f8 
I will close this one when it is solved.
Thank you for the very detailled report.

**Comment by Frenchris** [comment]
This bug has been fixed. Closing the issue.

**Comment by bray0u** [comment]
Reopened, bug is still happening and a fix is in progress

**Comment by leviet0115** [comment]
Hi, Grit:lab encountered the same error when testing the content in the dev environment. Our go-piscine hasn't started yet, so we can't check if it happens to the production environment too. Please advise us about this and keep this ticket updated when the error is fixed. Thanks. 
![image](https://user-images.githubusercontent.com/64316728/159889101-748738e9-89a5-4a9e-a306-18d474c9e254.png)
<img width="945" alt="image" src="https://user-images.githubusercontent.com/64316728/159889261-cfa3fb39-d34f-4352-a939-5ccffa50169d.png">

**Comment by ZoeVig** [comment]
Closing this ticket as it is linked to a bug ticket open in Jira here [https://01talent.atlassian.net/browse/SUP-40](https://01talent.atlassian.net/browse/SUP-40)
(accessible to school admins only)
