### ISSUE TITLE
doop subject

### ISSUE THREAD

**Issue by sariyya-abdullayeva** [01-edu/public#817]
doop
---
The task is not well explained. it is said to print result, but package restrictions are not defined. What package can be used to print, given that all program long we have been asked to use PrintRune and using fmt is considered cheating.

please clarify task better.

**Comment by OGordoo** [comment]
I suggest for you to always take a look at the packages that are allowed
For example in the `os` package there is this [function](https://pkg.go.dev/os#File.WriteString).
