### ISSUE TITLE
The Index Function !

### ISSUE THREAD

**Issue by KamalZ18** [01-edu/public#820]
index
---
In the 01 Founders → Piscine-go → Quest-05 → Index Function specification:
it states that: this function behaves like the Index function;
Here is a possible program to test your function:
Println(piscine.Index("Hello!", "l"))
Println(piscine.Index("Salut!", "alu"))
Println(piscine.Index("Ola!", "hOl"))

but there is no example or mention about if the substring is empty;

• The 01 Founders → Go Tests on GitHub:
https://github.com/01Founders/go-tests

It does a test for when the substring is empty, the test expects that index function returns 0;
but this is not mentioned in the Specification or Examples;
In the Specification it should state that:
If the substring is empty, then this function returns 0;
it should also state that:
If the substring is not found, then this method returns -1.

**Comment by OGordoo** [comment]
In the subject it is said that the function should behave like the `Index` from the Golang std package. You can check its behavior in the link provided in the `### Notions`.
