### ISSUE TITLE
go-reloaded subject

### ISSUE THREAD

**Issue by MPuust** [01-edu/public#829]
go-reloaded
---
Audit Exercise 4 
‘I’m an optimist, but an optimist who carries a raincoat.’ has different quotation marks (ASCII 8216 & 8217) and their conversion required whilst in the introduction handling of " ' " (ASCII 8242) is required. This means that only after first audit you'll know exactly what you need to write.

**Comment by OGordoo** [comment]
Hi @MPuust, I just checked the README. Do you mean that in the example in the README is missing the `"`?

**Comment by jarmo-seljamaa** [comment]
The instructions do not mention the special types of "Left single quotation mark" and "Right single quotation mark", but have visual representation of a "Single quote" character. Also, the given examples do not include cases with opening or closing quotation marks. So only at the audit we get to learn that our code should handle these special types, too.

**Comment by MSilva95** [comment]
We are currently rewriting the instructions for better understanding.
Thanks for the review!

**Comment by jarmo-seljamaa** [comment]
While doing an audit I noticed that the audit sentence has been changed `I'm` changed to `I am`, but the left single quotation  mark and right single quotation mark are still present in the audit sentence, while missing in the task instructions.
`place the following text (without the double quotes): "harold wilson (cap, 2) : ' I am a optimist ,but a optimist who carries a raincoat . '".`
