### ISSUE TITLE
customers-continent subject

### ISSUE THREAD

**Issue by ErikDRen** [01-edu/public#830]
customers-continent
---
Il y'a beaucoup de fautes évitables sur l'ensemble du challenge Sql ce qui fait perdre beaucoup de temps . Le TRAVAIL a été bâcle 4/20  très déçu.

**Comment by LEEDASILVA** [comment]
Hey, @ErikDRen so this is not our content

**Comment by Frenchris** [comment]
@ErikDRen as @LEEDASILVA mentioned we are not the authors of this content.
However so, if we may suggest,  in term of making your feedback a bit more _constructive_ and help the authors enhance the SQL piscine for everyone: 
1)Please make the list of all the "fautes évitables".
2)Transmist that list either in the form of an issue or a PR.
3)If you transmit your feedback in the form of a PR you will get the credit and will facilitate the integration of said feedback to the content you revised.
