### ISSUE TITLE
Make either challenging or basic projects audit-ratio free.

### ISSUE THREAD

**Issue by uristdwarf** [01-edu/public#831]
**Is your feature request related to a problem? Please describe.**
Currently, if you work too quickly (or are unlucky to receive audits for a long time), you can be locked out of further progressing on any project for an unknown period.

**Describe the solution you'd like**
One solution would be to make the basic projects free from audit-ratio requirements, so as not to punish those who move more quickly through the system.
Another solution would be to make the challenging projects audit-ratio requirements free, so that those quicker ahead have something to do while they wait, and can act as a surplus to those who haven't gotten as much audits as needed.

**Describe alternatives you've considered**
Other solutions could be: lowering the audit ratio requirements for projects or requiring a good audit ratio to advance to the next piscine (i.e making it an overall requirement for advancement).

**Comment by Frenchris** [comment]
Hello @byondmindfucked. This issue is currently being discussed with your local administrators as well. I am in contact with them to see if some of the projects audit-ratio requirements will be lowered.

**Comment by Frenchris** [comment]
This is no longer an issue. An improvement was deployed regarding the calculation of the audit-ratio. And some projects settings were adapted locally with a lower required audit ratio.
