### ISSUE TITLE
ascii-art-color subject

### ISSUE THREAD

**Issue by jamesforvaru** [01-edu/public#834]
ascii-art-color
---
In the task description it is said that you have to let the user choose the "ascii font" as well, but the auditing page says that it's not needed.

Task description:
<img width="334" alt="Screenshot 2021-09-21 at 21 31 24" src="https://user-images.githubusercontent.com/65786723/134227514-cca43098-92cb-40fe-87c6-5b63199d2240.png">
Auditing page:
<img width="334" alt="Screenshot 2021-09-21 at 21 32 31" src="https://user-images.githubusercontent.com/65786723/134227639-bf86e0be-0a4a-48ce-b67c-effb7ddf34bb.png">

**Comment by OGordoo** [comment]
Noted, thanks for the feedback
