### ISSUE TITLE
printwordstables subject

### ISSUE THREAD

**Issue by loguio** [01-edu/public#836]
printwordstables
---
HELLO, I WARN YOU THAT THIS SUBJECT IS WRONG !!! I'M NOT HAPPY WITH THIS, LOOK THE INSTRUCTION AND COMPARE WITH USAGE, IT'S NOT THE SAME THING !!!! THANKS TO CHANGE THIS FAST.

Bourse Marius, a student at ynov campus Nantes

**Comment by OGordoo** [comment]
Noted, thanks for the feedback
