### ISSUE TITLE
math-skills subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#838]
math-skills
---
The example in task description gives the following order of results:
```
Average: 35
Standard Deviation: 65
Variance: 5
Median: 4
```
But the audit instructs to check if the output is the same format as the output of the test program:
```
Average: 152
Median: 152
Standard Deviation: 29
Variance: 833
```
The order of the statistics are different, therefore the format is not exactly the same. Perhaps it would be easier for both the students and the auditors if the example had the same order of statistics as the test program?

**Comment by OGordoo** [comment]
Noted, thanks for the feedback
