### ISSUE TITLE
ascii-art-reverse audit/example issues

### ISSUE THREAD

**Issue by N1X0N3** [01-edu/public#876]
The expected result of example03 in the audit is shown in parenthesis, even though they aren't present in the actual ascii-art version, it is also the only test case where parenthesis have been added.

![incorrect expected output](https://user-images.githubusercontent.com/81628708/139146382-df491cc8-bdc0-414d-8de3-e17a8161ceb0.png)

There are two spaces between some characters in example05, there should only be one (the space following the previous character, each character starts from the 1st char of each line). This will incorrectly make peoples output fail/skip letters.

![extra space between dollar and percent](https://user-images.githubusercontent.com/81628708/139146799-248e11ca-3ea2-41cb-ac63-809affbdbeb0.png)
![extra gap between period and forward slash](https://user-images.githubusercontent.com/81628708/139146806-56d1ecba-ab04-4703-8c11-e5a9207c1606.png)

**Comment by MSilva95** [comment]
we will merge the fix as soon as possible thank you for the catch
