### ISSUE TITLE
CreateHistoricalMonument subject

### ISSUE THREAD

**Issue by injin0301** [01-edu/public#877]
CreateHistoricalMonument
---
Hello

It's been 2years for me doing this Ytrack and i found a big problem that It's VERY difficult to drag the scroll bar of the Test Panel! Because I DO NOT SEE VERY WELL the scroll bar! Could you modify OPACITY of the scroll bar ? Please?

**Comment by ZoeVig** [comment]
PR merged, will be available in the next redeployment
