### ISSUE TITLE
groupie-tracker-search-bar subject

### ISSUE THREAD

**Issue by ItsKris1** [01-edu/public#880]
groupie-tracker-search-bar
---
Some of the task exercise descriptions are hard to understand. One thing is actually solving the problem and second thing is what is expected from you. Without the second part it makes the exercise overcomplicated. I suggest providing more clear examples or being more descriptive in the exercise descriptions.

**Comment by Frenchris** [comment]
@MSilva95 may you check this isssue?
@ItsKris1 May you give us an examples of an example that would be more descriptive in the exercise descriptions?
An example that you would have thought would have been relevant?

**Comment by jarmo-seljamaa** [comment]
For example this:
`The program must handle case sensitive.`
This sounds like you want us to create an user interface that would not present results if the user enters the search term with incorrect case. That would be extremely bad UX and we should not be trained to do bad UI.

The instructions should say:
`The program must handle search input as case-insensitive`

**Comment by jarmo-seljamaa** [comment]
In the audit instructions there is a mistake too:
![pilt](https://user-images.githubusercontent.com/80747520/141954320-6e54352e-b82b-4087-831d-48141166d67e.png)

When searching for "Queen", the result should be "Queen" and **suggestion** (not the result) should be "Queensland", as this was an incomplete search term. No?

**Comment by MSilva95** [comment]
Hello jarmo-seljamaa! I will take a look at it, thank you for the catch.

**Comment by MSilva95** [comment]
We took care of the mistake, thank you again for the catch.
