### ISSUE TITLE
cl-camp1 subject

### ISSUE THREAD

**Issue by JacksyJack** [01-edu/public#882]
cl-camp1
---
Hi. When I click on the run test button, I get this error:

Error: Get file info failed: Not Found

The .sh file is sitting in my repository. I don't think I git it quite right, but can't tell one mlway or the other! 

Thanks

Jack

**Comment by MSilva95** [comment]
Did you check if the file has the correct name?

**Comment by Frenchris** [comment]
This was most likely a git issue during the first quest. Not a bug as it is an isolated report. Closing the issue.
