### ISSUE TITLE
ascii-art-web-export-file subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#890]
ascii-art-web-export-file
---
The task instructions do not state clearly if the exported file should be downloadable via the web browser or should it be just saved in the project folder in the backend. However, the audit instructions refer to HTTP content headers, so it seems only the first option can be implemented. 

Perhaps something like this:
```
Instructions
    The web server must export at least in one export format.
    The web server must be created in Go.
    The web site must include a button or a link to download/export the file.
    You must handle website errors.
    The code must respect the good practices.
```

**Comment by MSilva95** [comment]
Thank you for your review. We will add it to the readme and audit.
