### ISSUE TITLE
iterativefactorial subject

### ISSUE THREAD

**Issue by Ouassim-Remote** [01-edu/public#891]
iterativefactorial
---
a problem with the questions  in Quest 4 : iterativefactorial.go /recursivefactorial.go.
 This is recursive , Not itérative

**Comment by MSilva95** [comment]
sorry can you specify better, i'm not sure i understand.

**Comment by Ouassim-Remote** [comment]
okay so basically the solutions for the Questions that are asking for iterative answers in Quest 4 only get validated if we use recursive solutions and it created a lot of confusion 
for example the first exercice in Quest 4 asks us for 'iterativefactorial.go' an iterative factorial which would be solved using 'for loops' but it dosen't work. and only recursive solutions works

**Comment by MSilva95** [comment]
Regarding the recursive solution, yes you can pass the test using a recursive solution.
But the goal is to use an iterative solution, and i just checked the test with my solution and it passed so it is possible to pass the exercise without the use of recursion.

**Comment by Ouassim-Remote** [comment]
alright, Thank you
