### ISSUE TITLE
groupie-tracker subject

### ISSUE THREAD

**Issue by Gervin1** [01-edu/public#892]
groupie-tracker
---
The audit requires tasks that are not in the tasks description to be done. 
In the task description, it just says that "you must use **at least** the artists and relation parts given in the API" and "It is up to you to decide which info you will present and how you will display it".
But in the audit, requires that the site must present first album dates, locations, and error handling.
Can there be more information on what is expected from students to pass the audit in the task description?

**Comment by MSilva95** [comment]
Hello @Gervin1 thank you for the catch i will take a look at this subject and audit.
