### ISSUE TITLE
atm-management-system subject

### ISSUE THREAD

**Issue by KamalZ18** [01-edu/public#896]
Atm-Management-System:

Issue no 1:
There is NO README.md file;
In the Program spec it states that there should exist a README.md in the files provided.
On the File system diagram provided there is a README.md;
does that mean I need to create the README file OR that it's missing ?

Issue no: 2:
On the description of the Records.TXT file, the balance (maybe) is missing;
For the contents of records.txt:
Alice 0 10/02/2020 german 986134231 11090830.00 current;
is the 11090830.00 field the balance ? OR what ?
please clarify ?
---

**Comment by LEEDASILVA** [comment]
hello 
- first issue you are right, the REAME should not be there.
- second is missing the field balance/amount. i will be added.

thank you for the feedback, if you feel up to it you can make a PR.
