### ISSUE TITLE
Go-reloaded Task descriptions 

### ISSUE THREAD

**Issue by GermanKarK** [01-edu/public#897]
Reporting issues with the task descriptions 

**ascii-art-web**
https://github.com/01-edu/public/tree/master/subjects/ascii-art-web/export-file
Task is to download a file from the website. By googling it, you get somenthing like this 
https://www.w3schools.com/tags/att_a_download.asp
So to create an downloadable  element, we need attach an atribute to it with file path. But the task demands to do, by using a HTTP header. And the info about this is only in the audit notes. So it forces you to use completely other strategy 

**groupie-tracker** 

- The program must handle case sensitive in groupie-tracker-search-bar. Though it should ignore case sensitive 
- «Try to see the „members“ for the artists/band Queen». But we choose members by ourselves. Our what do you mean by that?

**filters, search bar** 
Task descriptions are hard to understand. Audit files are required 

**tetris**
Task descriptions are hard to understand

**Comment by LEEDASILVA** [comment]
@GermanKarK the correction for those subjects will be fixed today

**Comment by LEEDASILVA** [comment]
@GermanKarK here are the corrections for all the subjects present on this issue <https://github.com/01-edu/public/pull/904>
