### ISSUE TITLE
lem-in audit example02 is illogical

### ISSUE THREAD

**Issue by raidoxd** [01-edu/public#901]
multiple ants going through the same tunnel at the same time from start to end. maybe 20 as in the example, will fit in the same tunnel at the same time but suppose if you have 1000 ants going through it at the same time then I would doubt they will all fit in the 1 tunnel. thus making the example02 illogical 
this 
![image](https://user-images.githubusercontent.com/95702354/145058912-2d4e4b7e-4225-4095-bfb4-bac97e73eb06.png)
should be 
![image](https://user-images.githubusercontent.com/95702354/145059017-6b98a557-daa9-4521-b004-2a191a210d55.png)

**Comment by MSilva95** [comment]
Hello @raidoxd, i will take a look at the example, thank you

**Comment by raidoxd** [comment]
if you look at the examples you can see that every new step is on a new
line, so the picture you sent indicates to them going through the tunnel
all at once with 1 step

**Comment by nik-don** [comment]
This is what I see.. 

![image](https://user-images.githubusercontent.com/93073558/157737396-f32371dc-3669-4b1d-93d4-790a17da697d.png)


We can agree to disagree but please notice that there is a direct link to the END ROOM. and the END ROOM does not have any constraints to the number of ants.

Unless there is a specific rule saying a tunnel can be accessed only ONCE per turn even if the room that the ant is moving into is the end room..
