### ISSUE TITLE
ascii-art-web-export-file subject confusing instructions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#909]
ascii-art-web-export-file
---
![pilt](https://user-images.githubusercontent.com/80747520/146151267-850755aa-e7bc-47c7-97eb-6002036f7497.png)

This is confusing for the users. We should be not advised to learn about exporting to PDF, because we are only allowed to use standard go packages and AFAIK there are no standard go packages to enable PDF output. So we are unable to practice exporting to PDF in the scope of this task. Please remove the reference to PDF or enable using non-standard go packages.

**Comment by MSilva95** [comment]
hello @jarmo-seljamaa. This is not a mandatory type, this is just an example of a format we dont ask the student to export in pdf. but thanks anyway for the feedback we will remove this from the radme.
