### ISSUE TITLE
groupie-tracker subject

### ISSUE THREAD

**Issue by StewedSheep** [01-edu/public#912]
groupie-tracker
---
Hey. In groupie-tracker the exercise info doesn't match audits requirements.
Audit page:
https://cdn.discordapp.com/attachments/920728924290424862/920729385810686032/unknown.png
exercise information page:
https://cdn.discordapp.com/attachments/920728924290424862/920729520527527976/unknown.png
if relations is not used it fails the audit

**Comment by MSilva95** [comment]
I will fix this in the next hour thank you for the catch!
