### ISSUE TITLE
ascii-art-web-export-file subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#913]
ascii-art-web-export-file
---
There are duplicate questions in the audit (first and last on the pic), only difference is if the button is "clear":
![pilt](https://user-images.githubusercontent.com/80747520/146671426-503b819e-1fc3-46b1-8c17-104b51728785.png)

**Comment by MSilva95** [comment]
Hello @jarmo-seljamaa thank you for the catch we will take care of this!
