### ISSUE TITLE
chunky subject

### ISSUE THREAD

**Issue by AaEnnDeeErrEeEss** [01-edu/public#920]
Order of parameters should be added.

**Comment by MSilva95** [comment]
Hello @AaEnnDeeErrEeEss !
I'm not sure what you mean here.
You mean something like this:
The function should be formulated as follows
  const chunk = (arr, size) => {}?

**Comment by AaEnnDeeErrEeEss** [comment]
Something like that.
Or that function takes two parameters: an array that has to be split, and an integer that is the size that the array has to be split into.
Right now one can figure it out, but it is not stated clearly.

**Comment by MSilva95** [comment]
ok, i will make it more clear thank you for the feedback!
