### ISSUE TITLE
cut-corners subject

### ISSUE THREAD

**Issue by AaEnnDeeErrEeEss** [01-edu/public#921]
round function test generates values different from Math.round for negative .5 numbers.

**Comment by MSilva95** [comment]
Hello @AaEnnDeeErrEeEss!
Thank you for the feedback, i will take a look at the tests and see what is the problem.

**Comment by MSilva95** [comment]
Did your exercise fails because of this problem? Because in the test we are not using - 0.5 values

**Comment by AaEnnDeeErrEeEss** [comment]
I don't really remember the cases.
I could try to reproduce it later if necessary to find out how I got it.

**Comment by MSilva95** [comment]
Yes if you can please reproduce the cases, thank you!
