### ISSUE TITLE
index-of subject: Make paramaters more clear

### ISSUE THREAD

**Issue by uristdwarf** [01-edu/public#924]
index-of
---
I was initially confused by it saying "functions should have an array element as first argument", thinking it meant the value to be searched.
A more clearer way for example:
`The indexOf functions takes 3 arguments: the array to be searched, the value to be matched, and optionally the index from where to start searching from.`

**Comment by MSilva95** [comment]
Hello @uristdwarf!
Thank you for the feedback, i will take a look at the subject and make it a bit more clear.
