### ISSUE TITLE
date-is subject

### ISSUE THREAD

**Issue by mihkelgering** [01-edu/public#925]
date-is
---
```js
test #21 failed:
() => isFuture(new Date(2021, 11, 31))
Error:
Error: Test failed
    at runTests (file:///app/test.mjs:169:15)
```

Seems like an outdated test, which is expecting true output, but my code output is false, because date.now -> `2022-01-13`

**Comment by kigiri** [comment]
Thank you for the report @mihkelgering we bumped it up to 2077
