### ISSUE TITLE
get-some-time subject

### ISSUE THREAD

**Issue by Dhicci** [01-edu/public#927]
get-some-time
---
The testing isn't working right. The 01-01-1000 isn't a monday it is a wednesday. As is suggested here: https://www.dayoftheweek.org/calendar/1000
And in js Date.

**Comment by MSilva95** [comment]
@Dhicci  i will check the tests as soon as possible. thank you for your feedback

**Comment by MSilva95** [comment]
Hello again @Dhicci!
Everything is good with the exercise.
In the readme, we say the following:

```If the first week is requested and it starts on the previous year
of the presented one, it should return the first day of the year.```

So, even if it is not a Monday, the ```01-01-1000``` is a new year and we ask that if the week begins in the past year, you should return the first day of the present year.
