### ISSUE TITLE
mouse-trap subject

### ISSUE THREAD

**Issue by Rostislav-chi** [01-edu/public#928]
mouse-trap
---
the test should check not only 'background' property, but also 'backgroundColor'. 
As an alternative - possible to give more understandable error ' background "" !== "white" check if color is set as backgroundColor'

**Comment by MSilva95** [comment]
hello @Rostislav-chi, i will take a look at the tests, tank you for your feedback.

**Comment by MSilva95** [comment]
the tests are checking if the background is set to the right color
