### ISSUE TITLE
fusion subject

### ISSUE THREAD

**Issue by AaEnnDeeErrEeEss** [01-edu/public#930]
fusion
---
- Description has typos.
- Examples don't match the test requirements: in exaples arguments are shown as primitive types while tests provide objects containing these as values.

**Comment by MSilva95** [comment]
Hello @AaEnnDeeErrEeEss i will take a look at the exercise thank you for the feedback.

**Comment by uristdwarf** [comment]
Indeed, the task description doesn't say anything about 'other types' 
```js
// other types
t(({ eq }) => eq(fusion({ reg: /\w/ }, { reg: /\S/ }).reg, /\S/))
t(({ eq }) => {
  const set = new Set([1, 2, 3])
  return eq(fusion({ a: 1, set: new Set([4, 5, 6]) }, { a: 1, set }), {
    a: 2,
    set,
  })
})
```

**Comment by MSilva95** [comment]
Hello @uristdwarf. I'm changing some stuff on the  task description to make it more clear thank you for the feedback.
