### ISSUE TITLE
deep-copy subject

### ISSUE THREAD

**Issue by MM1132** [01-edu/public#931]
deep-copy
---
I was some confususion. What does you do? This is not even explanation of task. 

What do function get in parameter, and what do we return?

**Comment by MSilva95** [comment]
Hello @MM1132!
 To do this exercise you need to understand the concept of deep copy, the rest is up to you to find out, what are the arguments and what the function returns. if you study this deep copy concept you will surely know what the function takes as an argument and what it will return.
The function will have to be done recursively, as requested in the readme.
