### ISSUE TITLE
debounce test

### ISSUE THREAD

**Issue by AaEnnDeeErrEeEss** [01-edu/public#937]
In **debounce** task test 4 the expected values are `[1, 2]`. They were changed to these in one of the [commits](https://github.com/01-edu/public/commit/777087a771b18f745cd554a886fb44d03c47a4ba#diff-0b0f662ddf46c2aeb2806d38759b11e049413d4c034a683f16dc9c4664d39235L55) from `[1, 3]`.
The test case was tested with corresponding lodash function, and it returns `[1, 3]`. People solving this task in the current sprint also found that it should be the correct answer after the research they have done.
Considering that the sprint is happening now, it is quite urgent.

**Comment by MSilva95** [comment]
Hello @AaEnnDeeErrEeEss i will fix it as soon as possible. Thank you
