### ISSUE TITLE
forum-security subject

### ISSUE THREAD

**Issue by blackcloro** [01-edu/public#944]
forum-security
---
The issue is encrypting SQLite database. Despite the fact that the mattn sqlite3 package encrypts the database and adds the sqlite_user table, the sqlite3 CLI continues to give access to the database without prompting for a password.
It looks that you must build your own SQLite CLI to get it to function, and constructing my own sqlite CLI is a significant effort that I have yet to master.

-----------------
SQLite user authentication

An authentication-required database is identified by the presence of a
new table sqlite_user

The sqlite_user table is inaccessible (unreadable and unwriteable) to
non-admin users and is read-only for admin users.  However, if the same
database file is opened by a version of SQLite that omits
the -DSQLITE_USER_AUTHENTICATION compile-time option, then the sqlite_user
table will be readable by anybody and writeable by anybody
- from [SQLite docs](https://www.sqlite.org/src/doc/trunk/ext/userauth/user-auth.txtl)

**Comment by MSilva95** [comment]
Hello @blackcloro I will take a look at this exercise as soon as possible
thank you

**Comment by Gervin1** [comment]
@MSilva95 any updates?

**Comment by MSilva95** [comment]
hello @Gervin1 I will be on it today

**Comment by MSilva95** [comment]
After some inspection to this issue we do agree with you @blackcloro. We will make some small changes to the readme and audit and the encryption of the DB will become a bonus feature. Thank you for your feedback!
We will link a pr to this issue as soon as the changes are made.
