### ISSUE TITLE
Groupie Tracker API incorrect location data / typos [very minor]

### ISSUE THREAD

**Issue by nik-don** [01-edu/public#946]
### Typo
`sao_paulo-brasil`  should be `sao_paulo-brazil` 
`manila-philippine` should be `manila-philippines`

### Location
`seoul-korea` should be `seoul-south_korea`

`glasgow-australia` should be `glasgow-uk` OR `glasgow-united_kingdom`

**even better >** all - `uk` should be `united_kingdom` **<<<< preferred**

`new_york-us` should be `new_york-usa` OR `new_york-united_states`

**even better >** all - `usa` should be `new_york-united_states` **<<<< preferred**

### Other
`ostrava-czech_republic` should be `ostrava-czechia`
`prague-czech_republic` should be `prague-czechia`
(thats the official name apparently)

I know this is not a issue but I was playing with a flag API and I noticed these... 

![Screenshot from 2022-02-01 10-55-38](https://user-images.githubusercontent.com/93073558/151956138-37e807d9-2d76-4e97-84f6-f6840b2ad4fe.png)
![Screenshot from 2022-01-28 16-05-06](https://user-images.githubusercontent.com/93073558/151580788-084b6487-09fd-4785-843d-a1799c7fc4ec.png)
![Screenshot from 2022-01-28 16-04-18](https://user-images.githubusercontent.com/93073558/151580782-60ab0047-2c42-45bd-9f53-1daddffabe13.png)

**Comment by MSilva95** [comment]
I will take a look at this thank you for the feedback!

**Comment by MSilva95** [comment]
Hell @nik-don!
The fixes will be deployed soon, we cant do it right away because there are too many persons using the API at the moment.
Thank you for your feedback!

**Comment by MSilva95** [comment]
The fixes are done thank you!
