### ISSUE TITLE
dog-years subject

### ISSUE THREAD

**Issue by sariyya-abdullayeva** [01-edu/public#950]
dog-years
---
"So if you were told someone that their dog were 1,000,000,000 seconds old, you should be able to say that the dog is 221.82 Earth-years old." 

this example is not clear. Given that the function will take two parameters,  according to which planet the years are calculate?

**Comment by maximihajlov** [comment]
In subject: `Someone once said that a dog makes 7 years for each human year.`
221.82 is in Earth-DOG-years

**Comment by MSilva95** [comment]
@sariyya-abdullayeva
As @maximihajlov  explained, in the subject we explain that in Earth, 1 human year is 7 dog years, so i don't see a problem here.
