### ISSUE TITLE
index-of subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#951]
index-of
---
The task instructions do not comply with the test.

Instructions:
![image](https://user-images.githubusercontent.com/80747520/152958646-e677bc72-7e7a-489b-875f-cbfc5864232e.png)

Test:
![image](https://user-images.githubusercontent.com/80747520/152958558-33f93fc9-95c9-4d0b-829e-927c304d51c6.png)

According to the instructions we should start searching from index 2, and therefore last index of 't' should be '3' not '0'. It seems the instructions should say that in function `lastIndexOf` the parameter should be called `toIndex` instead as we need to look until that index and not starting from that.

**Comment by MSilva95** [comment]
hello @jarmo-seljamaa i will add a clarification to the readme, nothing is wrong with the tests.
"The functions should have an array element as the first argument.

Both indexOf and lastIndexOf take an additional fromIndex argument that allows you to begin searching from a specific index and it will work exactly like in the original methods."

**Comment by jarmo-seljamaa** [comment]
I see. `fromIndex` is position where to start searching from, but backwards. Thank you for the clarification!
