### ISSUE TITLE
get-some-time subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#955]
get-some-time
---
The tests reveal that the task does not follow the [ISO week numbering](https://en.wikipedia.org/wiki/Week#Numbering) rules, and instead we have to assume that week #1 is in all cases the week that contains 1st of January. The week numbering system should be stated clearly in the instructions to avoid confusion.

I solved the task following the international standard and that resulted in 'Oh Snap!':

![image](https://user-images.githubusercontent.com/80747520/153428171-002c56b0-83d9-458f-bd7e-880472d60f86.png)
![image](https://user-images.githubusercontent.com/80747520/153428210-8ad5b293-9343-4c88-9b7c-cc89a6f0975e.png)

**Comment by MSilva95** [comment]
Hello @jarmo-seljamaa i will add a small explanation on the subject.
Thank you!
