### ISSUE TITLE
get-some-time subject

### ISSUE THREAD

**Issue by gsuikanen** [01-edu/public#956]
get-some-time
---
W1 of 1983 starts a 3rd of Jan. 
W43 starts at 24th of Oct. 
https://www.calendar-365.co.uk/jpg/calendar-1983-portrait-format.jpg
Please either fix it or specify that some other week counting should be implemented.

**Comment by MSilva95** [comment]
Hello @gsuikanen I will add an explanation to the subject. Thank you!
