### ISSUE TITLE
rebecca-black subject

### ISSUE THREAD

**Issue by gsuikanen** [01-edu/public#957]
rebecca-black
---
"isLeapYear returns true if the year is a leap year"
Please specify that date object is used as parameter when calling function. By current description I assumed that it is used like: isLeapYear(2020).

**Comment by MSilva95** [comment]
Hello @gsuikanen!
Do you think this is good: 
"returns true if the year of the date is a leap year"
?

**Comment by gsuikanen** [comment]
Hi! Yes, I think it is more clear :)
