### ISSUE TITLE
gossip-grid subject

### ISSUE THREAD

**Issue by MPuust** [01-edu/public#964]
gossip-grid
---
Tester can't validate min box width. Tester only works when each gossip panel has style width overwritten. I solved the problem by changing the underlying css code.

`test #2 failed:`
```js
async ({ page, eq }) => {
  // test that you can change the width to the min

  const min = await page.$eval('#width', n => {
    n.value = n.min
    n.dispatchEvent(new Event('input'))
    return Number(n.min)
  })

  eq(min, 200)

  const values = await page.$$eval('div.gossip', getStyle, 'width')

  eq(Array(gossips.length + 1).fill(`${min}px`), values)
}
```
```diff
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  [
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px',
+   '200px'
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   '',
-   ''
  ]
````

**Comment by MSilva95** [comment]
hello @MPuust, i tested with your code and it seams to be passing, can you send me the code that failed?

**Comment by MPuust** [comment]
Hey! Here's the code with the original solution commented out and replaced with a for loop.

`export {grid}
import {gossips} from "./gossip-grid.data.js";

function grid() {

    let ranDiv = document.createElement("div")
    ranDiv.classList.add("ranges")
    let slideWidth = document.createElement("input")
    slideWidth.type = "range"
    slideWidth.id = "width"
    slideWidth.min = "200"
    slideWidth.max = "800"
    let slideFont = document.createElement("input")
    slideFont.type = "range"
    slideFont.id = "fontSize"
    slideFont.min = "20"
    slideFont.max = "40"
    let slideBg = document.createElement("input")
    slideBg.type = "range"
    slideBg.id = "background"
    slideBg.min = "20"
    slideBg.max = "75"
    ranDiv.append(slideWidth,slideFont,slideBg)
    document.body.append(ranDiv)

    let gossipForm = document.createElement("form")
    let formTxt = document.createElement("textarea")
    formTxt.placeholder = "Got anything to share?"
    let formSubmit = document.createElement("button")
    formSubmit.type = "button"
    formSubmit.textContent = "Share gossip!"
    gossipForm.classList.add("gossip")
    gossipForm.append(formTxt,formSubmit)
    document.body.appendChild(gossipForm)

    gossips.forEach((gip) => {
        let gipiv = document.createElement("div")
        gipiv.classList.add("gossip")
        gipiv.textContent = gip
        document.body.appendChild(gipiv)
        }
    )

    formSubmit.addEventListener("click", () => {
        let newEntry = document.createElement("div")
        newEntry.classList.add("gossip")
        newEntry.textContent = formTxt.value
        gossipForm.insertAdjacentElement("afterend", newEntry)
        formTxt.value = ""
        }
    )

    slideWidth.addEventListener("input", (e) => {
        let elem = document.getElementsByClassName("gossip")

        for (let node of elem) {
            node.style.width = slideWidth.value + "px"
        }
        **//document.styleSheets[0]["cssRules"][3].style.width = slideWidth.value + "px"**
        }
    )
    slideFont.addEventListener("input", (e) => {
        let elem = document.getElementsByClassName("gossip")

        for (let node of elem) {
            node.style.fontSize = slideFont.value + "px"
        }
        **//document.styleSheets[0]["cssRules"][3].style.fontSize = slideFont.value + "px"**
        }
    )
    slideBg.addEventListener("input", (e) => {
        let elem = document.getElementsByClassName("gossip")

        for (let node of elem) {
            node.style.background = `hsl(280, 50%, ${slideBg.value}%)`
        }
        **//document.styleSheets[0]["cssRules"][3].style.background = `hsl(280, 50%, ${slideBg.value}%)`**
    })

}`

**Comment by MSilva95** [comment]
I think this is a hard way of doing the exercise and i didnt find many info on it, i am not sure if it works for all browsers as well
But we took a look at the code and apparently the code, that failed changes, the main css and not the css from each gossip.
For now the test are working fine for a clean simple solution with the for loops we will not change the tests now but thank you for your feedback!
