### ISSUE TITLE
interpolation subject

### ISSUE THREAD

**Issue by jaaguplasn** [01-edu/public#970]
Interpolation
---
Tests occasionally fail with the same code that passed the test

![randomerror](https://user-images.githubusercontent.com/83555025/154649237-764c87f0-5e5d-4d4e-8e5c-ecc601bd80fc.png)

**Comment by Shushlik** [comment]
same code can produce 3 different results for me.
![image](https://user-images.githubusercontent.com/88344427/154650061-2c7eda2c-cd80-4d0f-a250-669564d9b8d4.png)
