### ISSUE TITLE
using-reduce subject

### ISSUE THREAD

**Issue by santeri13** [01-edu/public#974]
using-reduce
---
I have a code which is right solution but system say that it is not, 
```
const funcExec = (obj,initialValue=0) => {
  const sumWithInitial = obj.reduce(
      (previousValue, func) => func(previousValue),
      initialValue
    );
  return sumWithInitial;
}
```
Error: func is not a function

**Comment by MSilva95** [comment]
Hello @santeri13!
Are you sure that you tested with this code?
I tested this code with my solution and it works fine.

I've checked on gitea in the user "santeri" and you don't have a correct code there. 
```js
const funcExec = (obj) => {
    if(arguments[1]) {
        return obj.reduce((previousValue, func) => func(previousValue), arguments[1])
    }
        return obj.reduce((previousValue, func) => func(previousValue), 0)
    }
```

Please confirm me if this is your gitea:
https://git.01.kood.tech/santeri/piscine-js-2/src/branch/master/using-reduce.js

**Comment by santeri13** [comment]
I tested it and there was a problem that it always give me an error but now when time for receiving exp is passed now it works.

**Comment by MSilva95** [comment]
For now i have test it and the test is working fine, and as you passed the exercise i will close the issue.
Thank you for your feedback!
