### ISSUE TITLE
manipulate-values subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#975]
manipulate-values
---
I think the **Code Provided** section is a bit misleading because it seems the `nutritionDB` is not necessary for the solution, it is only used in testing. I found this confusing as the task was to manipulate the items in the cart that have **name** and **value in grams**, but there are no instructions on what to think of the nutritional data in the **Code Provided** section. 

It looks like the nutritional data will enter the game two tasks later, in the manipulate-entries. Perhaps it was intended to provide code for `groceriesCart` object instead?

**Comment by MSilva95** [comment]
The nutritionDB is only there for you and us to test your solution, it is not asked on the readme to use it.
We will not remove it from there because it serves as an introduction for the next exercises as well

**Comment by jarmo-seljamaa** [comment]
A short comment of explanation would be enough. It is hard to understand what to think of the nutritionDB provided if the task explicitly instructs to manipulate items that have a name and value in grams (not values in nutrition data). Just too confusing.
