### ISSUE TITLE
is-winner subject

### ISSUE THREAD

**Issue by Aamsua** [01-edu/public#978]
is-winner
---
I would change in test 6 ( // testing correct number of times and correct continent) the country from Germany to France,
because it tests for 4 wins. With France it would test for 2 wins like the minimum of the task (If the country was champion in more than one year). At the moment you can pass the test also with wrong code.

**Comment by MSilva95** [comment]
Hello @Aamsua!
So, about the test, wen cant change germany to france because the minimum is not one but 3 wins as explained bellow
```
- `<country> + ' is not what we are looking for because of the number of times it was champion'`, if the country passed in `isWinner` was champion
  less than 3 times

- `<country> + ' won the FIFA World Cup in ' + <year(s)> + 'winning by ' + <results>`, otherwise. ```

I removed the misleading phrase from the readme and added this:
```The years and results should be displayed like bellow:

<country> + ' won the FIFA World Cup in 1000, 1004, 1008 winning by 4-3, 5-2, 1-0
 ```
This will be merged soon, meanwhile can you send me the wrong code that passes the tests?

**Comment by Aamsua** [comment]
I read " If the country was champion in more than *one* year."

But in this case, if you didn't change the tests - my wrong code would pass
the tests again , because the tests look for more than one win (not more
than 3).

I passed the test with these code lines:
[image: image.png]

Best regards,
Martin



Kontakt MSilva95 ***@***.***>) kirjutas kuupäeval K, 23.
veebruar 2022 kell 12:45:

**Comment by MSilva95** [comment]
@Aamsua the image of the code was not loaded.

**Comment by Aamsua** [comment]
my code :
async function isWinner(country) {
    try {
        let nation = await db.getWinner(country)
        if (nation.continent !== 'Europe') return nation.name + ' is not
what we are looking for because of the continent'
        let res = await db.getResults(nation.id)
        if (res.length < 1) return nation.name + ' is not what we are
looking for because of the number of times it was champion'
        else {
            let result = country + " won the FIFA World Cup in "
            res.forEach((wins, index) => {
                result += wins.year
                if (index !== res.length - 1) result += ", "
            })
            result += " winning by "
            res.forEach((wins, index) => {
                result += wins.score
                if (index !== res.length - 1) result += ", "
            })
            return result
        }

    }
    catch (err) {
        return country + ' never was a winner'
    }
}


Kontakt MSilva95 ***@***.***>) kirjutas kuupäeval K, 23.
veebruar 2022 kell 14:52:

**Comment by Aamsua** [comment]
Sorry, because I played a bit with the code, I forgot to change it back.
This is the code that passes the test :
async function isWinner(country) {
    try {
        let nation = await db.getWinner(country)
        if (nation.continent !== 'Europe') return nation.name + ' is not
what we are looking for because of the continent'
        let res = await db.getResults(nation.id)
        if (res.length < 2) return nation.name + ' is not what we are
looking for because of the number of times it was champion'
        else {
            let result = country + " won the FIFA World Cup in "
            res.forEach((wins, index) => {
                result += wins.year
                if (index !== res.length - 1) result += ", "
            })
            result += " winning by "
            res.forEach((wins, index) => {
                result += wins.score
                if (index !== res.length - 1) result += ", "
            })
            return result
        }

    }
    catch (err) {
        return country + ' never was a winner'
    }
}

Kontakt Martin Ausmaa ***@***.***>) kirjutas kuupäeval K, 23.
veebruar 2022 kell 15:01:

**Comment by MSilva95** [comment]
Ok, i will add one more test to the test file, thank you for the catch!
