### ISSUE TITLE
listpushback subject !

### ISSUE THREAD

**Issue by KamalZ18** [01-edu/public#982]
Hi to EDU guys/girls,

about the Piscine Week Four #43 Tasks,

there is no mention of which Repository on Git Tea to utilise ?

should we create a New Repo ?

I have completed Task - Program: listpushback.go
and pushed it onto the Piscine Repo,
but when I clicked on Run ListPushBack Test,
it displayed an Error msg: Not Found on Repo.
---
thank you, regards, Kamal H. Zada.

**Comment by MSilva95** [comment]
Hello @KamalZ18!
All the exercises in the piscine must be in the piscine-go repo.
Confirm if you wrote something wrong on the name of the exercise

**Comment by KamalZ18** [comment]
Hi to @MSilva95,

**this exercise is not exactly in the Piscine,
it is in the Piscine Week Four Tasks, Quest 11.**

**When I completed the Task - Program: listpushback.go,
I pushed it onto the piscine-go Repo,
but when I clicked on Run ListPushBack Test,
it displayed an Error msg: Not Found on Repo.**

**This means that this exercise must NOT be in the piscine-go repo;
a new Repo must be created ;
please could you find out the name of the new Repo
and update the description of the 
Piscine Week Four Tasks, Quest 11
to mention the new Repo name !**

thank you, regards, Kamal H. Zada.

**Comment by Frenchris** [comment]
Check the name in the url. 
If you are submitting the exercise in 
https://demo.01-edu.org/intra/london/**piscine-go**/quest-01/introduction
**piscine-go** has to be the name of the repository
and the repository must be created on **git.demo.01-edu.org**
https://beta.01-edu.org/intra/london/**piscine-go-4-week**/quest-01/introduction
**piscine-go-4-week** has to be the name of the reposity
and the repository must be created on **git.beta.01-edu.org**

**Comment by Frenchris** [comment]
> 

Je vais bien merci :)

That URL is the one that you see when you are on the page of the subject of the piscine you are in. It is just the one in your browser.

My pleasure.

**Comment by KamalZ18** [comment]
OK, merci.
