### ISSUE TITLE
make-it-better subject

### ISSUE THREAD

**Issue by Frasse75** [01-edu/public#993]
`--time-style='+%F %R'`  does not seem cross platform with Mac. 

```
maugisf@maugisf-EMD6M piscine-go % TZ=utc ls -l --time-style='+%F %R' | sed 1d | awk '{print $1, $6, $7, $8, $9, $10}'
ls: illegal option -- -
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]
```

**Comment by MSilva95** [comment]
Hello @Frasse75! 
For now i think you can install "coreutils" to get the GNU version of ls, which includes the (--time-style). I will change the readme according to this issue.
Thank you for your feed back!

**Comment by leviet0115** [comment]
Hi @MSilva95!I've installed coreutils, but the error remains (please see the screenshot below). <img width="632" alt="Screen Shot 2022-03-17 at 11 15 27" src="https://user-images.githubusercontent.com/64316728/158783626-39a2d1bd-ec37-427a-9f44-6a06c8d5b89a.png">

**Comment by MSilva95** [comment]
Can you try it like this and see if its working? I don't have a Mac so its difficult to test sorry for the inconvenient.
I saw something online that says that commands installed with brew may have added the prefix g. e.g. ls vs. gls, find vs. gfind
```TZ=utc gls -l --time-style='+%F %R' | sed 1d | awk '{print $1, $6, $7, $8, $9, $10}'````

**Comment by leviet0115** [comment]
Yes, I test it and it works now. Are we going to change the command line the assignment instruction to this new one?

<img width="634" alt="Screen Shot 2022-03-17 at 13 24 39" src="https://user-images.githubusercontent.com/64316728/158798929-aff469f2-19fd-447b-9a46-b94dbc9b9ec5.png">

**Comment by MSilva95** [comment]
i will add a note explaining how mac users should proceed to run the command

**Comment by leviet0115** [comment]
Got it! Thanks for your help, @MSilva95.
