### ISSUE TITLE
isnegative the task doesn't suggest changing package name to piscine

### ISSUE THREAD

**Issue by ismanaraev** [01-edu/public#994]
Task description doesn't specify that you need to change package name from "main" to "piscine" and by not doing so, you awoke an error
---

**Comment by MSilva95** [comment]
Hello @ismanaraev! 
In the exercise we ask you to write a function and not a program so we don't need to specify what package you need to use, this is up to you to learn from the begging of the piscine. 
The Program given in the exercise is just to test the function you will create and should not be submitted.
