### ISSUE TITLE
more-or-less subject

### ISSUE THREAD

**Issue by HanaAbdi** [01-edu/public#995]
more-or-less
---
English - less that takes 1 argument and substract 1 to it

- Should be less that takes 1 argument and subtract 1 to it

**Comment by HanaAbdi** [comment]
English fix -  issue: sub that takes 2 arguments and substract them

Should be sub that takes 2 arguments and subtract them

**Comment by MSilva95** [comment]
Hello @HanaAbdi !
The requested changes were made in the PR linked to this issue. 
Thank you for the feedback!
